- lib/Drush/Migrate/MigrateManifest8.php
This is necessary after changes being discussed in [#2384529: Make the class variables protected for Migration](https://www.drupal.org/node/2384529). While that issue is not committed yet, the changes in this commit will work even now, and will continue to work after the issue is committed.
Note: There might be direct getter methods but that is under discussion in that issue. However, the changes in these pull request don't rely on those methods.
> Use the get() and set() methods to set source and destination on a migration.

- includes/preflight.inc
Prevent PHP warnings caused by the @ error suppression directive, when only the the global vendor autoload.php is present.
Tested on php 5.5
> Fix autoload warning. 

- commands/core/search.drush.inc
Updated search-index and search-status to check for
drupal_major_version >= 8 and if so use drupal 8 specific
code to get the remaining search items and update the search
index.
> Updated search-* commands to work with Drupal 8

- commands/core/site_install.drush.inc
```drush site-install``` wipes all files in config dirs during installation. Please add an option to keep these config files. Otherwise it is not possible to install Drupal from CLI with [Config Installer](http://drupal.org/project/config_installer].
Example command
```
drush si config_installer --keep-config -y config_installer_staging_configure_form.staging_directory=../config/staging config_installer_site_configure_form.account.name=foobar config_installer_site_configure_form.account.pass=foobar config_installer_site_configure_form.account.mail=foobar@example.com
```
// cc @alexpott
> Keep configuration in confgis dirs during installation

- docs/configure.md
- drush.complete.sh
It's very easy to set up shell auto-completion for ZSH as well as BASH, but this isn't documented anywhere officially.
I added the small amount of information to the documentation, which works quite well for me.  The details are originally from [Use Drush Autocomplete with Zsh](http://mark.shropshires.net/blog/use-drush-autocomplete-zsh).
> Explain how to set up ZSH autocompletion in the docs

- commands/pm/package_handler/wget.inc
- commands/pm/pm.drush.inc
I hate having to wait for all the MD5 hashes to be updated properly in order to download new module updates. Can we provide an option to bypass it?
> Added --force option to pm-download to skip MD5 validation.

- lib/Drush/Boot/bootstrap.inc
https://www.drupal.org/node/2348679 has landed. DRUPAL_BOOTSTRAP_PAGE_CACHE no longer exists.
> Remove DRUPAL_BOOTSTRAP_PAGE_CACHE from Drupal 8 bootstrap

- drush
I get the following error when I run Drush with xDebug enabled:
Command stderr:
/usr/local/drush/drush: line 129: [: -le: unary operator expected
> Fix unary operator expected error.

- lib/Drush/Migrate/MigrateManifest8.php
- tests/migrateManifestTest.php
Source and destination are no longer public since: https://www.drupal.org/node/2384529
Somewhere in Drush the return result becomes an array so I added source and destination to the return because we don't have the full migration object in the test.
> Fix migrate tests

- drush
Reverts drush-ops/drush#1115
This commit works fine on my local machine, but the Travis build breaks.  I'm not sure why this is; perhaps Travis is not set up to use bash?
I'm going to revert this to see if we can get the tests to go green again.  I'm not opposed to putting it back in later, but it would be good to know what limitations this might introduce.  Does anyone have any idea why the [[ ]] form is required with xDebug?  I don't think I had this problem, but I haven't installed xDebug on my new laptop yet, so I'll have to return here later to try it out.
This is also my first go at using the "revert" button on GitHub -- let's see how it works out when I click "create pull request".
> Revert "Fix unary operator expected error."

- composer.json
- composer.lock
This is important, because if Drush is included as a requirement in some other project's composer.json, it will inherit the minimum stability of the root project. Therefore, any setting less than 'stable' could cause problems when including Drush from a project that required stable releases.
I kept the directives "minimum-stability" and "prefer-stable", for documentation.
In order for Composer to work correctly, we must insure that our minimum-stability is no less stable than the release that it appears in.  In other words, a stable Drush release should always use "stable", but a beta release could use "beta", and a dev release could use "dev".
It is simplest, of course, if Drush works with the latest stable release of each of its dependencies.
> Change minimum stability to 'stable'.  

- includes/engines.inc
This was causing an annoying warning after many drush commands, e.g. drush status.
Making a PR to make Travis run the test suite.
> Make drush_merge_engine_data() idempotent.

- commands/core/drupal/batch.inc
While fixing the `drush sapi-i` (https://www.drupal.org/node/2230949) command, I noticed that the `batch.inc` file in D8 was slightly altered. The finished callback doesn't use the function `function_exists`, but uses `is_callable` instead. This way namespaced methods can be passed in a decent way (cf original issue on d.o https://www.drupal.org/node/1924420).
Since this change is not very intrusive and should not break things for D6 and D7, I immediately created this PR.
> Fixed 1924420: finished callback exisiting check handling

- commands/core/sitealias.drush.inc
- includes/sitealias.inc
This is a bugfix for the --with-db-url flag in the site-alias command.
See:
http://drupal.stackexchange.com/questions/97380/convert-database-object-into-database-url-string
Making a PR for Travis.
> Fix site-alias option --with-db-url

- lib/Drush/Sql/Sqlmysql.php
In the follow up to #365 (commit ac050dd) the defaults-extra-file is only created if a password is given. This means that --db-su=root has no effect without the (optional) argument --db-su-pw being set when running site-install. The username is simply ignored.
> Ensure that --db-su works without --db-su-pw for site-install

- commands/core/sitealias.drush.inc
- includes/sitealias.inc
Just putting this in the queue for Travis.
I did update .travis.yaml to get one branch tested, but then I had to put it back before merging with master. Is there a way to tell Travis to test a branch that contains a pattern, but NOT if it's on the master branch (UNLESS it IS a pull request)?  Probably not.  Just wondering if there's something we could live with that stayed in .travis.yaml all the time.
> Silence a warning when an alias record does not contian a 'root' element

- examples/example.bashrc
> example.bashrc doesn't work with symlinks

- commands/core/drupal/update.inc
- Show them in the list
- Execute them first as a single batch (not very pretty, but exactly like core does it now)
- Also implemented a missing function needed for drush updbst, copy from 7.x + showing the change summary there as well.
> Support entity updates in drush updb

- includes/command.inc
#1218 was not the first instance of someone using "--option value" where "--option=value" is expected.  This PR adds sanity checking, and reports an error if an option that is expected to have a value is not provided one.
> Fail with an error message if the user omits a required option value

- lib/Drush/Boot/bootstrap.inc
I guess it needs more refactoring, but for now, I just switched to use the drush constants and cleaned it up, because nothing was calling it with anything else but configuration or full. Also nothing uses the return value.
Not sure what a proper fix would look like...
> Workaround for removed drupal bootstrap constants.

- commands/core/role.drush.inc
This prevents the cache clear from running after modifying permissions if no permission was modified, since it isn't needed in that case.
> Don't run cache clear after remote-add/remove-perm if no permission was added/removed

- includes/drush.inc
Fix the multiple-site invoke to take care not to pass "php" and "php-options" in, so that they are not forwarded to remote systems.
> Bug fix for #324

- drush.complete.sh
- includes/sitealias.inc
- tests/siteSetUnitTest.php
The "drush use @site-alias" feature does not work on a system with more than one user account using the feature.
From a real life experience today:
```bash
$ whoami
arne
$ ls -ld /tmp/drush-env
drwxr-xr-x 2 root root 4096 2013-09-04 18:25 /tmp/drush-env
```
Since another user has already created the `drush-env` folder I'm not able to set my environment.
This pull request incorporates the user ID in the folder name.
> User-specific temp directories

- includes/context.inc
- includes/preflight.inc
This patch insures that our selected site is set prior to the site bootstrap phase, so that we don't have to go back and fix up anything if uri changes in the sites drush config file.
> #800: Allow sites/[site]/drushrc.php to change the value of 'uri'.

- includes/preflight.inc
This sometimes poisons the context cache which can then cause type
errors later at places like drush_set_config_special_contexts() when
trying to merge options.
> Don't mix basic types

- includes/bootstrap.inc
We should recommend that Drush extensions that have composer.json files should call drush_autoload in their hook_init. This will allow us the flexibility to support extensions in the vendor directory, once we have an efficient mechanism for doing that, while still allowing folks to write extensions that can still go in the usual places.
Today, extension writers have to put their own logic for finding and including their autoload file, which is not optimal. We already have drush_autoload() in Drush 7; it would be low-impact to have it in Drush 6 as well, which will help folks who want to be compatible with the recommended Drush 7 mechanism without becoming incompatible with Drush 6.
> Backport drush_autoload() from master branch.

- commands/core/drupal/site_install.inc
- commands/core/drupal/site_install_7.inc
- commands/core/site_install.drush.inc
Instead of always falling back to `standard` this allows lazy people to just type `drush si` and Drush will install
a distribution installation profile if there is one. This makes `drush si` consistent with the behavior of `install.php`
> Automatically detect a distribution installation profile when installing Drupal 8

- commands/core/core.drush.inc
- includes/command.inc
- lib/Drush/Boot/BaseBoot.php
This is in case a command with a low bootstrap requirement invokes another command with a higher bootstrap requirement.  The only example we have of this today is drush quick-drupal, and qd must still explicitly set the selected site and call bootstrap, because it wants to bootstrap to a site that didn't even exist.
I think it's good to put this in for clarity, but at the moment it is a redundant step.  Let me know what you think.
> Insure that we have reached the right bootstrap level in drush_dispatch()

- commands/core/drupal/environment_6.inc
- commands/core/drupal/environment_7.inc
There are warnings generated (and missing information) when running 'drush core-requirements' on an installed d6 or d7 site due to the fact that arguments are not passed to module_invoke_all() from drush_module_invoke_all().
> Fix #825. Argument passing to module_invoke_all().

- lib/Drush/Boot/DrupalBoot.php
- lib/Drush/Boot/DrupalBoot6.php
- lib/Drush/Boot/DrupalBoot7.php
- lib/Drush/Boot/DrupalBoot8.php
Defined separate methods to return the locations where modules and themes can be found.
> #1256: Split out contrib-paths from commandfile_searchpaths()

- commands/make/make.utilities.inc
- docs/make.txt
- tests/makeTest.php
- tests/makefiles/includes-main.make
- tests/makefiles/includes-platform.make
- tests/makefiles/includes-sub-platform.make
This is a backport of https://github.com/drush-ops/drush/pull/1063 (please see PR for full documentation on the matter) for the 6.x branch. 
Mentioned PR is already reviewed, tested and merged into master. It would be great if we can do the same for the 6.x branch.
Thanks!
> [Backport] Add support for git repositories in the 'includes' directive.

- commands/pm/pm.drush.inc
For some reason, the --lock feature of pm-updatecode explicitly excludes core.  This PR enables --lock with core, which is very useful if you are in a managed hosting environment with a custom core (e.g. pressflow at Pantheon).
> Respect --lock=drupal in pm-updatecode.

- commands/core/config.drush.inc
- tests/configTest.php
This is a start on #1163. It shouldn't be too much more work to allow for directory imports of partial config sets.
> Config import partial

- commands/make/generate.contents.make.inc
- commands/make/make.drush.inc
- commands/make/update.make.inc
The purpose of this command is to improve and replace --lock-update. It uses the update_status engine to generate an updated makefile.
> Add make-update command

- commands/core/core.drush.inc
- commands/runserver/runserver.drush.inc
- includes/sitealias.inc
This is a continuation of #1177, with the creation of the drushrc.php file moved from the runserver command to the quick-drupal command.
It is very useful to record the port used when running qd, as it helps subsequent commands to be correctly targeted, should they need to use the 'uri' for any reason.
I would like to see this in the 7.0-rc1 release, if possible.
> Move uri cache from runserver to qd

- lib/Drush/User/UserSingleBase.php
This is related to the commit of https://www.drupal.org/node/1548204, which removed user signatures.
> Fixes Drush with D8 user signatures change

- commands/core/core.drush.inc
- commands/core/field.drush.inc
- commands/core/role.drush.inc
- commands/core/topic.drush.inc
- commands/core/variable.drush.inc
- includes/drush.inc
- includes/preflight.inc
- includes/sitealias.inc
- tests/Unish/CommandUnishTestCase.php
- tests/pmDownloadTest.php
Here's a proposed patch that defines an exit code (75) that Drush returns if the user cancels.  Also defines a mechanism for Drush to set other exit codes, if desired.  (Currently, only "0" or "1" is ever returned.)
> Fixes #1265:  Define an exit status code for user aborts.

- includes/sitealias.inc
Drush had trouble finding aliases in the 'sites' folder early in the bootstrap.
This is a simple bugfix, that brings the behavior of `drush @foo command` in line with the documentation, and `drush sa @foo`, for aliases defined in ROOT/sites/default/aliases.drushrc.php.
I'll merge this if the tests come up clean.
> Fixes #1241: Make Drush better at finding site aliases in the sites folder

- examples/example.aliases.drushrc.php
- examples/policy.drush.inc
- includes/sitealias.inc
Deprecate 'parent' element in site aliases, for eventual removal (probably in Drush 8).
> Add a hook_drush_sitealias_alter, with documentation.

- commands/make/make.utilities.inc
Right now the defaults are not applied in deep. If a project has a level 1 key, the will override the default without checking in deep. See #1307.
> Make defaults apply in deep

- README.md
The FAQ section was formatted in a fenced code block, which looked kind of funny but also made the embedded link non-functional.  I changed it to a blockquoted section and added a little styling for emphasis.
> Remove code-formatting from FAQ section

- includes/drush.inc
first tried fixing the issue described here in https://www.drupal.org/node/2487632, but it seemed that the better place was to fix this in `drush_op()`.
the issue is when calling `drush_op()` via a D6 -> D8 migration, the migrate-manifest command is showing lots of PHP notices during console output:
```
$ drush migrate-manifest --legacy-db-url=mysql://user:@127.0.0.1/test-drupal-redesign-devdrupal migrate-manifest.yml --verbose --debug
Calling ::import() [3.37 sec, 48.87 MB]                                                                                                                                                            [debug]
Running d6_system_maintenance [3.38 sec, 48.89 MB] …
```
> Adds checks for class methods to drush_op()

- commands/core/core.drush.inc
- commands/core/sitealias.drush.inc
- examples/example.bashrc
Avoid conflict with the new --local global option.  See related issue #1340.
> Rename the --local flag of drupal-directory and site-alias to --local-only

- commands/make/make.utilities.inc
- docs/make.md
Implement a shorthand for the case we have only the `url` key under project/library `download`.
```yaml
projects:
mymodule:
download: http://example.com/modules/mymodule.git
libraries:
thirdpartylib:
download: http://example.com/libs/thirdpartylib.min.js
```
is equivalent to:
```yaml
projects:
mymodule:
download:
url: http://example.com/modules/mymodule.git
libraries:
thirdpartylib:
download:
url: http://example.com/libs/thirdpartylib.min.js
```
> Shorthand for download[url] in make file

- commands/make/generate.contents.make.inc
This fixes issue #1054. I basically just added a recursive array_filter() re-implementation that allows '0' values to remain.
> Fix #1054 by more selectively pruning empty project array items.

- commands/core/drupal/update.inc
I was testing custom updates and they just silently didn't do anything.
I don't know why exactly but it looks like the .install file is (no longer?) included, so those functions weren't found and silently ignored.
I made sure that the necessary .install file is loaded and also added an error if a function can't be found.. it's not something that should ever happen (with my fix..), but if it does, then there is at least an error.
> Load install file before running update function

- lib/Drush/Boot/DrupalBoot8.php
I got the error today about "Drush 7.0.0 does not support Drupal 8." but it took me a good 10-15 minutes to figure out how to fix that. (Luckily these instructions still work https://drupalize.me/blog/201408/upgrading-drush-work-drupal-8)
Let's give people a bit more help.
> Give a little bit more help getting to Drush 8

- commands/core/config.drush.inc
When running config-merge in rsync mode, it is often the case that the default 'config' directories are not writable by the web server.  In this case, --temp must be used, or config-merge will fail.
In the instances where the 'config' directories _are_ writable, there is never a need to export the configuration to these locations; --temp is always a workable option when in rsync mode.  --temp is already ignored when using --git.
This patch makes --temp the default for rsync mode, as this is a more sensible default.
> Default to --temp mode when not using --git in config-merge.

- commands/core/outputformat/yaml.inc
Set the `objectSupport` flag to TRUE. Fixes #1417.
> Also support objects in the YAML formatter.

- .travis.yml
- composer.json
- composer.lock
- docs/configure.md
- docs/install.md
- drush
- drush.php
- examples/example.bashrc
- includes/preflight.inc
- lib/Drush/Sql/SqlVersion.php
- Lets avoid using Drupal 5.4 features for a while so commits are more easily backported
- Unish test suite now tests on 5.5 by default. The *-fulltest branches have broader PHP version testing.
> Raise minimum PHP to 5.4.5 (like Drupal 8)

- commands/core/queue.drush.inc
- lib/Drush/Queue/Queue6.php
- lib/Drush/Queue/Queue7.php
- lib/Drush/Queue/Queue8.php
- lib/Drush/Queue/QueueBase.php
- lib/Drush/Queue/QueueInterface.php
- tests/resources/queue_script-D7.php
- tests/resources/queue_script-D8.php
* Adds exception handling to queue running (including the SuspendQueueException logic from Drupal 8). An exception should not prevent the rest of the queue items from being processed.
* Adds a summary message of how many items were processed. Currently you get absolutely no output from the queue-run command unless there was an exception.
> Improve queue running (exception handling, time limits, summary messages)

- commands/make/make.project.inc
Setting GIT_DIR in Windows must be done through "set" command. Instead of doing this, I switched from environment variable to the command parameter.
Output for a failing run on Windows:
Executing: cd D:/tmp/drupal-exec11-tmp/make_tmp_1431341027_555087e3bb150/__build__/sites/all/modules/contrib/conditional_fields && GIT_DIR=. git apply --check -p1 D:/tmp/drupal-exec11-tmp/make_tmp_1431341027_555087e3bb150/IEF_compatibility-2193025-14.patch --verbose
'GIT_DIR' is not recognized as an internal or external command,
operable program or batch file.
The attached commit is tested on Windows and should also work for Linux users as the fix rely on git commands and not the environment. Should also be tested on Linux.
An **alternative Windows only solution** that might work (not tested):
'cd %s && …
> [Windows] Using git command argument instead of GIT_DIR environment variable

- includes/environment.inc
When I do a drush updb in this directory /var/www/example.com/sites/example.com/modules,I would expect it to run the database update for my site.  This use to work in version 5 but  not when updated to version 7.x it has stopped working.  This is the error I get when running the command. 
```
drush updb
Command updatedb needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                                                                                        [error]
The drush command 'updb' could not be executed.                                                                                                                                                                                              [error] …
```
> Order of operations fix when discovering drupal root.

- drush.complete.sh
- examples/example.prompt.sh
Git has a nice option to colorize your PS1 Git string using a `GIT_PS1_SHOWCOLORHINTS` environment variable. I would like to be able to color my PS1 Drush string as well, to give a visual indication of the environment my active Drush alias points to. This pull request accomplishes just that. Following the instructions at the top of the new `examples/example.prompt.sh` results in the prompt depicted below, for example:
> Add option to colorize Drush PS1 with DRUSH_PS1_SHOWCOLORHINTS

- commands/core/sitealias.drush.inc
- examples/example.bashrc
- includes/sitealias.inc
- tests/siteSetTest.php
There are ~~two~~ *three* prerequisites for this patch:
1. The user must source examples/example.bashrc
2. The user must also define `alias cd=cddl`
3. *The user must use a PS1 that contains $(__drush_ps1)*
If ~~both~~ *all three* of these are true, then with this PR, any time the user 'cd's to a Drupal root that has a matching site alias, their prompt will switch to contain the name of the alias to the current site.
There is also a change in behavior here.  If the user 'cd's to a directory that does not contain a Drupal site, then Drush will automatically `use @none`.  This insures that your prompt matches your cwd; however, without this PR, you could formerly `use @alias`, and have your site selection persist when 'cd'ing to different non-Drupal directories.
It would be easy enough to …
> Automatically set prompt to the alias record for the current site

- mkdocs.yml
The currently used method is deprecated and will be removed in a future release of MkDocs.
> Update MkDocs pages config

- commands/core/cli.drush.inc
It would be cool to have a local `$container` variable available in the REPL.
> Make a local $container variable available in drush cli

- commands/core/drupal/environment.inc
As identified in #1469, `drush_watchdog_severity_levels` uses the wrong keys for severity levels. This PR properly maps the RFC 3164 severity levels to watchdog severities.
> Issue #1469 - use correct class for defining severity levels.

- examples/example.aliases.drushrc.php
- includes/preflight.inc
- includes/sitealias.inc
- tests/siteAliasTest.php
Currently, Drush only considers alias files that appear immediately inside any given alias searchpath directory.  This PR expands the search to include any directory that is anywhere deep inside any specified searchpath directory.
For the most part, this should not cause Drush to search for alias files too deeply.  The current default alias search path only includes folders that are specific to Drush.  For example:
```
/etc/drush
$HOME/.composer/vendor/drush/drush
$HOME/.drush
$ROOT/drush
$ROOT/sites/all/drush
$ROOT/../drush
```
I'm not sure why Drush searches its own directory for aliases, but it does.
These directories do, for the most part, only contain Drush files, and therefore should not be too crowded with deeply-nested folders.  The one exception here is $HOME/.drush, which might …
> Allow Drush to search recursively inside any specified alias path.

- lib/Drush/Boot/Boot.php
- lib/Drush/Boot/DrupalBoot.php
Drush is unable to detect drupal-version-specific commandfiles without a full bootstrap.
This is not neccesary for such commandfiles that only want to operate on `DRUPAL_ROOT` or `DRUPAL_SITE` phases. Indeed it is very bad if the site is not installed yet.
My case: I'm willing to provide `settingsphp.d8.drush.inc` and `settingsphp.d7.drush.inc` for https://www.drupal.org/project/settingsphp. Drush fails with "command not found" because I'm running on a site not installed yet so it can't bootstrap to `DRUPAL_FULL` and the commandfiles are not reachable from the Drush preflight phase.
> Stop by bootstrap to DRUPAL_ROOT when searching for commandfiles

- docs/cron.md
By doing `sudo -u www-data`, this assumes that the `www-data` user has a home to install said cron, which isn't always the case. `crontab` has it's own user argument.
> Fix crontab user argument

- commands/make/make.project.inc
If a translation fails to download, you get a completely unhelpful error message:
Could not retrieve l10n update url for
This is because there's no such variable $project.
Surprisingly, I think this has been a bug for over 4 years (ever since the feature to pull translations was added): https://github.com/drush-ops/drush/commit/ab353291b39cccdbd69f51887d1f963196c1509c
> (make) Fixed error when translation download fails.

- commands/core/drupal/update.inc
```
Parameter 1 to update_entity_definitions() expected to be a          [warning]
reference, value given batch.inc:149
```
> Follow-up to #1504: Fix parameter reference warning.

- includes/drush.inc
Fix #1292 
Adds a default mime type for .sql files since finfo returns application/octet-stream for that file type.
> fix(mimetype) Add mime type for .sql files

- docs/make.md
- examples/example.make.yml
Fixes #1470 by updating the drush make documentation to specify that version strings should be in quotes.
> Drush make docs: use quotes for version strings.

- commands/core/drupal/update.inc
- Displays any error (or informational) messages set during update
hooks.
- If an error is set during updates, updb will now exit non-zero.
- Fixes #1509
> Add an update finished callback.

- commands/make/make.drush.inc
I was noticing that when you do a
```drush make xxx.make --projects=drupal```
On a current site so that it's updated, the top-level files are not copied, this is because an attempt to prevent removing top-level directories possible when overwriting files.
Probably not the best way of doing all this, see #1269 , but this is a fix following the same logic.
> Make sure top-level files are also merged

- lib/Drush/Boot/DrupalBoot.php
This change fixes the search path discovery for top-level drush/ directories.
```php
$searchpath[] = $drupal_root . '../drush';
```
Translates to ```path/to/drupal/docroot../drush``` instead of ```path/to/drupal/docroot/../drush```. This breaks inclusion of drush configuration and commands and aliases within a top-level drupal/drush folder.
The workaround is to use sites/all/drush.  However, many users might not want to put custom commands and drush configurations in a web-servable location such as sites/all/drush -- especially custom commands and code. It's far safer to keep these commands and code outside of the server-executable context.
Minimalist fix is to restore the slash that was there in drush 6.
```php
$searchpath[] = $drupal_root . '/../drush';
``` …
> Fix search path handling for top-level drush/ directory

- includes/environment.inc
fixes issue #1226 
simple change to `_drush_convert_path()` function in `includes/environment.inc` to filter out alteration of `/cygdrive/` paths when the php is cygwin's php - I've not tested under cygwin with the standard non-cygwin-based php so this change may have broken that scenario.
> fix for use under cygwin's php

- includes/sitealias.inc
- tests/siteAliasTest.php
This is an alternative fix for #1536, which broke the ability to specify aliases in `sites/default/foo.aliases.drushrc.php`.
Now with tests!
> Prevent site alias discovery from recursing into the files directory.

- lib/Drush/Boot/DrupalBoot.php
Symfony's algorithm to obtain the base url wants $_SERVER['REQUEST_URI'] to contain a url based on the site base url. We are enforcing / and it is wrong for sites installed in a subdir.
This fixes `uli` command dfor Drupal 8 and is still compatible with Drupal 7 (and 6, I guess).
Reference: https://api.drupal.org/api/drupal/core!vendor!symfony!http-foundation!Request.php/function/Request%3A%3AprepareRequestUri/8
> Tweak server global variables to suit Symfony algorithm. Fixes #1535.

- commands/core/config.drush.inc
To fix #1563 we need to add ConfigException namespace importing.
As result:
> Fix the catch ConfigException

- commands/make/make.utilities.inc
This fixes a simple typo in the path check for libraries, when checking for malicious paths. Everywhere else, this check is done with `contrib_destination`, but for libraries, it was `contrib-destination`.
> Fix typo in libraries safe path check

- commands/sql/sql.drush.inc
- includes/sitealias.inc
* Fix sqlite support. Reported in #1336. Broke with 8027687a96fdebc0d71527cbc8702e3dad5bc0ea
* Add support for absolute urls. We did never supported it before: parse_url() is unable to parse them.
* Prevent drush_sql_get_class() from trying to load a class if db_spec is not valid ("Unable to load class Drupal\Driver\Database\\Drush")
> Bring back sqlite support

- lib/Drush/Boot/DrupalBoot.php
This change fixes the search path discovery for top-level drush/ directories for 7.x branch. It is intended to resolve issue https://github.com/drush-ops/drush/issues/1546
```php
$searchpath[] = $drupal_root . '../drush';
```
Translates to path/to/drupal/docroot../drush instead of path/to/drupal/docroot/../drush. This breaks inclusion of drush configuration and commands and aliases within a top-level drupal/drush folder.
The workaround is to use sites/all/drush. However, many users might not want to put custom commands and drush configurations in a web-servable location such as sites/all/drush -- especially custom commands and code. It's far safer to keep these commands and code outside of the server-executable context.
So the small fix is:
```php
$searchpath[] = $drupal_root . …
```
> Fix search path handling for top-level drush/ directory 7.x

- commands/core/cli.drush.inc
This is just getting ready for when https://www.drupal.org/node/2536560 is committed into 8.0.x . Once that is in, this will work, then we have a tiny patch that will actually fix the problem consistently by registering that handler in drush php : https://www.drupal.org/node/2550641 .
So we need to hold off until the first issue in done at least.
> Register the runtime assertion handler for PsySH

- includes/bootstrap.inc
- includes/environment.inc
Allow potential Drush-compatible systems to put their bootstrap class hooks at __ROOT__/drush/bootstrap.
For backdrop/backdrop-issues#47
> Add a path for commandfiles that is loaded during locate_root

- commands/make/make.utilities.inc
- tests/makeTest.php
- tests/makefiles/no-core.make
- tests/makefiles/no-core.make.yml
- On large files, preg_match_all can segfault. To avoid this, test for
YAML first.
> Issue #1249: Test for YAML first to avoid segfault.

- commands/make/make.utilities.inc
- tests/makeTest.php
- tests/makefiles/no-core.make
- tests/makefiles/no-core.make.yml
Backport for issue #1249: Test for YAML first to avoid segfault.
> Backport of YAML parsing re-ordering

- docs/usage.md
> Missing `=` in the example.

- docs/install.md
The suggested composer command for `One Drush per Project` is the same as `One Drush for all Projects`. I think the intended command omits the `global` option. If that's correct, we could also use a note on how to path the `drush` command to your local instance.
> Remove `global` option in composer command for docs on `One Drush per Project`

- includes/output.inc
Drupal 8 may remove processing of !var substitutions. These are used all over Drush and also in Drush contrib modules; better to pre-process our strings before variable substitutions are removed for us by D8.
> #1637: Replace !var substitutions before calling D8 translate()

- drush.api.php
- examples/example.aliases.drushrc.php
- includes/backend.inc
- includes/environment.inc
- includes/sitealias.inc
Also fixes a problem in drush_sitealias_is_remote_site(), which did not accept alias records, even though some callers used it as if it did.
With this change, users will have to implement an alias alter hook if they want "remote" aliases to act like local aliases when used on the system they point at.  Drush cannot really know the right way to test for local for every system, so it is best to not try, save for completely unambiguous options such as 'localhost' and '.local'.  This PR also eliminates the inconsistently-used "#check-local" item in site aliases -- an earlier, failed attempt to fix this problem.
> Make drush_is_local_host() only match unambiguously local hostnames.

- composer.json
Since #1595 we rely on pcntl_exec(). Some php binaries are not compiled with it (ex https://github.com/docker-library/php). Adding an explicit dependency in composer.json helps identifying the problem.
> Require ext-pcntl in composer.json

- docs/install.md
The docs currently states...
> When you run Drush, it will notice that you have a site-local Drush with the site you have selected, and will use that one instead.
That tripped a couple of us up over at Isovera as we did not realize we needed our global version of drush to be drush 8 in order for this to work. This pull request changes that sentence to...
>  When you run globally installed Drush 8.x.x, it will search for a project level drush install from the context of your current directory, and if found it will use that one instead.
I hope this rewording clarifies this for folks coming across this in the future.
> Clarify that drush 8.x.x is needed for project level drush resolution

- commands/core/drupal/update.inc
- Resolves #1602
- See https://www.drupal.org/node/2538108
> Support hook_post_update_X().

- includes/startup.inc
This will handle the various flavors of root that `dirname()` on Windows gives us (eg: c:\, d:\, / or \)
> Prevent endless loop on Windows.

- includes/startup.inc
Don't confuse arbitrary 'drush' scripts located above the pwd for a site-local Drush; require an 'index.php' before changing the cwd to an arbitrary location.
> Do not chdir in Drush Finder unless really at a Drupal root.

- includes/environment.inc
drush_build_drush_command() should not decide to use a local drush finder script; it is the responsibility of backend.inc (drush_backend_invoke_concurrent(), to be specific) to make that determination.
> #1671: drush_build_drush_command() should never replace DRUSH_COMMAND

- includes/startup.inc
I accidentally created a drush file (without execution permissions) at the root of the project, and without knowing, the drush execution was broken.
Drush was giving me this error:
```
PHP Warning:  pcntl_exec(): Error has occurred: (errno 13) Permission denied in /usr/local/share/drush/includes/startup.inc on line 294
```
Took me a while to understand that the permission denied was related to the drush script execution found in the root of the project.
Maybe something more described could help:
```
PHP Warning:  pcntl_exec(): Error has occurred: (errno 13) Permission denied in /usr/local/share/drush/includes/startup.inc on line 294
Error has occurred executing the Drush script found at /home/vagrant/project/builds/20151016-134102/drush
(errno 13) Permission denied
```
Looks a little …
> Detailed error message when pcntl_exec() fails 

- tests/pmUpdateCodeTest.php
Hopefully catches errors in updatecode with new drupal releases.
> Always update from the previous release to the current release

- includes/drush.inc
- includes/preflight.inc
- includes/sitealias.inc
- includes/startup.inc
The Drush finder (and before it, the Drush wrapper, for those who used it) broke the site-set command, because the parent process ID for the Drush application is no longer set to the shell that called Drush.
This PR passes in the shell PID from the Drush Finder, so that it is available when needed.
> Pass shell ppid from Drush finder 

- includes/environment.inc
This fixes a bug from https://github.com/drush-ops/drush/commit/5fd73516d9d09c856fb4c70748bc0ca5dcd5ea54 / PR #1618 .
`drush_is_local_host()` added a test for the hostname ending in .local - but <a href="https://en.wikipedia.org/wiki/Multicast_DNS">.local is used for mDNS</a> and means machines on the local network, not the localhost itself. This breaks vagrant machines using mDNS for automatic publishing of records, but would also break using .local addresses for physical machines as well.
> Fix '.local' being assumed as localhost

- commands/core/archive.drush.inc
- commands/core/browse.drush.inc
- commands/core/core.drush.inc
- commands/core/outputformat.drush.inc
- commands/core/site_install.drush.inc
- commands/core/ssh.drush.inc
- commands/runserver/runserver.drush.inc
- commands/user/user.drush.inc
- includes/context.inc
This PR supports --no- options as an alternate for =0 (e.g. --no-browser inste…ad of --browser=0).
I noticed that since forever ago (Drush 5, or whenever it was), Drush had a provision for --no options.  The function drush_append_negation_options() ensures that --no-foo does not raise an error if there is any command option --foo.  However, despite this assurance, nothing in Drush ever allowed these options to actually work.
This PR introduces a minor enhancement that does just that.  If this looks acceptable, I could update the documentation for options where --no makes sense.
> Just say "--no"

- includes/drush.inc
Because dt() function have only 2 arguments, third argument ($options) is redundant. That's why drush_format_size() second argument langcode also redundant (used only to pass to dt() which is useless).
> Fix langcode usage

- includes/output.inc
> Issue #1742: Fix array_flip error in find_legacy_dt_args() function when the dt() function was chained many times

- commands/core/init.drush.inc
- includes/command.inc
- tests/Unish/CommandUnishTestCase.php
- tests/initCommandTest.php
A number of cli tools provide an 'init' command to help set up the tool's configuration files after installation.  This PR adds a basic init command to do the same thing for Drush.
There is more we could potentially do here, but this is a start.  It ensures that `drush` is in the global $PATH, and also sets up our example Bash configuration file, so that completion works, and various bash aliases and functions are offered.  Currently, this is done by modifying .bashrc, but we have the opportunity to add heuristics to find the best file for the platform here. I have heard anecdotally that .bash_profile is better for the Macintosh, but my recent experiments on Yosemite show that only .bashrc is sourced for newly-created accounts, so it seems to me that .bashrc is best for Mac and probably …
> Add a 'core-init' aka 'init' command.

- commands/core/drupal/cache_8.inc
For example dynamic page cache uses a separate bin and currently, drush cc render doesn't invalidate that.
Additionally, using the cache tag can also invalidate varnish/fastly if the site is using such an integration.
> Invalidate rendered cache tag instead of render bin

- commands/core/cli.drush.inc
- commands/core/druplicon.drush.inc
- lib/Drush/Psysh/DrushCommand.php
- lib/Drush/Psysh/DrushHelpCommand.php
- lib/Drush/Psysh/Shell.php
Modified version of the commands from https://github.com/grota/drush-psysh
This needed a bit of work to get working properly with drush, I guess just the newer version.
The help command needed a couple of fixes but mainly the DrushCommand execution needed some work to run correctly. This initial attempt is working pretty well though!
Based on discussion in https://github.com/drush-ops/drush/issues/1754
- ~~After running a command, you need to use the psysh `exit` command twice to exit the shell session~~
- ~~Can we stop drush printing the output? I would prefer to pass it to the output object (@todo in the code)~~
- ~~Doesn't have support for site aliases yet (command aliases are fine), could be some sort of follow up?~~
> Add a modified version of drush-psysh commands

- includes/drush.inc
Issue #1667: Allows passing the result of dt() on Drupal 8 to drush_set_error().
> Allow drush_set_error() to handle TranslatableMarkup.

- composer.lock
This is a small follow up hotfix release for a bug with finding the psysh command files, should be pretty minor, and safe.
> Update psy/psysh dependency to 0.6.1

- commands/core/cli.drush.inc
- lib/Drush/Psysh/DrushCommand.php
I was testing out something for one of the PsySH PRs and we have a problem with aliases. There is a high chance one of them could conflict with a PHP keyword. E.g. `if` is an alias of `image-flush` this means we can't eval any php code starting with if :)
Maybe we should check commands too to be safe?
Needs a bit of tidy, just trying to post ASAP before my laptop dies (on 2% atm).
> Filter command aliases for PHP keywords

- commands/core/cli.drush.inc
we can add a few casters to make inspecting some objects a bit nicer. As almost everything is now a protected property, you would have to `dump -a $object` to see everything. So save doing that all the time we can add some casters, these will show properties of entities, config entities, config objects (for now).
So instead of not much:
We can have properties shown by default like this:
> Add VarDumper casters for Entity and Config classes to the shell

- lib/Drush/UpdateService/Project.php
Lots of projects with Drupal 8 releases don't have a recommended_major release yet. This visibilize an old bug in Drush.
> Prevent warnings when projects don't have recommended_major release

- commands/core/cli.drush.inc
See comment for explanation. This is not ideal but it does work, not sure there is a better way at the moment to be honest. This will actually run terminate() twice, but because we already have the subscriber instances created before the shell is run, when the shell exits they still work.
> Run terminate before the shell runs to avoid database errors when the core-cli command finishes

- commands/core/drupal/environment.inc
- commands/core/drupal/environment_6.inc
- commands/core/drupal/environment_7.inc
- commands/pm/pm.drush.inc
- lib/Drush/Drupal/ExtensionDiscovery.php
- lib/Drush/UpdateService/Project.php
- tests/pmEnDisUnListInfoTest.php
- tests/pmReleaseNotesTest.php
1. Test cache was cleared/rebuild for D8 also
2. Don't skip the full test! just avoid doing concrete tests
3. Test pm-enable's resolve-dependencies for D6,7,8 (it was doing it only for D7). Expected to fail in D8 because of #5
4. Add a new test to resolve-dependencies with projects namespace. Expected to fail for D7 because of #1731
* #1731
* rln command. Due to changes in d.o html.
* #5
> Update pm-enable tests and fix underlying issues with --resolve-dependencies

- commands/core/cli.drush.inc
- examples/example.drushrc.php
The shell history is currently using the PsySH global history. So we get regular psysh and any Drupal sites/versions you are using in the same history. This gets slightly annoying when switching between them.
Let's set the history file path ourselves, and allow this to be per site or per Drupal version! The default will be per site, with an option, `version-history` which can be used to use drupal version specific history instead.
I added an example in the `example.drushrc.php` file as this is a good one for command specific defaults.
It also prints out the history file path when verbose is enabled.
```
★ tree ~/.drush/cli/
$HOME/.drush/cli/
├── drupal-7
├── drupal-8
├── drupal-site-7a914924f49f52862af4fdc8b1813f52
├── drupal-site-7df5e3082987556585d903657b4cdeec
└── …
```
> Allow site and Drupal version specific CLI history

- docs/bastion.md
I noticed this spelling error with "configuration" in the docs. The spelling for it was "configuratin".
> Corrected Spelling Error Bastion.md

- lib/Drush/Boot/DrupalBoot8.php
- lib/Drush/Log/DrushLog.php
Call through to the core Drush logger.
Once we are using a service container, we can set up these relationships with a yml loader and get rid of the global.
Let's see if these tests pass, though.
> Convert DrushLog class into an AbstractLogger adapter

- commands/pm/release_info/updatexml.inc
- includes/environment.inc
- tests/pmReleaseNotesTest.php
This will make the installation of the Drush 6.x branch dependent on GitHub rather than Pear.  This will hopefully be an improvement.
Note that the oldest version of the Console Table available on GitHub is 1.1.5, so I used that. Previously, we were using 1.1.3.
> Fixes #1827: Download Console_Table from GitHub rather than Pear.

- includes/drush.inc
fix for "Exception 'ReflectionException' with message 'Class Drush\Sql\Sql7 does not have a constructor, so you cannot pass any constructor arguments"
> Fix for PHP 5.3.3.

- commands/pm/pm.drush.inc
- tests/makeTest.php
See #1190 for original issue description. In #1190, we fixed the datestamp for traditional .info files. This PR ports that fix to work with .info.yml files as well.
> Fix datestamp to time of last commit (.info.yml files).

- commands/core/site_install.drush.inc
site-install local option --config conflict with existing Drush global --config option. Rename the new site-install option to --config-dir.
I am not too partial to one name over another, as long as it is free from conflict.
> Suggested fix for #1875: rename --config to --config-dir

- tests/makeTest.php
Does not seem to be happening on Travis, but let's see if this at least does no harm. Just creating this to force the tests to run.
> Strange problem with double-include of make.utilities.inc

- examples/example.drushrc.php
- includes/drush.inc
- includes/environment.inc
- includes/output.inc
Fixed handling of recoverable fatal errors in the same way as Drupal do.
- Error will be logged as an error instead of a notice.
- Execution of the script will be stopped.
> Log recoverable an fatal error an stop the execution of the script.

- includes/preflight.inc
- includes/sitealias.inc
Add an automatic un-set on errors, so that users do not get stuck if a site-local alias is set, and later cannot be found (e.g. if the user cd's out of the site root.
This is my preferred solution to #1532.
> Treat site-set aliases the same way that cli-specified aliases are handled.

- commands/sql/sql.drush.inc
When using Fish `drush sql-connect` doesn't work because Fish doesn't support command substitution as the command itself.
@see
https://github.com/fish-shell/fish-shell/issues/2669#issuecomment-171494288
> Update sql-connect to include Fish example.

- commands/core/core.drush.inc
It will always be correctly reported by php_ini_loaded_file(). We therefore should not search for php.ini in 'drush status', as this will only serve to produce duplicate files.
> There can only be one php.ini file

- commands/core/config.drush.inc
- commands/core/core.drush.inc
- commands/core/rsync.core.inc
- commands/sql/sqlsync.drush.inc
- includes/sitealias.inc
- tests/siteAliasTest.php
An oft-requested feature. Handy for migrations.
> Allow drush rsync to operate on two remote aliases.

- includes/sitealias.inc
with https://github.com/drush-ops/drush/pull/1937 we introduced a typo:
`drush_sitealiase_get_record` is called `drush_sitealias_get_record` :)
> drush_sitealiase_get_record does not exist

- commands/core/usage.drush.inc
- includes/command.inc
Fixes a recent failure in \Unish\sqlSyncTest::testLocalSqlSync not seeing the sub-option --sanitize-email
> Fix drush_redispatch_get_options() to pass along sub-options

- includes/command.inc
- includes/sitealias.inc
- tests/Unish/UnishTestCase.php
- tests/siteAliasTest.php
- tests/sqlSyncTest.php
Allow cli overrides in drush_redispatch_get_options() and in @self. This replaces the PR #1924.
> --Uri on CLI overrides alias. Fixes #1883.

- includes/command.inc
with https://github.com/drush-ops/drush/pull/1952 we changed the behavior of `drush_redispatch_get_options()` which ends up in the function having array function errors when there are no arguments at all.
I saw it failing then on `drush cpull` but there are probably also other places.
the full error:
```
drupal8@drupalhostingdev1:~/public_html (dev)$ drush cpull @dev default
array_diff_key(): Argument #1 is not an array command.inc:729                                       
PHP Fatal error:  Unsupported operand types in /opt/drush/master/vendor/drush/drush/commands/core/config.drush.inc on line 782
Fatal error: Unsupported operand types in /opt/drush/master/vendor/drush/drush/commands/core/config.drush.inc on line 782
Drush command terminated abnormally due to an unrecoverable error. …
```
> Fatal error when calling drush cpull with no additional arguments

- includes/bootstrap.inc
- includes/environment.inc
- lib/Drush/Boot/DrupalBoot.php
If a drupal command has bootstrap level DRUSH_BOOTSTRAP_MAX, there is no indication of this in the debug log. Nothing says that drush is calling drush_bootstrap_max() or when it tries/fails to boot reach a higher boot level.
So e.g. if drush_bootstrap_max() is trying and failing to boot to the database level, it's not telling you that. All you see is that a certain drush command is booting at bootstrap_drupal_configuration() level. This can confuse people like me who
- encounter a ContainerNotInitializedException, like the one in https://github.com/drush-ops/drush/pull/1753
- stupidly forget to specify a --uri option in an environment where this is needed for anything to work... and then spend hours debugging unneccessary things.
(And with Drupal 8 still being new, I guess there is a …
> Bootstrap & db credentials logging (+ comment cleanup)

- lib/Drush/Boot/DrupalBoot8.php
Apparently, some folks use Drupal 8 with a Symfony front-controller.  Not sure why, but autoload.php is a file that definitely must exist in Drupal 8, so this will do as well as index.php for our purposes.
Seems legitimate to me, anyway; let's see what the tests say.
> Fixes #1895: Check for autoload.php rather than index.php 

- includes/preflight.inc
- includes/sitealias.inc
- lib/Drush/Log/LogLevel.php
- lib/Drush/Log/Logger.php
Messages logged at this level are only displayed when --debug and --verbose are used together.
--verbose:  Prints verbose log messages (e.g. 'notice'), but not debug.
--debug:  Prints verbose AND debug log messages (e.g. 'notice' and 'debug'), but does not print LogLevel::DEBUG_NOTIFY messages.
--debug --verbose:  Like --debug, but also prints new LogLevel::DEBUG_NOTIFY messages.
With this PR, only 'preflight' and the site-alias 'Scanning into' messages are moved to LogLevel::DEBUG_NOTIFY. Even with this small change, I like --debug output much better, as a lot of noise that is usually not interesting is removed.
We will have a minimal impact of occasionally having to ask folks to run with `-dv` for extra debugging info, but this should be very rare. It's unlikely that we'll ever need the …
> Add a new log level, DEBUG_NOTIFY. 

- commands/core/core.drush.inc
Related to #1845 -- make it easier to diagnose the situation where a settings.php file is missing.
> Add the Drupal Settings File path to the output of Drush status

- commands/core/config.drush.inc
this fixes drush-ops/drush/issues/1971
loading drush_config_get_object within drush_config_get_value allows us to work with include-overridden
proof:
```
$ drush cget system.site
uuid: 772b5957-0cfb-4660-933b-59a1c55a9416
name: 'Site-Install Change7'
mail: admin@example.com
slogan: ''
page:
403: ''
404: ''
front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
$ drush cget system.site --include-overridden
uuid: 772b5957-0cfb-4660-933b-59a1c55a9416
name: 'overwritten sitename'
mail: admin@example.com
slogan: ''
page:
403: asdf
404: ''
front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
default_config_hash: …
```
> fixing drush-ops/drush/issues/1971

- commands/core/search.drush.inc
> Fix #1978, print indexing output safely in D7/D8

- includes/sitealias.inc
- tests/siteAliasTest.php
Roll back part of #1883 / 70752cf: breaks remote aliases that do not set 'root'.
I did one simple test with --uri on the commandline, and found it was still overriding the 'uri' element set in the alias record.  Might need more testing, to insure that my fix does not break something else.  First step: see how the travis tests fare.
> --uri override fix broke Pantheon aliases.

- includes/backend.inc
The return value of `drush_backend_parse_output` is not guaranteed to be an array, in such cases, the assignment `$values['site'] = $site;` fails with an `Illegal string offset` error.
> Perform assignment after validating the return value

- commands/core/core.drush.inc
... and fix site selection when calling rs.
Works great locally; checking tests.
> Make --use-existing the default in qd

- composer.json
- composer.lock
Version of ```symfony/var-dumper``` is increased, because at now I receive conflict with ```psy/psysh``` package, [they use](https://packagist.org/packages/psy/psysh#v0.6.0) ```symfony/var-dumper``` version ```~2.7|~3.0```.
Also for symfony/yaml I made version more flexible.
This PR can solve the next problems:
Use case 1:
We already have application with Symfony components and we try to add drush like dependency into our application.
In this case we receive conflict when our symfony yaml or var-dumper component ```>= 2.8``` or ```< 2.7```.
Use case 2:
Some dependency package increase they version of any symfony component. For example ```psy/psysh:0.7``` start using version ```2.8``` of yaml.
In this case we never receive version ```0.7``` of ```psy/psysh```, because we have hard …
> Flexible versions for Symfony components

- includes/environment.inc
…  and give a better error message to help folks who encounter this in other contexts.
For original motivation on changing the defaults for recoverable errors in Drush, see: https://github.com/drush-ops/drush/pull/1465
This change is not necessarily helpful for folks running very old code that is unlikely to be fixed, hence the relaxed handling for Drupal 6.  For an example of this, see the question [module error in drush](http://drupal.stackexchange.com/questions/192058/module-error-in-drush/192063) on Drupal Stack Exchange.
> Turn of --halt-on-error automatically for Drupal 6

- lib/Drush/UpdateService/Project.php
- tests/makeTest.php
Fixes #2024
This PR addresses a long standing issue with projects with no recommended major version. This has resurged recently when drupal.org marked all 6.x branches of projects as unsupported, and removed the supported and recommended branches settings.
> Pick the most recent release when there's no recommended major

- commands/core/drupal/batch.inc
Attempts to fix #1930, based on #1465. Untested.
> Tolerate recoverable errors in batch operation callbacks

- tests/commandTest.php
- tests/pmDownloadTest.php
- tests/pmEnDisUnListInfoTest.php
Test to see if these are even necessary.
This reverts commit 37081e6ec9a7a61c79935a77799b01bd092440f1.
> Revert "Add workarounds to pm-download / pm-enable tests for Drupal 6"

- commands/core/cli.drush.inc
- lib/Drush/Psysh/Caster.php
Quick attempt for a container caster. This is not ideal, as we have to get every service... Better than nothing, and probably better than just showing the service IDs.
If you just want the service IDs you can run the devel `devel-container-services` (dcs) command.
> Add a caster for the container

- includes/filesystem.inc
> Exclude node_modules and bower_components from directory scans

- commands/core/config.drush.inc
- tests/configTest.php
It duplicates config-import --partial, and is buggy. A fix for --partial is coming in #2069
> Remove --file option form config-edit

- commands/core/config.drush.inc
- tests/configTest.php
Use ConfigImport for imports with --partial, just like the full imports already use. Similarly, use same codepath to do the import at end of config-edit.
> Fix #2069. config-import --partial works at too low a level.

- includes/backend.inc
It was comparing a site record's 'root' entry (e.g. /path/to/drupal) to
drush_get_context('DRUSH_DRUPAL_SITE_ROOT) (e.g. sites/default) instead of
drush_get_context('DRUSH_DRUPAL_ROOT'), This fixes that and detects whether we
are dispatching to a different multi-site in the same Drupal root using the
site record's 'uri' entry and drush_get_context('DRUSH_SELECTED_URI')
I found this when trying to debug a problem with my update path (i.e. `drush updb`) with Xdebug. I was never hitting the breakpoint in the update function because Drush was dispatching to the "other" site using the drush.launcher, which does not work with Xdebug. With this fix Drush calls out to `php /path/to/drush/drush.php` directly, so that Xdebug starts working.
> Fix drush_backend_invoke_concurrent() thinks @self is a different site

- commands/core/rsync.core.inc
Modification to correct comments and append the basename of the source path to the intermediate directory only when the source is a specific file or directory.
> PR: rsync between two remote directories fails

- composer.json
The [`classmap` parameter](https://getcomposer.org/doc/04-schema.md#classmap) in `composer.json` is used to enable autoloading files that have PHP classes in them. [`lib/Drush.php`](https://github.com/drush-ops/drush/blob/master/lib/Drush.php) is such an example. Move from "files" to "classmap" to have it autoload the class properly.
Uploaded a [similar issue to Drupal.org](https://www.drupal.org/node/2703487).
> Use "classmap" for Composer autoloading of Drush.php

- commands/core/locale.d8.drush.inc
Currently each project returned from `locale_translation_get_status()` results in a new entry in `$langcodes`.  When `$langcodes` is used to determine the batch operations, an operation is added for each module and each duplicate value in `$langcodes`.  For 11 translatable modules and one language on a site this means over 300 mostly duplicate operations instead of the 33 required.
> Prevent locale-update from executing same operation multiple times

- .travis.yml
- composer.json
- composer.lock
- lib/Drush/UpdateService/Project.php
- lib/Drush/UpdateService/ReleaseInfo.php
- tests/coreTest.php
- tests/pmUpdateCodeTest.php
Now that Drupal 6 has reached EOL, **all** contrib modules on drupal.org have been marked as unsupported. We will therefore loosen up, and allow for unprompted download of the best release for all contrib modules.
> Fix tests for Drupal 6

- docs/install.md
The install commands only work on systems where `wget` is already installed and available. 
By using PHP to download the `drush.phar` code file instead, we ensure compatibility with any system shell that meets the minimum requirements to use Drush.
We can further simplify the install by saving Drush using the file name `drush`, minus the `.phar` extension. This is the command name that people expect and will use.
> Remove wget dependency from Drush install docs

- commands/core/queue.drush.inc
- tests/queueTest.php
Working on something at the moment where we want to remove all items in the queue on some deployments, as items are easy to regenerate. I think it makes sense for drush to have this functionality too. Seems pretty useful to me.
> Add a queue-delete command

- lib/Drush/Sql/SqlBase.php
When running `drush sqlsan --db-prefix="xxx"` there was an issue with namespacing that caused the following error.
`Fatal error: Class 'Drush\Sql\Database' not found in /Users/tactica_david/.composer/vendor/drush/drush/lib/Drush/Sql/SqlBase.php on line 203`
> Fix fatal error when using --db-prefix

- docs/bootstrap.md
I was shortly confused that a views data export was done as anonymous via drush ...  https://www.drupal.org/node/1975608
This doc update would have saved me from looking up the drush_get_option call ;)
> Mention --user defaults to 0

- docs/install-alternative.md
Just a small fix for a typo I noticed when reading the documentation.
> Fix for typo in install-alternative.md

- includes/drush.inc
For the master branch, we could just take out the compatibility layer, and force folks to add a PSR-3 logger.  Let's keep this for a little while, though.
> Maintain compatibility with Drush extensions that use DRUSH_LOG_CALLBACK

- commands/core/cli.drush.inc
- lib/Drush/Psysh/Caster.php
I'm bored of casting `MarkupInterface` objects (like `TranslatableMarkup`) to a string every time... Let's add a caster for it!
> Add a caster for MarkupInterface

- docs/make.md
The makefile included from a git repo example is incorrect and doesn't work.
Simple issue, simple fix.
> Fix issue with included makefile on git repo.

- lib/Drush/Queue/Queue8.php
- tests/queueTest.php
- tests/resources/modules/d8/woot/src/Plugin/QueueWorker/WootRequeueException.php
- tests/resources/requeue_script.php
Drupal 8 added the [RequeueException](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Queue!RequeueException.php/class/RequeueException/8.2.x) to allow workers to mark an item to be re-queued.
[Core's Cron.php handles it](http://cgit.drupalcode.org/drupal/tree/core/lib/Drupal/Core/Cron.php#n168), but Drush's queue processor doesn't. This pull request fixes it.
> Handle RequeueException in queue workers

- lib/Drush/Sql/Sqlpgsql.php
When calling `psql.exe` under Windows, the value of the extra `--field-separator` command-line argument is quoted incorrectly (single quotes are used). The command interpreter of windows (cmd.exe) doesn't accept this type of quoting and thus this results in hangs during the execution of various drush commands (e.g. `drush cc all`).
The patch changes the single quotes to double quotes that should be interpreted correctly under windows-based and non-windows-based systems.
> Change single quotes to double quotes in field-separator extra parameter for psql command-line queries

- commands/sql/sql.drush.inc
With the `$major_version` variable defined within [the TRUE check for password sanitization](https://github.com/drush-ops/drush/pull/2251/commits/3cc07768b7d3a81ff7425706350fe7d2b363c8da#diff-31ada6b624724696f3cbb93fb59fdde8L629), `sqlsan --sanitize-password=no` on Drupal 8 is unable to determine the proper user table to UPDATE and the command will fail with `[error] Sanitize query failed.`
This 2-line PR simply moves the `$major_version` variable to [the top of the function](https://github.com/drush-ops/drush/pull/2251/commits/3cc07768b7d3a81ff7425706350fe7d2b363c8da#diff-31ada6b624724696f3cbb93fb59fdde8R622) so that even when passwords are not sanitized, the correct user table can be determined and the query will succeed.
> 'Sanitize query failed' with 'sqlsan --sanitize-password=no' on D8

- lib/Drush/Drupal/DrupalKernel.php
`\Drush\Drupal\DrupalKernel::createFromRequest()` seems broken  #after https://www.drupal.org/node/2631362. Fixed it here.
> Fixed method signature in DrupalKernel.

- commands/xh.drush.inc
- tests/xhUnitTest.php
The function `xhprof_enable()` takes flags to control the profiling of CPU, memory, and PHP built-ins. This change would add a drush sub-option for each of the flags.
Related to how sub-options appear to work currently, see #2173.
> Adds sub-options for xhprof_enable() flags.

- lib/Drush/Drupal/DrupalKernel.php
As stated in the pull request #2202 
We should pass the $app_root to bootEnvironment().
> add $app_root to bootEnvironment

- lib/Drush/Boot/DrupalBoot8.php
This is a follow-up to #2202 (and #2280)
Seems innocent enough, but I'm not very knowledgeable about the Drush boot process, so could use some eyes.
Note that passing the `$app_root` explicitly is considered a best practice. It's only optional for backwards-compatibility.
> Pass the $app_root to the kernel during boot

- commands/core/drupal/environment.inc
Raised from this issue https://www.drupal.org/node/2771855.
drush_get_modules() doesn't check a value of hidden property.
> Fix condition for hidden modules

- includes/filesystem.inc
- includes/preflight.inc
And thereby fix drush_is_nested_directory() and drush_preflight_command_dispatch() on Windows.
Progress on #1674
> Use DIRECTORY_SEPARATOR

- commands/pm/download.pm.inc
At the moment when you download a theme engine, e.g. "drush dl tfd7-7.x-3.0-beta2", it ends up in /public/themes/engines. But the sensible default place for theme engines from "contrib" is 
/public/sites/all/themes/engines.
> download theme engines into the sensible default destination

- composer.json
- composer.lock
- docs/install-alternative.md
- includes/environment.inc
- includes/exec.inc
- includes/filesystem.inc
- includes/preflight.inc
- includes/startup.inc
- lib/Drush/Boot/DrupalBoot.php
Run drush.php directly instead of drush.launcher when using Windows.
> Skip the launcher when using Windows.

- examples/sync_enable.drush.inc
It's often handy to apply database updates before enabling modules.
> Add updb option to sync_enable example.

- lib/Drush/Queue/Queue8.php
- tests/queueTest.php
- tests/resources/modules/d8/woot/src/Plugin/QueueWorker/WootRequeueException.php
- tests/resources/requeue_script.php
At https://github.com/drush-ops/drush/pull/2264 we added support for RequeueException in `master` branch. This PR backports that pull request for `8.x`.
> Handle requeue exception in 8.x

- drush
- tests/makeTest.php
- tests/makefiles/bz2-singlefile.make
- tests/makefiles/file-extract.make
The drush script (which is now drush.laundher in Drush 8 or later) uses PHP_MIN_VERSION to determine if the php release is PHP 5.3. This causes the test to spuriously pass on PHP 7. Adding the extra -d options is innocuous, but noisy.
Running php -r has a bad side-effect on Pantheon, though, which doesn't like it if you run php without the php options we've told Drush to use. This recently became an actual operational problem with some APC changes we made; breaks Kalabox when running Drupal 7 + Drush 7 + PHP 7.
This PR fixes all of these problems.
> Fix PHP 5.3 test on PHP 7 in Drush 7 startup script

- commands/make/make.drush.inc
- tests/makeConvertTest.php
- tests/makefiles/composer.json
- tests/makefiles/composer.lock
- tests/makefiles/patches.make.yml
This functionality is present in Drush 9.x, but not in Drush 8.x. It'd be really useful to have it here, so this PR backports (actually just copy-and-pastes) it back into the 8.x branch.
> Backport Composer support into make-convert command

- commands/make/generate.make.inc
This patch modifies the output of generate-makefile so that the key matches that sought when reading a drush makefile.
Signed-off-by: Nigel Cunningham <nigel@salsadigital.com.au>
> Fix yaml makefile generation - reading looks for patch, not patches.

- commands/core/site_install.drush.inc
Typo in `config-set` invocation.
> Fixed site-install --config-dir option

- commands/make/make.drush.inc
Related to https://www.drupal.org/node/2699121
> Fix composer branch-alias constraint

- lib/Drush/Boot/DrupalBoot7.php
We run drush cron every 10 minutes on a site and we saw a lot of cache clearing on every cron run. The problem was that the cache entry for system_cache_tables was gone after each drush invocation.
Traced that back to drush bootstrap where the module_implements() cache is reset. Drush should never do that when a random drush command is executed. We can inject the logging into the static module implements cache instead.
> fix(bootstrap): Do not clear the module_implements() cache on a drush invocation

- includes/preflight.inc
- lib/Drush/CommandFiles/DrushCommands.php
- lib/Drush/CommandFiles/ExampleCommandsFile.php
- lib/Drush/CommandFiles/core/BrowseCommands.php
- lib/Drush/CommandFiles/core/DrupliconCommands.php
- lib/Drush/CommandFiles/core/ViewsCommands.php
> Add a base class called DrushCommands

- commands/core/drupal/cache_8.inc
To rebuild the route tables the [RouteBuilder service](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Routing!RouteBuilder.php/class/RouteBuilder/8.2.x) needs to run the [`rebuild`](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Routing%21RouteBuilder.php/function/RouteBuilder%3A%3Arebuild/8.2.x) method, but this isn't correctly flagged to execute the method during cache clear. This results in the router tables not being rebuilt correctly since the method is never run.
> Fix typo in router rebuild call

- commands/core/cache.drush.inc
To reproduce:
1. Create a menu link pointing to /user/logout in the UI
2. Run drush cr, then access the page as anonymous user. The Logout link is visible
3. Clear cache in the UI, the logout link is not visible as anonymous user.
See also https://www.drupal.org/node/2817911 and possibly other duplicate bug reports caused by this.
Interesting site note: This only behaves like this in 8.2, in 8.1 it worked fine but I think this change makes sense anyway.
There is at least another createFromGlobals() but that's only a fallback that might not actually be used anmyore.
> Use Request::create() to create the request for drush cr so that the request method is set

- commands/runserver/d8-rs-router.php
Populating the "q" query in the d8-rs-router produces failures of assertUrl()
when executing SimpleTests within 'drush rs'.
Example of failed assertion:
`
Fail 
Expected
'http://localhost:8888/search-api-test-fulltext?f%5B0%5D=ab_facet%3Aitem'
matches current URL
'http://localhost:8888/search-api-test-fulltext?q=search-api-test-fulltext&f[0]=ab_facet%3Aitem'.
`
> Do not populate the "q" query.

- includes/annotationcommand_adapter.inc
- includes/preflight.inc
- lib/Drush/Commands/DrushCommands.php
- lib/Drush/Commands/ExampleCommands.php
- lib/Drush/Commands/core/BrowseCommands.php
- lib/Drush/Commands/core/DrupliconCommands.php
- lib/Drush/Commands/core/EvalCommandFile.php
- lib/Drush/Commands/core/EvalCommands.php
- lib/Drush/Commands/core/InitCommandFile.php
- lib/Drush/Commands/core/InitCommands.php
- lib/Drush/Commands/core/ShellAliasCommands.php
- lib/Drush/Commands/core/StateCommands.php
- lib/Drush/Commands/core/ViewsCommands.php
- lib/Drush/Drupal/DrushServiceModfier.php
- tests/annotatedCommandTest.php
- tests/resources/global-includes/Commands/FoobarCommands.php
- tests/resources/modules/d6/woot/Commands/WootCommands.php
- tests/resources/modules/d7/woot/Commands/WootCommands.php
- tests/resources/modules/d8/woot/src/Commands/AnnotatedGreetCommand.php
- tests/resources/modules/d8/woot/src/Commands/GreetCommand.php
- tests/resources/modules/d8/woot/src/Commands/WootCommands.php
- tests/resources/modules/d8/woot/woot.services.yml
This allows Drush extensions with commands and hooks to be declared in global (e.g. ~/.drush) and site (e.g. __DRUPAL_ROOT__/drush) locations.
For each potential search location, the actual commandfiles may be located at `.`, `./Commands`, or `./CommandFiles`.  The namespace calculation is not necessarily correct, though.  For example, a commandfile named `ExampleCommand.php` located in ~/.drush should have a namespace of `Drush`, whereas a commandfile with the same name located in ~/.drush/Commands should have a namespace of `Drush/Commands`. This is an ambiguity, because if the file is distributed as a standalone .php file, its namespace should not have to be modified based on where the end user chooses to install it.
This is not necessarily rational.  Potential improvements:
- Only …
> Add global and site (Drupal root) locations for Drush extensions.

- lib/Drush/Log/DrushLog.php
When I run a migration with `drush migrate-drush-run` I'm getting the following error:
> Object of class Drupal\Core\Session\AccountProxy could not be converted to string in DrushLog.php
This is caused by the `user` element in the `$message_placeholders` array being an `AccountProxy` object instead of a string. This message placeholders are retrieved from the `$context` which is populated in `LoggerChannel::log()`:
```
try {
if ($this->currentUser) {
$context['user'] = $this->currentUser;  // <<< here
$context['uid'] = $this->currentUser->id();
}
}
```
Our loggers are adhering to `LoggerInterface` from [`psr/log`](https://github.com/php-fig/log). According to their [documentation](https://github.com/php-fig/log/blob/master/Psr/Log/LoggerInterface.php#L13):
> The context array can contain …
> Filter out placeholders that can not be cast to strings

- commands/core/site_install.drush.inc
The error message now helps to understand which file couldn't be copied.
> Fix error message when unable to copy example.sites.php to sites.php

- commands/core/core.drush.inc
- composer.lock
- lib/Drush/Commands/core/StatusCommands.php
- tests/configTest.php
- tests/contextTest.php
- tests/drushScriptTest.php
- tests/sqlConnectCreateTest.php
The handling of default fields is not working right.  If --fields is not specified, an error is returned. If a valid list of --fields is given, they will be printed.
> Annotated command implementation of 'core-status' command.

- commands/core/cache.drush.inc
After #2450 with PHP 7
The following error is caused by execution of `drush cr`
[warning] apcu_clear_cache() expects exactly 0 parameters, 1 given cache.drush.inc:280
> fix [warning] apcu_clear_cache() expects exactly 0 parameters, 1 given

- includes/annotationcommand_adapter.inc
- lib/Drush/Commands/core/SshCommands.php
- tests/Unish/CommandUnishTestCase.php
- tests/siteSshTest.php
The only real change here is that the optional bash at the end must be quoted to form one argument. I didn't bother trying to figure out how to preserve that. I guess I could remove the strict option handling from this command if this feature goes away. Thoughts?
> Port site-ssh command to Annotated.

- commands/core/archive.drush.inc
- commands/core/core.drush.inc
- lib/Drush/Boot/BaseBoot.php
- lib/Drush/Commands/core/CoreCommands.php
- lib/Drush/Commands/core/EditCommands.php
- tests/Unish/UnishTestCase.php
Start a port. I renamed core-config to core-edit for disambiguation. Kept old name as a command alias.
core-edit has --editor and --bg options which would benefit from https://github.com/drush-ops/drush/issues/2336#issuecomment-262568264
> Port some core.drush.inc commands to Annotated

- lib/Drush/User/UserSingle7.php
- lib/Drush/User/UserSingleBase.php
Drupal 8 supports this again since 8.1.9 or so, as part of a security improvement.
Not sure if we want some kind of version check.
> Append /login to the user password reset URL also in 8.X

- lib/Drush/Sql/Sqlmysql.php
The code incorrectly writes `Sqlmysql.inc` in the MySQL connection defaults file comment.  It should be `Sqlmysql.php`.
> change filename in mysql defaults template

- includes/annotationcommand_adapter.inc
- lib/Drush/Commands/ValidatorsCommands.php
- lib/Drush/Commands/core/ImageCommands.php
- lib/Drush/Commands/core/WatchdogCommands.php
- tests/imageTest.php
This is a start. c.f. #2524; we don't have an implementation for --no-interaction yet.  Also, we will need to throw an exception to abort from an interact hook.
Ideally, hook interact should only be used to ask the user to provide values for arguments or options not provided on the commandline. If something is queried in the interact hook, then it should be skipped if the user already provided a usable value. The image commands follow this pattern, but in the case of `watchdog-list`, the interact hook is not necessary -- the interaction could be done as part of the command, before it calls through to `watchdog-show`.  I left this as an interact hook for illustrative purposes, though.
n.b. The interact hook conforms to the interface provided by Symfony Console. If the annotated-command …
> Implement @hook interact and @hook init.

- commands/core/config.drush.inc
This should make [config_split](https://www.drupal.org/project/config_split) compatible cex/cim.
> Use config.storage.sync to instantiate the FileStorage

- lib/Drush/Queue/Queue8.php
Queue-run command is throwing errors because of faulty placeholder:
`Invalid placeholder (id) in string: Processing item @id from @name queue. FormattableMarkup.php:238`
> Fixes queue-run message placeholder

- lib/Drush/Commands/sql/SqlSyncCommands.php
Removed the validation based on #2588
> remove validation for the equalness of @source and @target in sql-sync

- lib/Drush/Commands/core/UserCommands.php
The command help for `drush uli` is broken (`drush uli -h` thinks there's a "string" option) due to what looks like an incomplete conversation to an annotated command, and one of the usage examples doesn't use the current options correctly.
> Fix uli command annotation

- commands/runserver/d8-rs-router.php
Related issue: https://www.drupal.org/node/2850280
ping @Berdir: D8 takes care of path processing right? Drush should not longer preprocess the incoming request.
> Remove query string processing from D8 rs bootstrap

- lib/Drush/Commands/config/ConfigImportCommands.php
Adds a notice for each operation during sync. Unfortunately, the notice is shown after the operation completes and the message is not easily customized. An example:
```
Collection  Config                 Operation                
core.date_format.long  update 
core.extension         update 
dblog.settings         update
Import the listed configuration changes? (y/n): y
[notice] Synchronizing extensions: install options.
[notice] Synchronizing extensions: install aggregator.
[notice] Synchronizing extensions: uninstall ban.
[notice] Synchronizing configuration: update core.date_format.long.
[notice] Synchronizing configuration: update core.extension.
[notice] Synchronizing configuration: update dblog.settings.
[notice] Finalizing configuration synchronization.
[success] The configuration …
```
> Provide progress reporting during config-import

- commands/core/drupal/environment.inc
- lib/Drush/Commands/core/CoreCommands.php
Please review new PR following the resolution suggested by @greg-1-anderson in https://github.com/drush-ops/drush/pull/1315#issuecomment-126396642
FYI I couldn't find anyway to override @default-fields so had to temporarily edit the code.  The file http://api.drush.org/api/drush/commands%21core%21outputformat%21topics%21table.html/master suggests a --fields option but that gave me  Unknown option: --fields.
I would be interested in backport to 8.x and have done and tested code changes for that too.
> Fix issue #1314: drush core-requirements does not output descriptions in render arrays

- commands/core/drupal/pm_8.inc
- commands/pm/pm.drush.inc
Currently, there is no way to uninstall modules that depend on one another because Drush checks the dependency chain for each module individually, without considering any of the other modules you are uninstalling.
It's also counterintuitive that although Drupal's core ModuleInstaller::uninstall() function automatically uninstalls dependent modules, Drush (which ultimately just uses the same function) won't let you do the same thing.
Drush should automatically uninstall depending modules, same as core. I can't imagine a scenario where the current behavior is desired. The only argument I could imagine against this is that there's a small performance hit to computing the dependency chain... but we are already incurring that hit by not passing a second parameter to …
> Issue #1854: Allow uninstall of dependent modules.

- lib/Drush/Commands/core/UpdateDBCommands.php
I don't have this problem in 8.1.9 put when I updated to dev-master locally I had
```bash
[warning] call_user_func_array() expects parameter 1 to be a valid callback, function 'update_invoke_post_update' not found or invalid function name batch.inc:232
```
all over my shell when running `drush updb` if it included any post updates. This fixes it.
Note there are a bunch of manual includes of `update.inc` in `UpdateDBCommands`, but I *think* they are all still valid as they are not related to the batch, but I am not 100% sure.
> Fix post updates cannot be run

- lib/Drush/Commands/core/SiteInstallCommands.php
This PR makes two behavior changes to the site-install command to improve its usability with Continuous Integration servers.
If the CI server creates a Drupal site that persists after the test suite runs, then it is undesirable to have the uid1 password visible in the test logs. With this PR:
- The account password is by default hidden if it is provided on the commandline. Usually, users will not need to know the password if they already explicitly specified what it should be. If a CI script stores the account password in an environment variable, then it may be passed via `drush si --account-pass=$PASS` without exposing the value in the CI logs.
- The option `--show-passwords` / `--show-passwords=0` is available to override the default.
Currently, `drush site-install …
> Adjust 'site-install' command for better use in Continuous Integration

- src/Commands/config/ConfigExportCommands.php
This is necessary to make config_split (and everything else working with config_filter) work as expected.
(also this fixes a bug)
> Compare the  to the sync directory and wipe storage smartly

- commands/core/config.drush.inc
This is the same as #2637 but for drush 8
> Clean the export directory via the config storage

- composer.json
- composer.lock
- includes/preflight.inc
- src/Cache/CommandCache.php
- src/Commands/core/CacheCommands.php
- src/Commands/core/SiteInstallCommands.php
In my testing, this seems to save about 0.02s when using Drush core commandfiles. The difference for Terminus was much greater, though, so I think it really depends on what sort of code you have in your commandfiles.
This cache code does a good job at noticing when methods are added or removed from a commandfile, so there's not much downside to using it. There could be some potential upside if some external commandfiles contain more complicated implementations that take longer to parse.
Fixed #2608.
> Use annotated-command cache.

- composer.lock
This should contain the upstream fix for https://github.com/drush-ops/drush/pull/2635
> Fixes #2635: Bump psy/psysh version to 0.8.2

- .travis.yml
- tests/resources/codebase/composer-highest.json
- unish.sut.php
Expand our test matrix to test against very modern Drupal. Builds against Drual 8.4.x are marked as 'allowed failures' in Travis in order to not perturb Drush development. The failures will be in the Travis logs for interested parties to fix.
> Test against stable Drupal and highest Drupal (8.4.x)

- commands/core/config.drush.inc
Fixes (at least partially) #2709 
If an error occurs during config import, Drupal will catch it internally and then clear the exception so that the import proceeds gracefully: http://cgit.drupalcode.org/drupal/tree/core/lib/Drupal/Core/Config/ConfigImporter.php#n762
This means that Drush can't assume that an import was successful just because an import finished without throwing an exception. It must check if any errors were reported.
> Issue #2709: Fixed non-reporting of config-import errors.

- commands/core/locale.d8.drush.inc
When `drush locale-update` is run without any new translation to import, the following output may occur. This example is based on a 8.2.x core with a site installed in french and running with drush 8.1.10:
```
Traduction de mollom vérifiée.                              [ok]
Traduction de mollom vérifiée.                              [ok]
... x10
Traduction de paragraphs vérifiée.                          [ok]
Traduction de paragraphs vérifiée.                          [ok]
Traduction de paragraphs vérifiée.                          [ok]
Traduction de paragraphs vérifiée.                          [ok]
Traduction de paragraphs vérifiée.                          [ok]
... x10 …
```
> Deduplicate the langcode to avoid a message repetition.

- commands/runserver/d7-rs-router.php
- commands/runserver/runserver.drush.inc
This is an update to the PR in #1658
I've split d8 and d7 code into separate files. The PR is against 8.x because master no longer supports Drupal 7.
> Fix image style generation for d7

- src/Drupal/Commands/core/CliCommands.php
- src/Psysh/DrushCommand.php
- src/Psysh/DrushHelpCommand.php
See https://github.com/drush-ops/drush/issues/2728
We can remove quite a bit of code that was needed before to convert the drush command config arrays into input options etc.. now we already have those object on the original commands, which is nice :)
> Update core-cli command to use new command list

- composer.json
Addresses #2603 (partially).
Note that the output from `drush list` and `drush help` are not being processed by the word wrapper at all at the moment, even with this PR. However, other table output should be wrapped much better with this version.
> Include improved-wrap PR from output-formatter project.

- src/Commands/generate/Helper/InputHandler.php
- src/Commands/generate/Helper/InputPreprocessor.php
**Problem:**
At the moment both input handler and input preprocessor rely on hardcoded mapping of DCG generator names.
https://github.com/drush-ops/drush/blob/master/src/Commands/generate/Helper/InputHandler.php#L29
https://github.com/drush-ops/drush/blob/master/src/Commands/generate/Helper/InputPreprocessor.php#L40
There are two major problem with this approach.
1. The mapping has to be synchronized with DCG. For example if DCG gets new theme generator, Drush generate may not be able to handle it automatically. Currently for all unknown generators we assume that if a generator asks for [machine name](https://github.com/drush-ops/drush/blob/master/src/Commands/generate/Helper/InputHandler.php#L56) the generated code can be stored to existing module. This is too optimistic.
2. Third party …
> Let generators define destination generated code

- includes/environment.inc
- includes/preflight.inc
- includes/sitealias.inc
- src/Boot/BootstrapManager.php
In order to write the `pm-*` compatibility commands (wrappers around Composer equivalent), we need to know where the Composer root is. DrupalFinder knows, but we don't keep it around.
This PR aims to move the DrupalFinder into the bootstrap object, so that we can ask for the composer root when we want it.
In progress.
> Remove drush_locate_root

- src/Commands/core/LoginCommands.php
Only really applies to remote execution, but this just fixes the broken variable reference.
> Fix broken reference to $name in LoginCommands

- src/Commands/generate/GenerateCommands.php
- src/Commands/generate/Generators/Drush/DrushCommandFile.php
- src/Commands/generate/Generators/Drush/drush.services.twig
- src/Commands/generate/Generators/Migrate/MigrationGenerator.php
Until now DCG treated hooks and  _services.yml_ files in special way to preserve content of original files when they exist. I've just added more general way to append new content to existing file. A file definition can have some meta information including a property called _header_size_ so the dumper is able to merge the content of the file correctly.
It caused some small API changes addressed in this PR
1. _services.yml_ file should be rendered the same way as any other files (with Twig).
2. Path to _services.yml_ file should be specified explicitly (service tags are not checked any more).
3. Generator application no longer needs Yaml dumper.
> Render Drush command file service definition with Twig template

- tests/resources/codebase/composer-highest.json
We use webflo/drupal-core-strict instead of drupal/core.
This fixes mysterious test fails per https://www.drupal.org/node/2882456
> composer-highest.json uses webflo/drupal-core-strict 

- commands/pm/pm.drush.inc
This fixes #2753 by breaking out of the loop if downloads fail.
> Fix #2753: Prevent loops when unable to download extensions

- src/Commands/generate/Generators/Drush/DrushCommandFile.php
- src/Commands/generate/Generators/Migrate/MigrationGenerator.php
- src/Commands/generate/Helper/InputPreprocessor.php
Eventually DCG Question wrapper has been removed. At the moment the only point of keeping Question wrapper is [lack of setter methods](https://github.com/symfony/symfony/issues/23147) in original class.
I've added a small trait with helper functions to set question text and default value.
Generators have to use native Symfony console questions. All three types of questions are supported (_Question_, _ConfirmationQuestion_, _ChoiceQuestion_).
Also updated MigrationGenerator and fixed a small bug with missing 'source' key in DrushCommandFile generator.
> Update drush generate according to DCG changes

- src/Commands/generate/Helper/InputPreprocessor.php
Theme generators does not have to ask for theme name. At the moment it causes a fatal error "Error: Call to a member function setAutocompleterValues() on null (`drush generate breakpoints`).
> Check if generator has 'name' question before modifying it

- src/Commands/generate/Helper/InputHandler.php
Should work the same way as for modules. The location can be either in a directory of existing theme or global _themes_ directory.
> Save theme related files to a correct destination

- commands/core/cli.drush.inc
I had noticed that launching `drush php` is often inexplicably slow, taking up to 30 seconds to launch. I've now discovered that this happens when I am on a slow mobile connection. PsySH has a feature to check for updates, and by default this checks once per week. Unfortunately since we are using a "bundled" version and generate the configuration on the fly when launching it this performs the update check every single time it is launched.
I can understand the usefulness of this feature when using PsySH standalone, but I think this version check is pretty pointless in our typical use case. PsySH is a dependency of Drush which is a dev dependency of Drupal which is a dependency of a custom web project which will typically only be updated whenever a security update is available. I don't …
> Disable the PsySH version check

- composer.json
[environment.inc](https://github.com/drush-ops/drush/blob/master/includes/environment.inc#L566) calls the getHomeDirectory method from webmozart/patch-utils Path class. That method didn't exist until the 2.1.0 release of patch-utils, but drush's composer.json file allows the 2.0.0 release.
This PR just bumps the minimum version of patch-utils to 2.1.0 while still allowing everything up to, but not including, 3.0.0.
> Update webmozart/patch-utils minim version

- includes/annotationcommand_adapter.inc
- includes/command.inc
- src/Commands/help/ListCommands.php
Thus removing some no longer needed code from annotation_adapter.inc
> Fix #2460. Use $application instead of $command in option verify

- docs/examples.md
- docs/index.md
- docs/install-alternative.md
- docs/install.md
- docs/usage.md
I think the docs for Drush 8 should reference 8.x examples. A few link are broken because Drush 9 (master) diverged from Drush 8 (8.x)
> Fix drush docs, link to 8.x docs from within the 8.x documentation

- includes/output.inc
- src/Utils/StringUtils.php
A simple refactor, for rebasing into the Symfony Dispatch PR.
> Factor out fallback dt() code into StringUtils::interpolate().

- includes/bootstrap.inc
- src/Boot/BootstrapManager.php
> Move more bootstrap code from bootstrap.inc to the bootstrap manager.

- includes/preflight.inc
- src/Boot/BootstrapManager.php
- src/Boot/DrupalBoot8.php
(but …create one if it is not). 
Move initial assignment to 'DRUSH_BOOTSTRAP_PHASE' to the bootstrap manager.
More refactoring for #2843.
> Allow the DrupalFinder to be injected into the BootstrapManager

- composer.json
- src/Commands/core/SiteCommands.php
Update to OutputFormatters 3.1.11 so that we can use ListDataFromKeys to fix site-alias --format=list.
> Fix site-alias --format=list

- lib/Drush/Sql/SqlBase.php
I ran following command with Drush 8.x:
> drush.sh sql-query --db-prefix "TRUNCATE TABLE {file_managed}"
and noticed following error message:
> Error: Class 'Database' not found in .../vendor/drush/drush/lib/Drush/Sql/SqlBase.php on line 204 ...
The commit is to fix the issue in branch 8.x. I have another pull request to address the issue for branch master.
> fix namespace for Drush command sql-query with option "--db-prefix" in use (branch 8.x)

- src/Sql/SqlBase.php
I ran following command with Drush 8.x:
> drush.sh sql-query --db-prefix "TRUNCATE TABLE {file_managed}"
and noticed following error message:
> Error: Class 'Database' not found in .../vendor/drush/drush/lib/Drush/Sql/SqlBase.php on line 204 ...
The commit is to fix the issue in branch master. I have another pull request to address the issue for branch 8.x.
> fix namespace for Drush command sql-query with option "--db-prefix" in use

- src/Drupal/Commands/core/LocaleCommands.php
Fix #2812
Drush 9.0.0-beta3
`drush locale-update`:
Error: Call to a member function get() on null in /vendor/drush/drush/src/Drupal/Commands/core/LocaleCommands.php on line 111
> Fix missing state argument

- commands/runserver/d7-rs-router.php
- commands/runserver/d8-rs-router.php
Files with spaces (and other percent encoded characters) are not served from the files directory when using `drush runserver`. This change simply decodes the REQUEST_URI path.
Same change as #2889 for the 8.x branch.
> 8.x Fix serving existing files with encoded characters like `%20`

- includes/sitealias.inc
The alias-path cache looks up a site alias for a given site path. The problem is that the discovered site aliases can vary if --local is passed, the value of environment variables like HOME, ETC_PREFIX, etc. This PR just fixes my immediate problem of --local. Listing all the discovered alias files in the cache key is impossible since it would take too long to discover them - this needs to be fast.
In general, this alias cache is problematic. I believe it is slated for removal in symfony-dispatch PR.
> More granular cache key for alias-path.

- includes/preflight.inc
Current code in preflight relies on luck and happenstance to ensure that only one of three possible 'if' branches are ever executed in drush_preflight_command_dispatch(). Unfortunately, sometimes two of these may run, resulting in double execution. Fix this by ensuring we exit the function as soon as one variant runs.
Apparently introduced in https://github.com/drush-ops/drush/pull/2865, although theoretically possible prior to then as well.
> Avoid multiple execution of remote commands

- misc/d8-rs-router.php
Files with spaces (and other percent encoded characters) are not served from the files directory when using `drush runserver`. This change simply decodes the REQUEST_URI path.
> Fix serving existing files with encoded characters like `%20`

- src/Application.php
- src/Preflight/Preflight.php
- src/Style/DrushStyle.php
1. --yes behaves like --no-interaction. The effect is that prompts just proceed with defaults. At this time we lose Drush's feature to print out the question and response even during a --yes request. --no is still not supported.
1. --debug maps to -vv. Folks wanting more should use -vvv which maps pretty well to Drush's old DEBUG_NOTIFY level.
The new code in Preflight.php could easily be moved elsewhere if anyone has thoughts on that.
> Handle --yes and --debug

- composer.lock
This got missed and never backported into the 8.x branch. It's late, yes. But worth doing anyway :) We wanted 0.8.2 originally.
https://github.com/drush-ops/drush/pull/2649
> Update Psysh to version 0.8.11

- src/Application.php
- src/Commands/DrushCommands.php
- src/Commands/core/DrupliconCommands.php
- src/Commands/core/EditCommands.php
- src/Commands/core/NotifyCommands.php
- src/Commands/core/RsyncCommands.php
- src/Commands/core/SiteCommands.php
- src/Commands/core/StatusCommands.php
- src/Commands/core/XhprofCommands.php
- src/Commands/help/HelpCommands.php
- src/Commands/help/ListCommands.php
- src/Drupal/Commands/core/CliCommands.php
- src/Drupal/Commands/core/DrupalCommands.php
- src/Preflight/Preflight.php
- src/Style/DrushStyle.php
Based on #2843. Remove `drush_get_context()` where possible, and other modernization changes.
> Symfony dispatch remove contexts

- src/Drupal/Commands/core/UserCommands.php
Minor fixes to the grammar of the `user-add-role` help texts. It currently looks like this:
```
Arguments:
role  The name of the role to add        
names A comma delimited list user names. 
```
The first help text doesn't end in a period, and the second sentence is missing a word.
> Improve grammar of `user-add-role` help text

- src/Drupal/Commands/config/ConfigCommands.php
- src/Drupal/Commands/config/ConfigExportCommands.php
- src/Drupal/Commands/config/ConfigImportCommands.php
Cleaning up the config import to fix #2939
As a side effect the temporary filders will not be in git and therefore #2855 is solved too.
> Clean up config import and export methods to fix diff #2939

- src/Application.php
- src/Boot/BaseBoot.php
- src/Boot/Boot.php
- src/Boot/BootstrapManager.php
- src/Boot/DrupalBoot.php
- src/Preflight/DependencyInjection.php
- src/Preflight/Preflight.php
- src/SiteAlias/AliasRecord.php
- src/SiteAlias/SiteAliasManager.php
If URI is not specified, and cwd is inside a site directory (something with settings.php), then use the basename of the sites directory as the URI. Also, inject alias manager into Application so that we may later run a remote command that does not necessarily exist on the local machine.
> Find uri from site directory basename

- src/SiteAlias/SiteAliasFileDiscovery.php
- src/SiteAlias/SiteAliasManager.php
Fixed error when there are no search locations, and error in storing a complex record instead of '@none' for the non-alias.
> Fix a couple of errors with alias searching.

- src/Sql/SqlOracle.php
- src/Sql/SqlSqlsrv.php
Fixes PHP 7.x warning:
> Declaration of Drush\Sql\Sqlsqlsrv::creds() should be compatible with Drush\Sql\SqlBase::creds($hide_password = true)
Ref: #2967
> Fixes declaration compability (GH-2967)

- src/Application.php
- src/Command/RemoteCommandProxy.php
- src/Drupal/Commands/pm/PmCommands.php
- src/Preflight/DependencyInjection.php
- src/Preflight/RedispatchHook.php
Create a RemoteCommandProxy class to use to stand in for unknown commands in Application::find() when the command is destined to be executed remotely.
This overcomes a limitation of Symfony Console that prevented us from running commands remotely.
> Run remote commands even if they do not exist locally

- src/Boot/DrupalBoot8.php
- src/Commands/generate/GenerateCommands.php
- src/Drupal/DrupalKernel.php
- src/Drupal/DrushServiceModifier.php
This avoids conflict with Drush 8.
- 'drush.service.consolecommands' => DrushServiceModifier::DRUSH_CONSOLE_SERVICES ('drush.console.services')
- 'drush.service.consolidationcommands' => DrushServiceModifier::DRUSH_COMMAND_SERVICES ('drush.command.services')
- 'drush.service.generators' => DrushServiceModifier::DRUSH_GENERATOR_SERVICES ('drush.generator.services')
> Rename Drush's service cache objects stored in the Drupal container

- lib/Drush/Boot/DrupalBoot8.php
Do not attempt to access the cached Drush commandfile services unless they exist in the container. This converts a crashing scenario into one where commands are merely missing. A 'drush cr' should bring back the missing commands.
Needs testing to confirm whether 'drush cr' will repair this problem once this change is in place.
> Fixes #2767: Avoid 'non-existent service' error

- .travis.yml
- composer.json
- composer.lock
- tests/Unish/UnishTestCase.php
- tests/imageTest.php
While keeping global installs at Symfony 2.
If we do not allow Symfony 3 components, then site-local installs of Drush 8.x will not work with Drupal 8.4.x. However, if we simply add Symfony 3 to the require section, then we will break global installs of Drush for Drupal 8.3.x. To prevent this, we pin Symfony components to Symfony 2 in require-dev.
c.f. https://github.com/drush-ops/drush/pull/2799
> Allow Symfony 3 components for site-local installs of Drush 8.x

- src/Drupal/Commands/config/ConfigCommands.php
- tests/configTest.php
This would allow to filter configuration items by its operation and display results using different formatters.
Related issue #1811.
> Enhance config:status command

- src/Command/RemoteCommandProxy.php
- src/Preflight/PreflightArgs.php
- src/Symfony/IndiscriminateInputDefinition.php
- src/Symfony/LessStrictArgvInput.php
The remote side will validate.
> Fixes #3025: Avoid validating args and options for remote proxy commands

- src/Drupal/Commands/config/ConfigCommands.php
"Different" state should stand for "update" operation and be displayed in yellow to match `drush cex` / `drush cim` commands.
> Fix wrong state mapping in config:status command

- src/Commands/core/SiteInstallCommands.php
> Prevent sites.php file creation on "default" installations

- src/Preflight/ArgsRemapper.php
- src/Preflight/Preflight.php
Command aliases (e.g. 'en' + 'si') should only be replaced when they appear as the first non-option / non-alias parameter on the argv list.
> Fixes #3054: Only replace command aliases for commands

- sut
- unish.sut.php
This will require rebuilding your sut.
> When creating the sut, also create aliases @sut.dev and @sut.stage.

- src/Config/ConfigLocator.php
- src/Preflight/ArgsRemapper.php
- src/Preflight/Preflight.php
- Adds __DRUPAL_ROOT__/drush and __PROJECT_ROOT__/drush as commandfile search paths
- Finds directories containing one or more of:
- composer.json
- Commands/
- src/Commands/
- Does **not** support drush.services.yml for these locations (must make a module for DI)
- Adds commands and hooks in DRUSH_BOOTSTRAP_NONE
Support for drush.services.yml not added for simplicity, and because commandfiles with dependency injection cannot be instantiated until DRUSH_BOOTSTRAP_FULL.
> Fixes #2918: Add site-specific search paths 

- commands/core/drupal/update.inc
See https://github.com/drush-ops/drush/issues/1427
> Check requirements before running updatedb

- examples/example.drush.yml
Hello!
I was literally copy-pasting from the example.drush.yml file when i encountered the fact that it is actually not valid yml on some of the lines.
Here is a PR that fixes that
Thanks for drush, everyone!
> Fix syntax errors in example.drush.yml

- src/Commands/core/RsyncCommands.php
- src/SiteAlias/AliasRecord.php
- tests/resources/alias-fixtures/example.alias.yml
- tests/rsyncTest.php
- tests/sqlSyncTest.php
#3075 was overzealous about injecting alias parameter options. This masked actual problems with ssh-option handling in backend invoke.
This PR maintains the #3075 behavior while fixing these bugs. This will give us a commit that has this feature and behaves correctly. The alias parameter behavior is backed out in #3079, which I will rebase after merging this PR into master.
> Follow-on to 3075: do not inject global site alias options

- src/Drupal/Commands/sql/SanitizeUserFieldsCommands.php
We need to check the storage definition exists when looping through user fields and checking `->isBaseField()` otherwise you get:
```
Error: Call to a member function isBaseField() on null in Drush\Drupal\Commands\sql\SanitizeUserFieldsCommands->sanitize()
```
> Check for null field storage definition in sql:sanitize

- src/Drupal/Commands/config/ConfigImportCommands.php
Found an instance where the old log method is still used instead of the new one from `psr/log`:
```
Error: Call to undefined method Drush\Log\Logger::warn() in Drush\Drupal\Commands\config\ConfigImportCommands->doImport() (line 231 of vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php)
```
> Fix outdated method call

- src/Commands/core/UpdateDBCommands.php
- tests/resources/devel.post_update.php
- tests/resources/updatedb_script.php
- tests/updateDBTest.php
Add option for running them.
Please test this PR. At the moment we have no automated tests for uodatedb.
> Fix #3021. Control when post-updates are run during updatedb.

- src/Sql/SqlPgsql.php
Fixed PHP notice "Undefined variable: password_file SqlPgsql.php:39" and typo in variable `$Spec` name, should be `$dbSpec`.
> Multiple issues in SqlPgsql::createPasswordFile

- composer.json
I think drush 9 depends on https://github.com/webflo/drupal-finder/pull/32. We should bump the dependency.
> Bump webflo/drupal-finder

- docs/commands.md
Hello.
I was curious as to why a global command should have the namespace `Drush\Commands[dir-name]` (notice the missing backslash), when I noticed the source actually contained this said character. So here is a PR making it forced code block, so it actually shows :)
The other change is a typo for what you should read about. There is no `docs-configuration`, only `docs:configuration`
> Fix typo and strangely formatted line about global commands

- .travis.yml
- src/Boot/DrupalBoot.php
- src/Boot/DrupalBoot8.php
- src/Commands/core/CacheCommands.php
- src/Commands/core/SiteInstallCommands.php
- src/Drupal/DrupalKernel.php
- src/Sql/SqlBase.php
- tests/CommandUnishTestCase.php
- tests/UnishTestCase.php
- tests/cacheCommandTest.php
- tests/configPullTest.php
- tests/configTest.php
- tests/pmEnDisUnListInfoTest.php
- tests/rsyncTest.php
- tests/siteSetTest.php
- tests/sqlDumpTest.php
- tests/updateDBTest.php
- tests/userTest.php
Superglobals now confined to `site:install` since Drupal’s install_begin_request() practices ancient voodoo (i.e. still requires globals - https://github.com/drupal/drupal/blob/d260101f1ea8a6970df88d2f1899248985c499fc/core/includes/install.core.inc#L287)
> Stop setting SERVER globals. Build a Request instead

- includes/environment.inc
- includes/filesystem.inc
- src/Config/Environment.php
- src/Sql/SqlBase.php
As a next step, I was thinking of moving the following functions to a static methods on new FileUtils class, in same directory as StringUtils. Feedback welcome on that.
drush_save_data_to_temp_file()
drush_tempnam()
drush_tempdir()
drush_register_file_for_deletion()
_drush_delete_registered_files()
> Move canonical storage of tmp dir to config()->get(env.tmp)

- .travis.yml
- composer.json
- isolation/composer.json
I started to fix #3130, but then stopped when I realized that mixing Drush with Drupal prevents us from using phpunit 5.x, and erg sebastion/version 2.x, making the upgrade pointless.
However, I realized that at some point, Drupal will upgrade to phpunit 5.x.  While we cannot anticipate every upgrade that Drupal might make, phpunit 4.x is very old, so this is probably overdue, or at least likely to happen eventually.
This PR sets up highest / lowest testing for the isolation tests, and allows the isolation tests to run across different versions of phpunit and sebastion/version. This will give us the flexibility to test with multiple versions of other libraries in the future, if we so desire.
The value for Drush being ahead of the game on upgrades is that it allows newer versions of Drupal …
> Plan for the future (see #3130): Allow for phpunit 5.x.

- src/Commands/core/UpdateDBCommands.php
Until a solution will land for https://github.com/drush-ops/drush/pull/3095, let's apply a quick fix for the batch finished callback of the `updatedb` command. Right now, that is still using an inexistent callback (`drush_update_finished`). As the batch API checks first for the existence of the function/method, this fails silently, without throwing any exception or error.
> Fix the batch finished callback for 'updatedb' command

- src/Commands/generate/Generators/Drush/DrushAliasFile.php
- src/Commands/generate/Generators/Drush/drush-alias-file.twig
Here is a simple generator.
1. This generates one environment called dev. Additional environments are expected to be added by hand
1. Writes to PROJECT_ROOT/drush/[prefix].site.yml. User can rename/move the file by hand.
1. Interactively gathers root, uri, host, user. Reasonable defaults for each are offered.
1. Adds lots of help text at the top for guiding further customization. Thi
Any other requests/suggestions for this?
> Fix #3133. Add site alias generator.

- .travis.yml
- composer.json
- composer.lock
Update to latest version of annotated-command, which no longer requires reflection-docblock.
Re-creating PR #3156 to see if it is necessary to set the base branch in advance in order for Travis to run the tests.
> Remove pin of reflection-docblock. 

- src/Commands/sql/SqlCommands.php
This commit removed `drush_bootstrap_max()` but it was still being called elsewhere.
https://github.com/drush-ops/drush/commit/440be17aceeacef9308db747bd17e874883cb2ef
> Fixed call to legacy bootstrap function.

- src/Commands/generate/Generators/Drush/DrushCommandFile.php
Setting wrong file path in `drush generate dcf` causes a fatal error.
"PHP Fatal error:  require_once(): Failed opening required 'wrong file path'"
Throwing exceptions would allow console application fail gracefully.
This PR also handle the case when the provided file has no valid Drush command hook.
> Validate legacy command file

- includes/output.inc
See #3163. Replaces https://github.com/drush-ops/drush/pull/3169
> #3163: always fwrite in drush_print, instead of print.

- includes/output.inc
This is a problem because of backwards compatability. drush_print_prompt() has a handle with a default of NULL and then it passes that to drush_print(). Since it passes a default, the file descriptor is NULL and not STDOUT. We could fix all internal calls, sure, but I think for backwards compatibility with drush_print() we shouldn't change the default, and we should handle it in the function.
See #3163 and the conversation on https://github.com/drush-ops/drush/pull/3171
> #3163: don't use STDOUT as a function parameter default for backwards compatability, i.e. see drush_print_prompt()

- docs/commands.md
- src/Commands/generate/Generators/Drush/DrushCommandFile.php
- src/Commands/generate/Generators/Drush/dcf-composer.json
- src/Commands/generate/Generators/Drush/dcf-composer.json.twig
- src/Commands/generate/Generators/Drush/drush-command-file.twig
- src/Drupal/DrupalKernel.php
- Defines a composer.json that the dcf generator writes.
- Improves error reporting for bad composer.json content (still experimenting with right levels)
- Adds some documentation on how to stipulate multiple drush.services.yml files.
> Add a composer.json file to the output of the 'drush gen dcf' command.

- src/Application.php
- src/Commands/help/HelpCommands.php
Allow Drush help validate to behave as intended when 'drush help' is run without a command name.
> Fix 'drush help' w/out command name

- examples/example.drush.yml
- src/Commands/OptionsCommands.php
- src/Sql/SqlTableSelectionTrait.php
The three settings are missing in optionset_table_selection. Drush does not load the options otherwise.
@greg-1-anderson Should i add the ``@option`` annotation for these options? I think they should not be visible in the help section of the command. Because its not clear how to define an array via CLI. I saw other commands have ``@hidden-options``. What you i use?
It works fine without the annotation anyways.
I have checked the examples in ``example.drush.yml`` and it works as expected with this small fix. 👍
> Add skip-tables, structure-tables and tables to @optionset_table_selection

- src/Log/DrushLog.php
I guess this was already planned :
// TODO: RfcLogLevel::DEBUG should be 'debug' rather than 'notice'?
I get too much logs on my production servers.
> The debug logs come out as notice

- composer.json
- src/Commands/generate/GenerateCommands.php
Currently it's not possible to run `drush generate module` or `drush generate theme` because Symfony console application cannot identify these commands by aliases (see https://github.com/symfony/symfony/issues/25355). As a workaround I propose we identify `generate module` command explicitly because it is potentially one of the most used generators.
For `generate theme` it is not a problem any longer as it has been renamed (d8:theme:standard => d8:theme) in DCG 1.21.
> Enable calling module and theme generators by their aliases

- isolation/tests/LegacyAliasConverterTest.php
- src/SiteAlias/LegacyAliasConverter.php
- tests/SiteAliasConvertTest.php
Legacy alias file conversion was leaving ssh options at `options.ssh-options`, but the new correct location is `ssh.options`.
> Move options.ssh-options to ssh.options

- misc/d8-rs-router.php
Whilst working with drush runserver for a test environment I discovered that it doesn't support update.php. Drupal core's script has the same problem see: https://www.drupal.org/project/drupal/issues/2929198#comment-12374814
Steps to test
1. Install standard Drupal
2. Start up server using drush runserver --default-server=builtin 8080
3. Visit http://localhost:8080/update.php
4. Click on the continue button
5. You should see the next page either the review or a message saying no updates. Without this patch you get a 404.
6. Ensure that admin/structure/types/manage/article/fields/node.article.body is not broken since this is why with the script in the first place - see https://bugs.php.net/bug.php?id=61286
7. Ensure that http://localhost:8888/update.php/selection/blahd.blah
falls back to …
> Fix router.php to work with update.php

- src/Config/DrushConfig.php
Fixes #3221 
After `drush_mkdir()` was deprecated, it always returns `TRUE`, even the cache dir candidate has failed to be created. For this reason, the next candidate never get a chance to be tested or used.
> Next cache dir candidates are not tested if first fails

- src/Application.php
- src/Preflight/Preflight.php
I have a local site alias that defines a uri but no root. A root is not needed anymore because that gets located correctly based on me using vendor/bin/drush.
> Use uri from an alias when that alias has no root.

- src/Commands/core/UpdateDBCommands.php
- tests/resources/modules/d8/woot/woot.install
It was failing with "Error: Cannot use object of type
Drupal\Core\StringTranslation\TranslatableMarkup as array in
Drush\Commands\core\UpdateDBCommands->updateFinished() (line 357 of
vendor/drush/drush/src/Commands/core/UpdateDBCommands.php).".
> Fixed failing updb command.

- src/Commands/core/UpdateDBCommands.php
With latest changes in Drush 9, I'm getting empty notices when running `updatedb`.
> Don't output empty notices on updb

- src/Commands/core/UpdateDBCommands.php
As mentioned in #2358, it's weird if site goes live automatically after `drush updb`.
> Restore original maintenance mode state after database updates

- includes/drush.inc
- src/Log/Logger.php
- src/Preflight/LegacyPreflight.php
I did some debugging related to #2214 and noticed that DRUSH_NOCOLOR is mostly unused now. 
---
Disclaimer: This is very low-level code in Drush, not sure if this is the right thing.
> Replace DRUSH_NOCOLOR with OutputInterface::isDecorated

- misc/d8-rs-router.php
Discovered some problems with https://github.com/drush-ops/drush/pull/3218 - I've updated the corresponding core patch - see https://www.drupal.org/project/drupal/issues/2929198.
The problem is with image styles - to reproduce:
1. Install standard
2. Go to node/add/article 
3. Create an article with an image
4. Save - you should see your uploaded image. IN Drush HEAD you don't. With this patch you do.
I've also tested the update.php stuff that was failing before https://github.com/drush-ops/drush/pull/3218 and that all still works.
> Fix runserver command to work with image styles

- src/Drupal/Commands/config/ConfigCommands.php
This drove me nut for a bit, it was happening on drush 9 but not drush 8.
According to http://cgit.drupalcode.org/drupal/tree/core/lib/Drupal/Core/Config/ConfigFactoryInterface.php?h=8.4.x#n27 "is always loaded override free."
Although done slightly different, on 8x is like this: https://github.com/drush-ops/drush/blob/8.x/commands/core/config.drush.inc#L844
> The cget --include-overridden is currently reversed

- src/Commands/core/UpdateDBCommands.php
We just had a failure during execution of `drush update-db -vvv` but no error was logged and the build returned a success message:
```
[success] Finished performing updates. [331.09 sec, 38.91 MB]
```
Here is the full log output with debugging enabled, there were no warnings or errors, but the update failed, and an error code was returned:
```
[debug] Start bootstrap of the Drupal Kernel. [2.11 sec, 8.16 MB]
[notice] config_sync should have an extra.drush.services section in its composer.json. See http://docs.drush.org/en/master/commands/#specifying-the-services-file. [2.2 sec, 10.79 MB]
[notice] search_api should have an extra.drush.services section in its composer.json. See http://docs.drush.org/en/master/commands/#specifying-the-services-file. [2.2 sec, 10.79 MB]
[debug] Get container …
```
> Add logging if an error occurs during an update

- src/Commands/generate/GenerateCommands.php
Default Symfony console commands (`help` and `list`) are disallowed in Drush generate application however they are still shown in the categorized list.
> Exclude default console commands from list of available generators

- examples/example.prompt.sh
- src/Commands/core/InitCommands.php
> Fixes #3289: Bash helpers don't work on Mac.

- includes/output.inc
This is for #3226. 
In PHP 7.2, there is a notice raised because the PEAR `console_table` makes a `\count()` call on a variable that is not an `array`/`Countable` . Because maintaining a fixed version of this PEAR package is not worth the effort at this stage (Drush 9.x no longer uses this package), we avoid the notice by silencing PHP with the `@silent` operator.
> Fix count() calls on uncountable variables in \Console_Table class

- includes/backend.inc
- includes/startup.inc
A backport (see #3174) of SSH command escaping that properly handles "LOCAL" as a reference to the host OS, as opposed to the remote OS.
> Backport of #3174, SSH command escaping

- tests/README.md
By default the SUT is installed in the temporary folder. Let's explain in the documentation how it can be installed in a different folder.
> Document how to install the SUT in a different folder

- src/Preflight/PreflightArgs.php
- src/Symfony/DrushArgvInput.php
A private copy of ArgvInput (v3.4.2) that has commented out the poor section of hasParameterOption(). Is it OK for other versions of Sumfony to get this file, including Symfony2 users? If not, how to filter to just right installations?
ArgvInput has private members so seems like copying is the only way (thats what LessStrictArgvInput does as well).
>  Add private copy of ArgvInput to fix Console bug

- tests/AnnotatedCommandTest.php
- tests/UnishTestCase.php
- tests/UserTest.php
Set $_SERVER as well putenv() when setting env variables in Unish. This is apparently needed in new Process release. Possibly caused by https://github.com/symfony/symfony/pull/25559/files.
The new SetEnv() method will change its implementation once we drop Symfony 2 (March 2018)
> Support Symfony Process 3.4 Unish environment variables

- src/Preflight/ArgsRemapper.php
- tests/ArgsRemapperTest.php
Fixes #3295 by limiting the remapping to the first argument (properly).
> Fix argument remapping. Limit remapping to first argument.

- .travis.yml
> Try testing PHP 7.2 on the isolation tests.

- includes/output.inc
Always use 'fwrite' instead of 'print' in 'drush_print' to avoid undesired interaction with PHP's handling of the php headers.
> Fixes #3351: site-install Drupal 7 with PHP 7.2

- includes/environment.inc
This is a backport of #3359 to Drush 8.
> (Backport) Environment variables are prepended to Drush command in the wrong order

- composer.lock
This is a follow up for #3325. I did not notice that time that Drush 8.x has _composer.lock_ file.
> Update pear/console_table package (once again)

- docs/commands.md
Resolves #3366 
The current docs aren't really incorrect but this might help clarify things for future use. @Skarlso see: http://php.net/manual/en/language.namespaces.rules.php
> Clarify namespaces in command authoring docs.

- src/Commands/sql/SqlCommands.php
- src/Sql/SqlBase.php
Fixes #3364.
Drush 9 has lost a Drush 8 feature:
* If `--result-file` is provided with no value, then a date-based filename will be created under ~/drush-backups directory.
That's a really useful option for automated backups, but Symfony Console makes it hard to work with options that can be both Boolean and a string.
This PR adds a new `--result-file-auto` Boolean option to resurrect this.
If both `--result-file` and `--result-file-auto` are given, `--result-file` takes precedence.
Does something like this look like a possible solution to #3364?
> Add --result-file-auto to save to a date-based filename under ~/drush-backups directory

- src/Drupal/Commands/config/ConfigImportCommands.php
This commit fixes the issue by looking for the label in ConfigImportCommands.php's import function. If the label exists, it uses the config directory specified in $config_directories in settings.php for that label (as described in [the documentation](https://drushcommands.com/drush-9x/config/config:import/)). If the source option is specified, it uses that but outputs a notice mentioning what happened.
This fix should retain all existing functionality, and allow users to once again use non-default directories by specifying them in the settings.php.
> #3383 - fix label not being used for drush config:import command

- lib/Drush/Queue/Queue8.php
If a SuspendQueueException is thrown when processing an item the current
implementation will release the item and log an error. Processing of the
queue continues.
According to the documentation of the SuspendQueueException throwing 
this exception indicates that processing of the whole queue should be skipped.
This change breaks the queue item processing loop entirely after logging
the error.
The associated code comment is also updated as it does not make sense.
The queue run command only runs for a single queue so there is nothing
to skip to.
> Stop all processing of queue on SuspendQueueException

- src/SiteAlias/HostPath.php
- tests/RsyncTest.php
%files should resolve to `sites/default/files/` as it historically has, not `sites/default/files`.
With this PR:
```
$ ./sut -s rsync %files /tmp
Calling system(rsync -e 'ssh ' -akz /PATH/sites/dev/files/ /tmp);
$ ./sut -s rsync %files/ /tmp
Calling system(rsync -e 'ssh ' -akz /PATH/sites/dev/files/ /tmp);
$ ./sut -s rsync %files/foo /tmp
Calling system(rsync -e 'ssh ' -akz /PATH/sites/dev/files/foo /tmp);
$ ./sut -s rsync %files/foo/ /tmp
Calling system(rsync -e 'ssh ' -akz /PATH/sites/dev/files/foo/ /tmp);
```
This may need backporting to Drush 8, as I am seeing the `/` being dropped there as well. Drush 7 isn't working for me right now.
> Fixes #3306: Make sure that rsync with %files resolves correctly

- src/Boot/BaseBoot.php
- src/Runtime/DependencyInjection.php
The problem is that League/Container does not provide public access to the inflectors, so we need to remember to update our duplicate inflection method when new services are added to the container as inflectors.
> Make sure that site alias manager is inflected for command objects that need it.

- .circleci/setup.sh
- src/Commands/sql/SqlCommands.php
- src/Commands/sql/SqlSyncCommands.php
One downside of this fix is that running this code with a prior version of Drush will cause your dump files to be names `auto` instead of date based backups. I think mismatched Drush versions are a lot less common now that we are local to the project.
> Fix #3417. sql-sync dump filename not automatically generated

- tests/AnnotatedCommandTest.php
- tests/ContainerTest.php
- tests/QueueTest.php
- tests/RoleTest.php
- tests/TestModuleHelperTrait.php
- tests/UpdateDBTest.php
Split from #3402 to reduce the PR footprint there.
There are repetitive tasks and code duplication in some of the tests that are using the testing modules (`woot`). Allow code reusing for the setup of testing modules by moving the common code in a trait.
> Move the setup of testing modules in a trait

- docs/commands.md
- src/Boot/DrupalBoot8.php
- src/Drupal/DrushServiceModifier.php
- tests/CommandInfoAlterTest.php
- tests/resources/modules/d8/woot/drush.services.yml
- tests/resources/modules/d8/woot/src/Commands/WootCommands.php
- tests/resources/modules/d8/woot/src/WootCommandInfoAlterer.php
We are able to alter/replace commands in modules but we cannot intercept and alter the command info (annotations). This PR adds such capability.
How it works?
- Modules wanting to alter the command info should add a service class that implements `\Consolidation\AnnotatedCommand\CommandInfoAltererInterface`.
- The service should be added in `drush.services.yml` and should be tagged with the `drush.command_info_alterer` tag.
- Add the alter logic in the `alterCommandInfo()` of the alterer class.
See the testing `woot` module for details.
> Allow registering of command info alterer services

- src/Drupal/Commands/core/EntityCommands.php
``entity:delete`` uses 'type' as fixed bundle key. We should use the bundle key from the entity definition. This should work for every entity type.
> Use bundle key in entity:delete command

- src/Boot/DrupalBoot.php
Testing Drush 9.2.1 on XAMPP on Windows, I discovered this nice bug. Any Drush command would use 30% of the CPU and never finish. After some digging it was clear that DrupalBoot::scanUpForUri was the guilty one. 
The bug is only present if you start in the Drupal site root. If you start inside the core or sites folder, the infinite loop isn't triggered. If you start in the Drupal site root, $root and $scan are identical, and as a result (of flawed logic IMHO) scanUpForUri ends up scanning all the way to the file system root.
On Linux scanUpForUri stops when it's gets to the  file system root because $scan and $next becomes equal. On Windows this doesn't happen because of a nice bug in dirname:
`dirname('C:/somedir')` returns `C:\`, not the canonical `C:/`. 
The fix in the pull request is …
> Fix infinite loop in DrupalBoot::scanUpForUri (on Windows)

- docs/install-alternative.md
Still getting support requests about this; c.f. #3470. Let's get 'composer global' out of the maintenance branch installation instructions too.
> Change installation instructions to recommend cgr instead of 'composer global'

- src/Sql/SqlPgsql.php
This pull request should make it possible to create a PostgreSQL database with Drush sql:create command.
In PostgreSQL backticks don't exist, so they must be replaced by quotes.
> Fix the way to create PostgreSQL database

- src/Drupal/Commands/core/WatchdogCommands.php
drush watchdog:delete command fixed when no option is given. Earlier it give's following error:
_SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1: DELETE FROM {watchdog}
WHERE (); Array
(
)_
> watchdog:delete command fixed, when no option is given.

- commands/make/make.drush.inc
- tests/makeConvertTest.php
This patch fixes the composer.json make conversion.
As the maintainer of the [7.x branch of drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project/tree/7.x), I really want to convince people to leave drush make behind and move over to composer.json. Even for Drupal 7 sites.
However, the current "drush make-convert --format=composer" has several flaws:
1. It still uses webflo's packagist.drupal-composer.org, which is no longer active.
2. It assumes Drupal 8 installer-paths.
3. It uses versioning system from webflo's packagist (see #2261)
4. It doesn't support drupal-composer/preserve-paths for D7 sites.
This patch fixes all the above, moving to the packages.drupal.org packagist.
> Fix drush make-convert --format=composer

- commands/make/make.drush.inc
I am getting some warnings when building a legacy Drupal 7 project in PHP 7.2:
```
count(): Parameter must be an array or an object that implements Countable make.drush.inc:631
```
> Fix PHP 7.2 warning regarding count()

- includes/startup.inc
Affects hosts that have pcntl_exec(). Other hosts were similarly fixed in #2318. Since #2318 has been in Drush for a long time, I feel comfortable making this change even though 8.x is in maintenance now.
> Fix #2285, #2268. Recognize current working dir for multisites

- lib/Drush/Sql/SqlBase.php
Pull request #2882 works for Drupal 8 but breaks in Drupal 7. This new pull request makes it work well with both Drupal 8 and Drupal 7. Thanks for code review from @jorrit.
> fix Drush command sql-query with option "--db-prefix" in use

- includes/backend.inc
As mentioned in Slack at https://drupal.slack.com/archives/C62H9CWQM/p1527875860000040
I also fixed a typo in another docblock I saw as I was scrolling through.
> Mark drush_backend_invoke_concurrent as deprecated

- composer.json
- isolation/composer.json
Symfony 4.1 comes with new cool feature called [VarDumper server](https://symfony.com/blog/new-in-symfony-4-1-vardumper-server). This is very useful especially for debugging non-HTML responses and unit tests. Unfortunately, it is not possible to take advantage of VarDumper server on Drupal installation witth Drush  because of dependency conflict.
As a bonus, fixing this would also resolve the issue with installing Drush after Drupal console (https://github.com/hechoendrupal/drupal-console/issues/3249), which is probably caused by this Composer bug https://github.com/composer/composer/issues/7329.
> Support var-dumper 4.x

- src/Commands/generate/GenerateCommands.php
On some Windows environments color support detection fails. This could be mitigated by passing `--no-ansi` option, which is currently not respected by `drush generate` command.
> Pass ANSI options to generate command

- src/Boot/DrupalBoot8.php
If I perform a command such as the following I get a warning about an undefined index:
```
$ drush --root="/home/pieter/v/joinup/web" --verbose cache-rebuild
[info] Undefined index: scheme DrupalBoot8.php:121
[success] Cache rebuild complete.
```
> Warning: Undefined index: 'scheme' in DrupalBoot8::bootstrapDrupalSiteValidate()

- examples/example.drush.yml
- src/Config/DrushConfig.php
With this PR you can control cache dir without changing the $HOME environment variable. Just set `DRUSH_PATHS_CACHE_DIRECTORY` env variable to the directory you want to use. Drush will create the directory if it doesn't yet exist.
Fixes #3592, #3594
> Enable separate configurability of the Drush cache directory.

- composer.json
- examples/example.site.yml
- isolation/tests/SiteAliasFileLoaderTest.php
- tests/SiteAliasConvertTest.php
Allow site aliases to be referred to by a 'location' component of the alias name that is based on the name of the folder the alias file is stored in.
See the PR at https://github.com/consolidation/site-alias/pull/1
> Site alias location filters

- examples/example.site.yml
The primary goal of this rewrite is to pull the canonical site alias example up to the top of the example file, so that beginning users can read just the first section and get the overall idea on how to use the recommended workflow for site alias files that are local to a single site.
More advanced workflows and use cases are pushed down to the lower sections of the document.
> Improve site alias example documentation.

- src/Drupal/Commands/config/ConfigCommands.php
This should fix #3596.
I've added _Path::canonicalize()_ as it is done in `drush cim` command.
https://github.com/drush-ops/drush/blob/9.3.0/src/Drupal/Commands/config/ConfigImportCommands.php#L168
> Canonicalize directory

- src/Commands/core/StatusCommands.php
Adding drush cache directory as an output field in drush status (`@command core:status`) as a sanity check for the new `cache-directory` config/`DRUSH_PATHS_CACHE_DIRECTORY` env variable added in #3597.
Example usage: `drush status --field=drush-cache-directory`
> Adding drush cache directory to core:status

- commands/core/drupal/update.inc
This is the PR for 8.x.
Post updates use the update function in core, which is great and I will update the core patch to set the constant there as well.
Fixes #3604
> Set maintenance mode to update when running updates

- examples/example.site.yml
- src/Runtime/RedispatchHook.php
Usually Drush decides whether or not to create a tty for remote ssh commands based on whether the current Drush command is running in interactive mode or not. When in interactive mode, a tty is created; otherwise, no tty is created.
Sometimes, a remote server will not grant the ssh user the permission to create a tty. In this instance, it is possible to force Drush to never create a tty via this new option.
> Add an 'ssh.tty' option to site aliased.

- src/Preflight/Preflight.php
- src/Preflight/PreflightSiteLocator.php
Allow un-found aliases on the commandline to be passed through to the site-local Drush.
> Fixes #3274: pass missing aliases to site-local Drush

- src/Commands/core/SiteInstallCommands.php
Fix #3624
Regarding https://www.drupal.org/project/drupal/issues/2788777 that allow a site to be installed from an existing configuration from 8.6.x version, here an update to change the usage of `--config-dir` option.
Up to now, this option allowed to import a full set of configuration after installation.
From now, configuration does not import anymore after installation, but during installation.
> fix #3624: Change usage of '--config-dir' site-install option.

- composer.json
- scenarios/isolation-phpunit4/composer.json
- scenarios/isolation/composer.json
- src/Commands/core/SiteCommands.php
e.g. @location.site.env or @location.site, in addition to just @location or @site.
A simple bugfix / enhancement that makes Drush 9 sa work more like Drush 8 sa.
> Allow multipart aliases with drush sa, 

- src/Preflight/Preflight.php
- Fixed PHP notice:
PHP Notice:  Undefined variable: preflightArgs in /var/www/html/vendor/drush/drush/src/Preflight/Preflight.php on line 297
> Fix undefined variable preflightArgs notice

- src/Boot/BaseBoot.php
Not sure if this is effective, but it at least does not crash.
> Fixes #3672: Call Boot::terminate() in a shutdown handler.

- .env.example
- CONTRIBUTING.md
- README.md
- docker-compose.yml
- tests/README.md
Allows for tests on mariadb, postgres, sqlite. Includes Xdebug. Includes docs.
> Provide docker-compose for running tests and developing Drush

- composer.json
- composer.lock
- includes/annotationcommand_adapter.inc
- lib/Drush/Commands/DrushCommands.php
- lib/Drush/DrushConfig.php
Use new features of the commandfile discovery class in the new version of the annotated command library, 2.9.1 to allow site-wide Drush extensions to be placed in contrib/custom directories without adding those names to the namespace, so the namespace of a command does not change if it moves from 'contrib' to 'custom'.
I managed to make a version of the Behat Drush Endpoint that works with both Drush 8 and Drush 9. I'd like to backport #3687 so that the Drush 9 version of the same command can also work in Drush 8. Drush commands (site-wide or bundled with modules) could be made to work with both if they limited themselves to using only Drupal core APIs + the APIs of the module they are attached to + limited Drush features such as the logger and output formatters. A standalone project that …
> Backport #3687: preserve 'contrib' and 'custom' dir placements

- includes/environment.inc
Since set_error_handler was introduced, the fifth argument has been optional. In
PHP 7.2 it has been deprecated. The argument is not even used in the function.
> Make drush_error_handler's fifth argument optional.

- src/Commands/core/XhprofCommands.php
Drush includes built-in functionality to profile commands using XHProf or Tideways.
Tideways recently went through a [pretty significant refactoring](https://tideways.com/profiler/blog/releasing-new-tideways-xhprof-extension), which changed the extension name and apparently some of the internals as well, although the data format is still compatible with the XHProf UI. This requires Drush to update its integration as well.
I could think of ways to improve this approach, but I wanted to get at least a working PoC for maintainers to review before putting more work into it. Primarily, it would be nice to support flags, which are now also named differently in Tideways. Also, maybe use an abstract "profiler" interface to support either XHProf or Tideways (or even different versions of …
> Compatibility with new Tideways XHProf extension.

- src/Sql/SqlPgsql.php
Fixes: #492. This PR replaces #880.
----
Under a windows environment for a Postgres database, the variable "PGPASSFILE=..." will be interpreted as a command (not found of course, as it's not a valid command).
The result is it asks for password (but silently with the -q parameter), so the drush command is blocked and the password can't be input by the prompt.
In order to set properly the variable, I added a "SET" command if it's under windows platform.
I don't know if it's the best way to handle environment issue here, but it seems to work.
----
> GH-492: Fixes PGPASSFILE error as not an internal or external command

- composer.json
- scenarios/isolation-phpunit4/composer.json
- scenarios/isolation/composer.json
- tests/UpdateDBTest.php
The offending patch used to only be applied to our test system but I inadvertently made it so that Drupal installs that have extra config enable_patching: true in their composer.json extra config get the patch too. 
For now removing the patch and the test that depends on it. We'll find a better way. I made a [quick feature request in cweagans/composer-patches](https://github.com/cweagans/composer-patches/issues/237)
> Fix #3730. Remove patch to drupal/core 

- commands/sql/sql.drush.inc
This PR ensures `drush sql-create` returns a non-zero status when it fails.  See https://github.com/drush-ops/drush/pull/3732 and https://github.com/drush-ops/drush/pull/2925.
> Set a non-zero exit status for "sql-create" on failure

- commands/core/cli.drush.inc
so that we can change the default working directory.
Hi I love drush and I love the addition of psysh through core-cli. I'd love an option for changing the working directory while I'm working on a custom module or something so I added a cwd option to the core-cli command. This way I can do something like this:
```
drush core-cli --cwd="$(pwd -P)"
```
Now, when the interactive psysh shell is lifted, the current working directory is wherever I am working.
I hope this is useful.
> Drush 8.x: Adding cwd option to core-cli

- tests/README.md
- The docker php service name was changed in https://github.com/drush-ops/drush/pull/3728 but not the doc.
- There is no test named `testVersionString`, so when you execute the examples you end up with a `No tests executed!` message. IMO, this is bad for the DX. When I copy paste an example from a doc, I expect it to work. I updated the `--filter` argument with an actually existing test (I chose it randomly).
> Improve tests README

- docs/index.md
VersionEye was shut down at the end of 2017. See https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/
The link now goes to a page which gives a certificate security warning, and if you continue redirects you to something completely different (Médica Panamericana).
> Removed link to VersionEye

- composer.json
- scenarios/isolation-phpunit4/composer.json
- scenarios/isolation/composer.json
This change was accepted in https://github.com/drush-ops/drush/pull/3578 but was mistakenly reverted (I guess ? @weitzman) in https://github.com/drush-ops/drush/pull/3697.
> Allow symfony/var-dumper 4 again

- src/Commands/pm/SecurityUpdateCommands.php
The bug here is that 'packages-dev' and 'packages' are both arrays with
numeric keys. Using the '+' operator on them, according to PHP's
documentation (https://secure.php.net/manual/en/language.operators.array.php),
means that if a key exists in both, whatever array is on the right-hand side
will have that key's value ignored and the left-hand side's value will be
used.
To ensure that the 'packages' array is appended to the 'packages-dev' array,
we have to use array_merge, which always appends numeric keys
(https://secure.php.net/manual/en/function.array-merge.php).
> Fix bug where pm:security misses required security updates.

- composer.json
The `symfony/finder` component is not a core Drupal dependency. So it not technically locked to `^3.4`.
I have reviewed the usage that is made of this component in drush. The only thing that is used is the `Symfony\Component\Finder\Finder` class.
I have checked every method of this class that is used by drush. Then I have read the CHANGELOG of the component and did not see any obvious impact for drush. Then I made a diff between the `3.4` branch and the `master` branch of this class file and manually checked changes that could break drush usage of this component. I did not find any.
It would be great to accept v4 of this component, so projects that require drush and this component directly can use the latest version.
> Allow symfony/finder 4

- includes/backend.inc
If a drush command uses a Robo collection (or perhaps just a Robo task—untested), and that command is invoked as a backend process, and that command fails, you may see an error like this:
```
[error]  Drush command terminated abnormally due to an unrecoverable error.
Error: Uncaught Error: Unsupported operand types in /app/vendor/consolidation/log/src/LogOutputStyler.php:66
Stack trace:
#0 /app/vendor/consolidation/log/src/Logger.php(186): Consolidation\Log\LogOutputStyler->style(Array)
#1 /app/vendor/consolidation/log/src/Logger.php(171): Consolidation\Log\Logger->doLog(Object(Symfony\Component\Console\Output\StreamOutput), 'error', '', Array)
#2 /app/vendor/drush/drush/src/Log/Logger.php(174): Consolidation\Log\Logger->log('error', '', Array)
#3 …
```
> Unset _style during encode/decode of backend packets to avoid type mismatch errors

- includes/backend.inc
- includes/bootstrap.inc
- includes/cache.inc
- includes/drupal.inc
- src/Boot/BootstrapManager.php
- src/Boot/DrupalBoot.php
- src/Boot/DrupalBoot8.php
- src/Log/Logger.php
- tests/functional/AnnotatedCommandTest.php
Main change is that the bootstrap phase is now tracked with a property on the Boot class.
This builds upon the other PR from today #3794
> Remove context.inc usage in Boot classes

- includes/preflight.inc
The exception was printing another backtrace which clutterred things. Use regular log message instead.
However, I still think we are printing too often here. If there is a fatal error anywhere in the request we write the message about exit(). A much more relevant message has already been reported. I think we need more criteria around this log message.
> More gentle exit() reporting.

- src/Boot/DrupalBoot.php
- src/Boot/DrupalBoot8.php
Removes a dependency on the SQL classes and Drush users may no skip installation of `mysql` CLI client if they don't want to run sql commands. This is nice for mnimalist Docker pwoered environments.
> Use Drupal DB during bootstrap instead of CLI

- includes/backend.inc
- includes/drush.inc
- src/Log/Logger.php
And instruct backend to use the new methods.
> Collect log messages in Logger instead of in context system.

- sut/drush/sites/sut.site.yml
- sut/drush/sites/synctest.site.yml
- tests/unish/UnishTestCase.php
We don't need to dynamically generate these any more.
> Add sut alias record to repository rather than building it dynamically

- includes/preflight.inc
There have been many reports of ssh issues with 8.1.17. See #3725. I believe the changes in #3428 are the source of the breakage.
I'm able to connect successfully if I use `--local`: `drush --local @alias ssh`. I'm also able to connect if I use only a global drush. The combination of a global drush calling a local drush breaks.
I find myself very confused with the variable names. The command setting `handle-remote-commands` sounds to me like it should run the command remotely, but the docs say ```set to TRUE if `drush @remote mycommand` should be executed locally rather than remotely dispatched```.
The `ssh` command has `handle-remote-commands` set to `TRUE` so it should always be executed locally.
In the changes for #3428, a new variable `$must_use_site_local` is defined. To me it sounds …
> Fix ssh to site alias

- tests/integration/ImageTest.php
- tests/integration/WatchdogTest.php
- tests/unish/Controllers/RuntimeController.php
- tests/unish/UnishIntegrationTestCase.php
> Allow integration tests to test commands that have confirmations

- src/Commands/core/SshCommands.php
- tests/functional/SiteSshTest.php
(supported in Drush 9.5.2).
Fix bug with lack of echo'ed output in 'drush @site ssh cmd'.
n.b. `simulate` mode not working in integration tests at the moment. Moving this to be an integration test wouldn't be much of a time savings in the test, since these tests do not set up a Drupal site.
> Bring back legacy support for space-separated commands in 'drush ssh'

- src/Drupal/Commands/config/ConfigCommands.php
There should not be a full stop here, as the framework adds a colon:
```
Choose a source.:
[0] Cancel
[1] sync
[2] vcs
```
> Fixed config location prompt has an unnecessary full stop

- src/Runtime/RedispatchHook.php
Use $aliasRecord->isLocal() rather than getOption('remote-host') to determine whether to redispatch.
Merge this into #3835 , and then it shouldn't be necessary to [remap docker.service](https://github.com/consolidation/site-alias/pull/30/files/016f5a8c77bb455038d29696d0c0e94c7b00e230..ed6d1fb2e5a939297964cf088c13d322df789818#diff-61c9423e4386ba78d1b3d7d9523ce5e9R268) in https://github.com/consolidation/site-alias/pull/30.
Presuming tests pass here, anyway.
> Stop using 'remote-host' in redispatch hook.

- src/Application.php
- src/Boot/BootstrapManager.php
- src/Commands/DrushCommands.php
- src/Commands/config/ConfigPullCommands.php
- src/Commands/core/BrowseCommands.php
- src/Commands/core/EditCommands.php
- src/Commands/core/LoginCommands.php
- src/Commands/core/NotifyCommands.php
- src/Commands/core/RsyncCommands.php
- src/Commands/core/RunserverCommands.php
- src/Commands/core/SiteCommands.php
- src/Commands/core/SiteInstallCommands.php
- src/Commands/core/SshCommands.php
- src/Commands/core/StatusCommands.php
- src/Commands/core/UpdateDBCommands.php
- src/Commands/core/XhprofCommands.php
- src/Commands/sql/SqlCommands.php
- src/Commands/sql/SqlSyncCommands.php
- src/Config/ConfigAwareTrait.php
- src/Config/DrushConfig.php
- src/Drupal/Commands/config/ConfigCommands.php
- src/Drupal/Commands/core/RoleCommands.php
- src/Drupal/Commands/core/UserCommands.php
- src/Drush.php
- src/Runtime/RedispatchHook.php
- src/Runtime/TildeExpansionHook.php
- src/SiteAlias/ProcessManager.php
- src/Sql/SqlBase.php
Depend on injected config object rather than static `Drush::` methods wherever possible.
> Move some methods from Drush:: to DrushConfig::

- src/Commands/core/CacheCommands.php
Fixes #3836.
It looks like _drupal_log_error() no longer themes error messages form CLI requests. So lets remove this code.
> Remove set_error_handler('drush_error_handler') from cache:rebuild.

- src/Commands/sql/SqlCommands.php
- src/Runtime/RedispatchHook.php
When using the Symfony Process component, it is necessary to call `setTty(true)` when an interactive program is called; however, if input is redirected, then it is important to not set tty mode to true. `setInput` must also be set, and it is possible to pass any resource stream, e.g. STDIN, to this API call.
Replaces #3865 (or at least a subset of it).
> Fixes #3859: Allow input to be piped to sql:cli

- src/Sql/SqlBase.php
This is almost right.
What we are trying to do here is wrap the 'pipefail' command in "bash -c" so that we can ensure that the shell is bash, since pipefail is a bash feature. We use interpolation on the pipefail string so that it is easy for the caller to alter the template as needed to support other shells.
The default pipefail string is: `bash -c "set -o pipefail; {{cmd}}"`
Also, 'pipefail' doesn't have anything to do with ssh, so I renamed the configuration name from 'ssh.pipefail' to 'sh.pipefail'.
Shortcomings:
1. This works if pipefail is empty, or if it is the default value. However, it is also possible that someone might use something like `set -o pipefail; {{cmd}}`, which for example should work if the user know their default shell is bash. However, at the moment this code …
> FIXES #3874: Wrap 'pipefail' in "bash -c".

- src/Boot/DrupalBoot.php
Avoids an error with the Acquia Cloud settings include files. And maybe more errors elsewhere.
> Set Drupal root context for backward compat.

- src/Commands/core/SshCommands.php
- tests/functional/SiteSshTest.php
Gets rid of --legacy which was not even declared as an option.
> Fix #3894. Assume pre-escaped for single arg calls to ssh command.

- includes/batch.inc
This code is broken. Since [migrate already handles low memory](https://github.com/drupal/drupal/blob/8.6.x/core/modules/migrate/src/MigrateExecutable.php#L256), this code no longer serves its original purpose.
> Fix #2762, #3117. Remove respawn after 50% memory exhaustion during batch processing.

- commands/pm/package_handler/git_drupalorg.inc
https://twitter.com/drupal_infra/status/1088571024918994945
> git:// is discontinued on drupal.org - use https://

- commands/core/drupal/update_7.inc
Currently  `update_check_requirements()` runs `update_check_requirements()` before a full bootstrap. And `update_check_requirements()` performs a writeable check on the filesystem - which invokes the file stream wrapper handling.
This fills a the static cache of `file_get_stream_wrappers` and because of the low bootstrap level not all available stream wrappers will be registered.
This can lead to missing stream wrappers in update hooks.
We should reset the file_get_stream_wrappers static cache before running the full bootstrap which then will re-evaluate the available stream wrappers.
> D7: file_get_stream_wrappers cache poisoning in update_check_requirements()

- src/Sql/SqlBase.php
- tests/functional/SiteInstallTest.php
Testing is only done for PostgreSQL and MySQL because SQLite doesn't actually prefix tables (see #3849 ) .
> DB prefix ignored when installing site

- composer.json
- composer.lock
- includes/annotationcommand_adapter.inc
- includes/command.inc
- includes/drush.inc
- includes/preflight.inc
- Allow '--no-interaction' (interpret as '--yes')
- Recognize '-vvv' (interpret as '--debug')
- Use Drupal Finder to locate Drupal root from composer.json
- Ensure that logger is injected into command files.
> Improve consistency of command files between Drush 9 and Drush 8:

- src/Preflight/Preflight.php
If Drush is installed as a dependency of a Drupal site (as we stipulate it always should be) and the cwd / alias does not find a site, then search for the site that Drush is installed in, and fall back to the sut only as a last resort.
Note that this PR does not fix the case where your cwd is inside the Drush project root for a Drush site installed inside a Drupal site. That is an edge case that not too many folks should encounter.
> Fixes #3940: Do not get confused by the SUT

- tests/integration/SecurityUpdatesTest.php
The current pm:security test fails if there is also a pending security release for some other module, or Drupal core. Make the check a little more flexible to avoid this problem.
> Make pm:security test more flexible

- src/Boot/BootstrapManager.php
- src/Boot/EmptyBoot.php
The bootstrap manager was not designed to work without some bootstrap object.
> Restore the EmptyBoot bootstrap object.

- docs/make.md
As per #3946, Drush make is no longer maintained. Let's inform people about this and propose alternatives.
> Drush make is no longer maintained (fixes #3946).

- docs/commands.md
https://github.com/drush-ops/drush/blob/master/docs/commands.md#site-wide-drush-commands
Currently the `examples/Commands` link leads to non-existing documentation  page.
http://docs.drush.org/en/master/examples/Commands
I suppose it should open `examples/Commands` folder on GitHub.
Also note that 404 pages on docs.drush.org are broken.
> Fix broken link in commands documentation

- src/Sql/SqlOracle.php
Add fix in SqlOracle.php to address warning - [warning] Declaration of Drush\Sql\SqlOracle::createdbSql($dbname) should be compatible with Drush\Sql\SqlBase::createdbSql($dbname, $quoted = false) SqlOracle.php:98
Read more https://github.com/drush-ops/drush/issues/3896
> Add second parameter in createdb function in SqlOracle.php .

- includes/batch.inc
> Fixes comment and notice message (#3952)

- src/Boot/DrupalBoot8.php
This is an addition to #3553 (committed just before Drush 9.3.0, https://github.com/drush-ops/drush/pull/3553/commits/3f18f8138e9174e700b22892ef4dd8d7bcca78ef) which continued #3166.
This PR fixed the situation for --uri=http://domain.com/subdir and for --uri=domain.com/subdir/, but not for --uri=domain.com/subdir . (This is a regression from Drush 8 and has caused some emergency work on an existing Drupal-using project. Not sure if this ever worked with Drush9; I only tested 9.2.3, which obviously doesn't work because... above referenced code is missing.)
In the latter case, $_SERVER['SCRIPT_NAME'] will contain 'subdirindex.php' (i.e. missing slash) ... which makes DrupalKernel::findSitePath() return "sites/default" instead of the correct directory in $sites.
I believe the fix, and the …
> Continue #3166/2. Fix script name when Drupal uses a domain + subdir without scheme.

- docs/dependency-injection.md
- src/Boot/BaseBoot.php
Currently it's impossible to implement such interface because in `\Drush\Boot\BaseBoot::inflect():146` the wrong method is called.
When an object implements `SiteAliasManagerAwareInterface` it should be injected via `siteAliasManager` instead of `setOutputAdapter` which is part of `VerbosityThresholdInterface`
> Allow implementing `SiteAliasManagerAwareInterface`. 

- src/Preflight/PreflightArgs.php
- src/Preflight/PreflightSiteLocator.php
- tests/functional/ConfigPullTest.php
- tests/functional/RedispatchTest.php
- tests/functional/RsyncTest.php
- tests/functional/SqlSyncTest.php
This is a start, but it looks like there are a few failures in the functional tests.
> Use --uri from commandline over uri in an alias

- src/Exceptions/UserAbortException.php
- tests/unit/UserAbortExceptionTest.php
\Throwable is documented as being first available in PHP 7:
http://php.net/manual/en/class.throwable.php
> Add a test for UserAbortException

- src/Config/ConfigLocator.php
- tests/unit/ConfigLocatorTest.php
Imagine you have a project layout that looks like this:
```
composer.json
sut
drush
drush.yml
sites
self.site.yml
web
index.php
```
Prior to this PR, Drush *does* find `drush.yml`, but it does *not* find `self.site.yml`. This is because the search paths Drush considers for alias paths includes the composer root and the Drupal root, but the parent of the Drupal root is not considered. This PR adds the parent of the Drupal root as a search base for site alias files.
This limitation does not affect Drush because the Drush sut has its document root as its base directory (where its composer.json would be, if it had its own composer.json). In the example project I am building, I want the sut to follow the same directory pattern as drupal-composer/drupal-project, for familiarity. There are …
> Consider parent directories of site roots when searching for alias paths

- .gitignore
- .scenarios.lock/php5/composer.json
- .scenarios.lock/php5/composer.lock
- appveyor.yml
- composer.json
- composer.lock
- includes/backend.inc
- src/Commands/sql/SqlSyncCommands.php
- sut/drush/sites/self.site.yml
- tests/functional/RsyncTest.php
- tests/integration/RsyncTest.php
- tests/unish/UnishIntegrationTestCase.php
Use format json instead of format string when fetching database credentials in sql:sync
> Use --format=json in sql:sync

- src/Commands/core/PhpCommands.php
It was a nice surprise this was only missing in the docs and that the functionality already exists.
> Document php:script supports stdin scripts

- composer.json
The current requirement of `consolidation/annotated-command:^2.9.1` does not include code needed for latest drush 8.2.0. I discovered it needs at least 2.11.0, but this PR bumps to the latest since I didn't exhaustively test every version.
Fixes #3985
> Bump minimum version of consolidation/annotated-command

- src/Boot/BootstrapManager.php
- sut/sites/example.sites.php
- tests/functional/CoreTest.php
These are two followups to #3847 which are not super related, but I hope putting them in one PR turns out to be less work.
1) I found out why bootstrapDrupalSiteValidate() is called a lot more lately (since #3820):
* BootstrapManager::bootstrapMax() has a loop for each phase, in which it calls bootstrapValidate()
* bootstrapValidate() only checks its $result_cache for _the current target phase_ is filled, and if it is not, validates _all phases from 0 up to this target phase_ again.
I'm going to just assume that was not intentional and that it can be fixed this way.
--
2) It was suggested to add a test, to add against regressions with the --uri flag.
So here it is. I'm guessing a fairly simple addition to CoreTest::testOptionsUri() will do the trick, even though that means it's now used …
> Don't call bootstrapValidate commands repeatedly, and add --uri tests

- includes/environment.inc
- includes/preflight.inc
- lib/Drush/Drush.php
This allows them to be called directly, e.g. from a module.
> Fixes #3988: Move code to get version directly to the static access methods.

- src/Config/Environment.php
- src/Preflight/Preflight.php
Similar to #3970, this is something I run in primarily when working on Drush.
- Run command using a global Drush (e.g. development Drush checked out from git)
- Use a site alias to a remote Pantheon site (n.b. there is no `root` element set)
- cwd points to a **different** local site with a similar site-local version of Drush
The flow of execution is something like this:
1. Because there is no root in the selected site alias, the reference to the site at the `$cwd` is lost, and the redispatch to site local does not happen.
2. Redispatching to remote sites happen after dependency injection
3. The local site's autoload file is loaded prior to dependency injection
4. The local site at the cwd is rediscovered and its autload file is loaded, just prior to the redispatch to the remote site. …
> Do not load the local autoload file if the alias is remote.

- lib/Drush/Drush.php
Discovered via the _PHPCompatibility.Variables.ForbiddenThisUseContexts.OutsideObjectContext_ PHPCompatibility PHPCS rule:
> "$this" can no longer be used in a plain function or method since PHP 7.1.
> Fix $this being used in a static context in Drush.php.

- src/Commands/sql/SqlCommands.php
- src/Exec/ExecTrait.php
- src/Preflight/Preflight.php
Remapping `--db-su` to an sql config option was misguided; `--db-su` and `--db-su-pw` are ordinary command options, and should be treated as such.
The only change in this PR directly relevant to the bugfix is the deletion in src/Preflight/Preflight.php; the other changes merely make simulated mode work better with sql commands. Note that simulated mode does not help you see what is happening with `--db-su` and `--db-su-pw`, as we want to avoid echoing credentials to the terminal.
> Fixes #3997: Pass --db-su through to sql methods

- src/Commands/core/SiteInstallCommands.php
Bootstrap already works without `mysql`, but I had not yet dealt with `si` and `sql:*`. This PR takes care of `si`.
> Let site:install work with just PDO and no shell commands.

- src/Sql/SqlBase.php
There are currently situations where `sql:sync` can fail in somewhat unexpected ways. For instance, if you terminate a `sql:sync` operation during the db import it can leave behind files that break subsequent invocations.
To reproduce:
1. Simulate cruft leftover from a previous run of `sql:sync`: `touch /tmp/tmp.target.sql`
2. Try to run a sync: `drush sql-sync @foo @self --target-dump=/tmp/tmp.target.sql.gz`
3. Observe error: `Failed to import /tmp/tmp.target.sql.gz into target.`
This is easily fixed by just forcing gzip to unpack the db dump even if there's an existing copy.
This is the root cause for https://github.com/acquia/blt/issues/3279
> sql:sync shouldn't crash due to leftover files.

- .scenarios.lock/php5/composer.json
- .scenarios.lock/php5/composer.lock
- composer.json
- composer.lock
- src/Runtime/RedispatchHook.php
- src/Utils/TerminalUtils.php
When tty mode is used, the output stream provided to the Symfony Process Component / proc_open is ignored, and output goes directly to the connected terminal instead. It is therefore important for Drush to detect that output has been redirected, and avoid using tty mode in that instance.
This PR also sets the minimum acceptable version for consolidation/site-process to ^2.0.1 to pick up a related bugfix.
> Fixes #4004: Do not set tty mode if stdout is redirected.

- src/Commands/sql/SqlCommands.php
When dumping database to standard output Drush prints incomplete message because `result-file` option is not specified.
```
$ drush sql:dump > /dev/null
[success] Database dump saved to 
```
> Fix sql-dump log message

- src/Runtime/DependencyInjection.php
This allows executing drush calls via vagrant ssh -c by just using vagrant: in the site alias file. Support for this was added in site-process here: https://github.com/consolidation/site-process/pull/40
> Add vagrant transport to Drush.

- .circleci/config.yml
- docker-compose.yml
- src/Runtime/ShutdownHandler.php
- tests/functional/ShutdownAndErrorHandlerTest.php
If we get to the shutdown handler in an error state, but the status code is still zero, force it to 1.
> Fixes #4034: Ensure that status code is nonzero on invalid shutdown

- examples/example.prompt.sh
I've been using ZSH for the past week. Digging it!
For Drush 10, I think I'd like to simplify example.prompt.sh so it only provides a function that people can then call in their prompts.
> Document how to show current site alias in Zsh prompt

- src/Drupal/Commands/core/UserCommands.php
The suggested usage is invalid. If we want to use the `:` notation, it should be `user:role:add`
> Fixed usage docs for user-add-role.

- src/Drupal/Commands/config/ConfigCommands.php
I fell into that mistake that naively believed the syntax the usage hint suggested and ran this command like this:
`$ drush config:set system.site page.403 filter/tips`
When tested the results in browser, I got the regular exception from Drupal core:
> The website encountered an unexpected error. Please try again later.
> InvalidArgumentException: The user-entered string 'filter/tips' must begin with a '/', '?', or '#'. in Drupal\Core\Url::fromUserInput() (line 204 of core/lib/Drupal/Core/Url.php).
Although Drupal's GUI still lacks of consistency on how to properly request users to type in internal URL paths (with or without leading slashes), at least on the CLI side Drush could do better. Let's help future fellows not to fall again into this pitfall I learned today. Once they took the …
> Fix misleading usage examples for config:set and config:delete commands

- commands/make/make.drush.inc
This PR introduces a few improvements for converting Drush Makefiles to Composer.
- Every library is added as a `package` type to the `repository` array of Composer. This makes them ready to be installed right after running the convert command.
- The caret (`^`) is removed in front of packages. The Drush Make command always installs the exact version that is defined in the makefile, so Composer should also install this exact version.
- Instead of using `Enter {$project['name']} patch #$key description here` as a patch name, it uses the original patch name. 
- The `drupal/core` package is marked as fully incompatible, instead of only marking `8.*` incompatible. This makes sure higher versions also won't be installed in the future.
> Convert Drush Make to Composer more accurately

- src/Commands/core/UpdateDBCommands.php
- tests/functional/UpdateDBTest.php
- tests/functional/resources/modules/d8/woot/woot.install
- tests/functional/resources/modules/d8/woot/woot.post_update.php
> Reduce the useless verbosity of batch update output (#3372)

- src/Commands/config/ConfigPullCommands.php
so that it halts if the export did not report a destination path.
> Improve safety/robustness of config:pull

- src/Commands/core/UpdateDBCommands.php
Coming from https://github.com/drush-ops/drush/issues/4070 - it was noted that updatedb --entity-updates has the same problem.
> Fix updatedb --entity-updates flag in Drupal 8.7.0

- examples/example.aliases.drushrc.php
- examples/policy.drush.inc
- includes/sitealias.inc
- tests/siteAliasTest.php
On Pantheon, some organizations have many many sites - so many that the operation to generate the Drush aliases for the org can time out and fail.
For Drush 9, site alias wildcard environments can be used to greatly reduce the number of records that need to be generated, as a single record can represent any number of environments for a single site. For example:
**examplesite.site.yml**
```
'*':
host: appserver.${env-name}.8a5311d2-....pantheon.io
uri: ${env-name}-a-far-off-site-with-no-org.pantheonsite.io
user: ${env-name}.8a5311d2-....
ssh:
options: '-p 2222 -o "AddressFamily inet"'
tty: false
```
If this alias is accessed via `drush @examplesite.foobar status`, then all occurrences of `${env-name}` will be replaced with `foobar`. If there is, in fact, an environment named `foobar`, then …
> Support wildcard aliases for Drush 8

- README.md
Added info about GitHub's 'Releases only' watch option and removed old Version Eye link.
> Updated subscription options in README.md

- docs/install.md
We still need to make some decisions about compatibility for Drush 10. Here is a visual representation of what that might look like. Subject to change.
For example, consolidation/site-process still needs some minor changes to work with symfony/process 4+. We will probably want to have different major versions of consolidation/site-process for symfony/process -3 vs 4+. It is still speculative whether this will pose any issues for Drush.
> Fixes #3845: Speculative Drush 10 compatibility

- src/Commands/core/UpdateDBCommands.php
- tests/functional/UpdateDBTest.php
- tests/functional/resources/modules/d8/woot/woot.install
- tests/functional/resources/modules/d8/woot/woot.module
- tests/functional/resources/modules/d8/woot/woot.post_update.php
If an entity type is provided by a module being installed via a (post)update hook. The next Drush command will fail to recognize the new installed definition, unless a cache rebuild is run just after `updatedb`. For example, with this hook:
```php
function woot_post_update_install_taxonomy()
{
\Drupal::service('module_installer')->install(['taxonomy']);
return \Drupal::entityTypeManager()->getDefinition('taxonomy_term')->id();
}
```
When running:
```bash
$ drush updb --yes
```
This will end successfully and will return `taxonomy_term`, but if I run immediately:
```bash
$ drush eval 'print \Drupal::entityTypeManager()->getDefinition("taxonomy_term")->id();'
```
...will output:
```
In EntityTypeManager.php line 150:
The "taxonomy_term" entity type does not exist.
```
The bug is reproduced …
> Entity type provided by a module installed via update hook not available

- .circleci/patch.sh
- appveyor.yml
- composer.json
- composer.lock
This is necessary to ensure that we get the fix required for Drupal 8.8.x development.
> Constrain our minimum version of webflo/drupal-finder to 1.2 or later

- commands/sql/sql.drush.inc
Before this commit, Drush threw
"ArgumentCountError: Too few arguments to function Drush\Sql\SqlBase::__construct()"
To reproduce, do `/var/www/drupal7-site/vendor/bin/drush --root=/path/drupal8-site`
Fixes #3047
> Better UX in case of mixing Drupal 7 sources with Drupal 8 root

- src/Boot/DrupalBoot8.php
- tests/functional/CoreTest.php
- The Symfony request object had an incorrect base URL when using the --uri option
with a subdirectory.
- Added tests for the url check.
Closes #4135
> Issue #4135 Fix Request to have correct base URL

- src/Drupal/Commands/core/DrupalCommands.php
Currently, when you run cron and it is already running, it throws an exception saying Cron run failed.
This PR removes the exception throw when the cron call returns false. Checking Drupal - it will only ever return false if the cron is already running, and a warning will have already been logged. This ensures that cron installations of `drush cron --uri=<uri> --quiet` do not randomly fail
> [cron] Do not throw exception if cron is already running

- src/Sql/SqlMysql.php
Hello, i've asked for this feature some time ago in #4158 and finally had the time to add it. 
It would leave an empty line if no socket is set but that shouldn't be a big issue as the file is temporary anyways. Would be nice to have this feature in Drush in order to be able to run MySQL commands on setups with socket connections.
If you merge it, thanks in advance.
> add unix socket configuration to mysql credentials

- tests/functional/PmEnDisUnListInfoTest.php
Since classy is no longer the default testing theme, the Unish\EnDisUnListInfoCase::testEnDisUnList is currently failing.
This test is checking if classy is installed. Since classy is no longer the default testing theme, the test will nog longer find classy in the installed modules/themes list.
Issue: https://www.drupal.org/project/drupal/issues/2352949#comment-13252667
CR: https://www.drupal.org/node/3083055
> Replace classy with stark in EnDisUnListInfoCase::testEnDisUnList

- src/Drupal/Commands/sql/SanitizeUserFieldsCommands.php
As described in https://github.com/drush-ops/drush/issues/3636 drush sql-sanitize fails sometimes, because it generates sample values for all fields.
This PR adds a check, to generate the sample value only, when the field type is supported.
> Issue-3636: Generate sample values only for supported field types.

- src/Drupal/Commands/core/EntityCommands.php
Following up on https://drupal.stackexchange.com/q/285037 and since I found myself already in a situation to need to delete every node *except* some very certain ones, I added an `--exclude` option to the `entity:delete` command.
Is it OK how it's written? Is it right to have the `$options` parameter array extended to also take `'exclude' => self::REQ` with `self::REQ`? I just followed the `'bundle' => self::REQ` pattern.
Finally everything else I added are the following few lines after the `$entities` are already loaded.
```php
// Don't delete excluded entities.
if ($exclude = StringUtils::csvToArray($options['exclude'])) {
foreach ($exclude as $id) {
unset($entities[$id]);
}
}
```
Is there anything else I need to consider when adding this option? Do I need to extend existing tests for …
> Add option to exclude entities by ID to entity:delete command.

- includes/drush.inc
Fixes drush_memory_limit to give correct value if memory limit is strictly numeric
> Calculate memory_limit correctly when there is no suffix

- src/Commands/sql/SqlSyncCommands.php
Tested with
- `drush sql-sync @remote-site-alias @self`
- `drush -y sql-sync @remote-site-alias @self`
This fixes the problem described in #4071 run inside the Alpine container.
Please advice if this needs to be somewhere else.
> Closes #4071 by setting -y to sql-sync command

- src/Commands/config/ConfigImportCommands.php
- src/Drupal/Commands/config/ConfigImportCommands.php
The `--partial` is equivalent to a single import in the UI. Config transformations are not applied in that case. So we should also skip them in the drush import.
This bug exists because of a core bug with `StorageReplaceDataWrapper` which "forgets" the replaced data when the collection is switched.
> Fix config import with `--partial`

- composer.json
- composer.lock
- sut/modules/unish/drush_empty_module/drush_empty_module.info.yml
- sut/modules/unish/drush_empty_module/drush_empty_module.install
- sut/modules/unish/drush_empty_module/drush_empty_module.routing.yml
- sut/modules/unish/drush_empty_module/drush_empty_module.services.yml
- sut/modules/unish/drush_empty_module/src/MuchControllerManyWow.php
- sut/modules/unish/drush_empty_module/src/MuchServiceManyWow.php
- sut/themes/unish/drush_empty_theme/drush_empty_theme.info.yml
- tests/functional/ConfigTest.php
- tests/functional/LanguageAddTest.php
- tests/functional/LocaleTest.php
- tests/functional/PmEnDisUnListInfoTest.php
- tests/functional/PmEnLocaleImportTest.php
- tests/functional/UpdateDBTest.php
- tests/functional/resources/drush_empty_module.nl.po
- tests/functional/resources/drush_empty_module.post_update.php
- tests/functional/resources/modules/d8/woot/src/DependingService.php
- tests/functional/resources/modules/d8/woot/woot.post_update.php
- tests/functional/resources/updatedb_script.php
- tests/integration/CoreTest.php
Removes test dependency on devel and empty_theme by adding mock module and themes for the same purposes
I tried to remove the dependency on `drupal/alink` too, but unfortunately SecurityUpdatesTest expects to find an insecure module in composer.lock.
I don't know if that can be gotten around.
> Remove test dependency on devel/empty_theme

- docs/commands.md
This pull request is in favor of drush-ops/drush#4290, which adds some information about symlinked composer packaged commands. I've created a new heading for this part since it is information that addresses all other headlines so I didn't really know where to put it but here. Everyone okay with that?
> Adding extra information about symlinked packaged commands

- includes/legacy.inc
- src/Commands/core/SiteInstallCommands.php
- src/Drupal/Commands/config/ConfigCommands.php
- src/Drupal/Commands/config/ConfigExportCommands.php
- src/Drupal/Commands/config/ConfigImportCommands.php
> Fix #4293. Stop using CONFIG_ACTIVE_DIRECTORY and especially CONFIG_SYNC_DIRECTORY.

- src/Sql/SqlMysql.php
Now consistent with https://github.com/drush-ops/drush/commit/9b11884c12449c2413fd154b0bffe7d06d0c3797 and https://github.com/drush-ops/drush/pull/3998. 
This may cause some backward compat issues but its a bug fix. No backport for that reason.
> Fix #4098. Stop using sql.db-su.

- .circleci/config.yml
- src/Drupal/Commands/pm/PmCommands.php
- src/Drupal/Commands/pm/drush.services.yml
- sut/themes/unish/drush_empty_theme/drush_empty_theme.info.yml
- tests/unish/UnishTestCase.php
> Add missing base theme key and remove system_rebuild_module_data().

- src/Preflight/RedispatchToSiteLocal.php
Escape the command name in RedispatchToSiteLocal, making it possible to use a globally installed drush from a Drupal directory with a name containing spaces.
Fuller description of the issue in https://github.com/drush-ops/drush/issues/4306.
> Escape command name in RedispatchToSiteLocal.

- composer.json
- composer.lock
- src/Commands/pm/SecurityUpdateCommands.php
- sut/themes/unish/drush_empty_theme/drush_empty_theme.info.yml
- tests/integration/SecurityUpdatesTest.php
```
./drush pm:security-php                                                                                    
[warning] One or more of your dependencies has an outstanding security update.
[notice] Try running: composer why david-garcia/phpwhois to learn what  module requires the package.
david-garcia/phpwhois:
version: 4.3.0
advisories:
-
title: 'PHP Code Injection'
link: 'https://github.com/sbaresearch/advisories/tree/public/2018/SBA-ADV-20180425-01_phpWhois_Code_Execution'
cve: CVE-2015-5243
```
Uploads a site's composer.lock to https://security.symfony.com/ and returns any found vulnerabilities in YAML format (by default). An exit code of 1 is returned in this case.
Requires `curl` to be available and on your PATH.
Our long standing pm:security command which checks Drupal packages …
> Add pm:security-php command for checking PHP dependencies for vulnerabilities

- src/Commands/config/ConfigImportCommands.php
- tests/functional/ConfigTest.php
- tests/functional/resources/modules/d8/woot/src/EventSubscriber/ConfigSubscriber.php
This removes the usage of UpdateKernel from the `config:import` command and thereby fixes #4350.
I expected to see an error in 'testConfigImport', but all tests pass (after fixing another minor test issue).
It also looks like the config validation event was not invoked anymore - that is now also fixed and being checked on in the test.
To showcase that this test would be failing without this change, please see #4369 .
> Don't use the UpdateKernel for config:import.

- docs/deploy.md
- src/Commands/core/DeployCommands.php
Needed if there were no db updates.
> Add cache clear to early part of deploy.

- src/Drush.php
- src/Log/DrushLog.php
> Avoid logging during web requests.

- commands/core/rsync.core.inc
- commands/make/generate.make.inc
- commands/pm/info.pm.inc
- includes/command.inc
- includes/sitealias.inc
- Curly brace syntax for accessing array elements and string offsets has been deprecated in PHP 7.4
- Passing the $glue and $pieces parameters in reverse order to implode has been deprecated since PHP 7.4; $glue should be the first parameter and $pieces the second
> Drush 8 - PHP 7.4: Fix deprecation notices

- src/Commands/pm/SecurityUpdateCommands.php
- tests/integration/SecurityUpdatesTest.php
Fixes https://github.com/drush-ops/drush/issues/4366.
Unfortunately, it does not seem possible to use a single `composer why` call for multiple packages.
> Display "composer why" suggestion for every package

- lib/Drush/User/UserSingleBase.php
Use drush_backend_batch_process() instead of batch_process() in user:cancel.
This should have broken 100% of the time, but instead it decided to break 0% of the time for years, until it started breaking only most of the time, but only when used with a site set up via Behat. Go figure.
> Fix user:cancel

- .circleci/config.yml
- tests/integration/SecurityUpdatesTest.php
Replace alinks once there is a contrib module release that is both D9 compatible and insecure.
> alinks has no D9 release

- src/Commands/pm/SecurityUpdateCommands.php
Provides a simple message on success instead of silently ending.
Wording and logging level copied form the Drupal version of the method.
> Notify success checking php security updates

- composer.json
- composer.lock
- src/Commands/generate/GenerateCommands.php
DCG determines available Twig version by checking `\Twig\Environment::VERSION` constant in bootstrap script. However given that the script is loaded very early in some edge cases it may cause problems because accessing class constant triggers Composer autoloader.
https://github.com/Chi-teck/drupal-code-generator/issues/46
https://github.com/Chi-teck/drupal-code-generator/issues/47
The proposed solution is checking Twig version right before the instantiation Twig environment.
> Create Twig environment explicitly

- src/Drupal/Commands/core/TwigCommands.php
Loading the template ensures the compiled template is cached. It is not necessary to also render it.
drush-ops/drush#1969
> Replace twig_render_template() with \Drupal::service('twig')->loadTemplate()

- src/Drupal/Commands/core/CliCommands.php
- src/Drupal/Commands/sql/SanitizeCommands.php
- src/Drupal/Commands/sql/SanitizeUserFieldsCommands.php
Following up on https://www.drupal.org/project/ideas/issues/3159647#comment-13755051 let's fix this now.
This PR replaces blacklist which only had one occurrence in a comment. And it deprecates whitelist which only appeared in an option to the `sql:sanitize` command.
> Replace blacklist/whitelist with blocklist/allowlist

- src/Commands/core/UpdateDBCommands.php
This PR fixes 3 problems:
1. Currently post update hooks appear successful if placed in my_module.install, but are not actually invoked
2. If you put your update or post update function in the wrong file, it would be helpful to tell you what the right file is
3. Post-update processing should use Drupal::moduleHandler()->loadInclude not module_load_include(), as update processing already does.
> Better error handling for update functions in wrong files 

- src/Commands/DrushCommands.php
- src/Commands/core/DocsCommands.php
- src/Commands/core/MkCommands.php
I would like to hyperlink the topics on the new Commands web pages. For example, see 3 topics at bottom of https://www.drush.org/commands/10.x/config_pull/.
This PR adds a value to one `@topic` with a relative link to the file. The mk:docs command can programmatically use that value to build the hyperlink.
This PR duplicates the path `../../../README.md` in the body of the command method. Ideally it would use the value from its own annotation. However I do not see a way in a command method to learn what the current command name is. If I could do that, I would get load a $command object and fetch the annotationData. Hooks get the command info as a param but the command method does not.
This PR will change more methods once the above question is settled.
> @topic annotation can be a relative path to a file

- src/Commands/OptionsCommands.php
- src/Commands/config/ConfigPullCommands.php
- src/Commands/core/BrowseCommands.php
- src/Commands/core/CacheCommands.php
- src/Commands/core/DrupalDirectoryCommands.php
- src/Commands/core/MkCommands.php
- src/Commands/core/RunserverCommands.php
- src/Commands/help/HelpCLIFormatter.php
- src/Drupal/Commands/config/ConfigCommands.php
- src/Drupal/Commands/config/ConfigExportCommands.php
Apparently its been gone for 3 years.
Also better help formatting on several commands.
> Bring back printing of an argument default in Help. Also change <info> to italic on Commands site

- includes/sitealias.inc
Drush sql-sync will add a "--root" option to the backend invoke call that fetches the database information. If the site alias record does not define a "root" path, then Drush will use the path to the root of the locally-bootstrapped Drupal site. This will not produce the correct results, because the local root path is usually meaningless on the remote server.
This commit fixes this bug. This bug has already been fixed in Drush 9 and Drush 10.
> Do not pass --root in sql-sync if it is not set in the alias file.

- commands/user/user.drush.inc
- includes/backend.inc
Drush 10 does not support backend invoke, which causes problems for Drush uli when a local Drush 8 is trying to get a login link from a remote site with Drush 10.
This PR adds a mode to backend invoke which will convert the output of a remote command from any app into a backend invoke record. The uli command then uses this flag to allow Drush 8 uli to work on Drush 10 targets.
> Allow Drush 8 uli to call Drush 10 and get the right reset link.

- src/Preflight/PreflightVerify.php
See #4411. Note that Process already checks for proc_open() availability https://github.com/symfony/process/blob/2cf3f1373f84bdd33a3dfb1fb99eaa29371859af/Process.php#L142-L144
> Fix #4411. Remove preflight checks for disable_functions and disable_classes

- src/Utils/FsUtils.php
Pantheon is rolling out new "Container-Optimized Environments" (COE). Most existing bindings and all new sites are one COE. This new environment puts $HOME at `/`, and of course `/` is unwritable. This causes problems with Drush sql:sync, which by default wants to put the dump file in the backup directory. The Drush backup directory is at $HOME/drush-backups, which is not writable under COE.
This PR makes the backup dir configurable, just as it was in Drush 8.
> Allow the backup dir parent to be set in config.

- examples/example.drush.yml
- src/Utils/FsUtils.php
The drush backup-dir configuration setting should have been drush.paths.backup-dir, for consistency.
Also added some documentation.
> Fix the backup-dir configuration setting

- docs/install.md
Removes 'Drush brach' column since thats obvious now with master being dropped in favor of 10.x. Also removed Drupal 6 column as its way past EOL and I'd rather show the table without horiz scrolling.
> Narrow the drush-drupal compat table to avoid horizontal scrolling

- includes/backend.inc
This is a backport fix for the 8.x branch. See #3472 and #3469.
> Remove deprecated each().

- src/Commands/core/DeployCommands.php
We can't use /dev/null as a value because it fails the candidate check `$fs->mkdir($candidate)` in \Drush\Config\DrushConfig::cache. A temp dir works just as well.
> Change how we NULL the cache dir during deploy command.

- src/Commands/core/XhprofCommands.php
- tests/unit/XhProfTest.php
- flags could be checked for both extensions
- added mapping for settings (could be extended for blackfire)
- cleaned docs about xhprof pecl
Ref https://github.com/tideways/php-xhprof-extension/blob/master/tideways_xhprof.c#L59
> Document and clean-up xhprof

- src/Commands/core/CacheCommands.php
- src/Commands/core/DeployCommands.php
Yet another attempt to deal with #3592. This accepts the race condition and simply converts the Exception into a notice. Its pragmatic, having dealt with this for years.
> Avoid exception when clearing Drush’s own cache files

- lib/Drush/Sql/Sqlmysql.php
Backports #4364 to 8.x (Fixes #4318)
See also my comments here: https://github.com/drush-ops/drush/issues/4259#issuecomment-690810648
> Fix SQL user creation with MariaDB (#4364)

- commands/runserver/d7-rs-router.php
- tests/makefiles/lockfiles/git.lock.yml
In Panopoly's automated tests, we've been pinned to Drush 8.0.* for years, because using Drush 8.1.* or newer had some mysterious issues with Panels, that I've finally gotten around to figuring out. :-)
This is important for us now, because we need to update to Drush 8.4.* in order to run our tests on PHP 7.4.
Anyway, the bug is that `drush runserver` won't decode the URL paths the same way that Apache and nginx does. This affects some Panels AJAX URLs, for example, with this URL from my local test site:
http://127.0.0.1:55432/panels/ajax/ipe/save_form/panel_context%3Apage-panopoly_demo_panel%3A%3Apage_panopoly_demo_panel_panel_context%3A%3A%3A%3A?destination=demo
When the AJAX request for the URL goes through Apache or nginx, then `panels_ajax_router()` (a page callback) will get its 3rd …
> drush runserver with Drush >= 8.1.* and Drupal 7: doesn't decode URL paths the same as Apache or nginx would

- includes/batch.inc
**Describe the bug**
Running drush on PHP 8 throws a deprecation warning.
**To Reproduce**
Run `drush en -y pathauto` (or any module). I suppose it would happen with other commands as well.
**Expected behavior**
No warnings
**Actual behavior**
Couple of deprecation warnings.
```
Deprecated: Required parameter $args follows optional parameter $command in /var/www/html/vendor/drush/drush/includes/batch.inc on line 116
Deprecated: Required parameter $options follows optional parameter $command in /var/www/html/vendor/drush/drush/includes/batch.inc on line 116
```
**Workaround**
I suppose suppressing error messages would do the job (or change `error_reporting` in php.ini).
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.4
| Drupal version? | 9.1.x-dev
| PHP version …
> Fix PHP 8 deprecation with required parameters

- src/Drupal/Commands/config/ConfigCommands.php
- src/Drupal/Commands/config/drush.services.yml
in #4194 we added a export transformation to compare with a given storage.
We should have instead transformed that storage for import to do the comparison.
> Transform the storage to import instead of the active one for export

- src/Commands/DrushCommands.php
- src/Commands/pm/SecurityUpdateCommands.php
- tests/integration/SecurityUpdatesTest.php
- tests/unish/UnishTestCase.php
We have duplicated exit code constants due to our legacy of Unish being quite separate from Drush. Seems like we could get rid of that one day.
> Fix #4544. Use exit code 3 when insecure packages are found in security commands

- composer.json
- composer.lock
Drupal 8 does not require symfony/finder, so it's common for Drupal sites that pull in this requirement from somewhere else to float to symfony/finder ^5. This causes friction in installing Drush afterwards.
This PR allows symfony/finder ^5. I recently updated Robo ^1, annotated-commands ^2 and output-formatters ^3 so that this would be possible. Note that we still get symfony/finder ^4 in the lock file due to our platform php configuration; however, our PHP 7.2 test should pull in symfony/finder ^5.
> Allow Symfony Finder ^5

- src/Drupal/Commands/core/EntityCommands.php
When deleting lots of entities at once (+1000). It seems that the command hangs. I changed the command to process the deletions in small steps and added a progress bar to the output to inform the user.
> entity:delete -> execute deletion of entities in small steps to avoid loading all at once

- src/Boot/DrupalBoot8.php
> Fixed app root detected by Drush not getting passed to the Drupal kernel

- src/Drupal/Commands/core/CliCommands.php
I think this would make more clear to users that PHP shell is running within Drupal context.
> Add site name and Drupal version to php:cli startup message

- src/Drupal/Commands/config/ConfigImportCommands.php
> Fix #4614. TypeError on Drupal 9.2.x with EventDispatcherInterface

- src/TestTraits/CliTestTrait.php
Issue #4620 - Support both array and string $command in symfony/process
> Issue #4620 - Support both array and string $command in symfony/process

- src/Application.php
- src/Commands/sql/SqlCommands.php
A minimalist implementation of #4649. I think we'll do Collision exceptions in Drush 11.
> Fixes #4038. More verbose sql exceptions and omit command  signature at end

- src/Commands/core/UpdateDBCommands.php
> Batch operation on updateDB doesn't set correct installed schema version if sandbox['#finished'] is > 1

- includes/drush.inc
Drush (`site-install` to be more precise) was failing when used with an old Drupal 7 site. 
Some of the modules used in that site still use curly braces to access array elements and this is deprecated since PHP 7.4. The deprecation error messages got captured by drupal and, since there was no specific rule for such error messages, drush was logging them as errors, resulting in an exit code of 1.
While very useful, messages about deprecated features should be treated more like warnings instead of errors, as the application will work fine even though it uses a feature that won't be available in the future.
To avoid that, we now check for any messages starting with "deprecated function:" and log them as warnings instead of errors.
> Consider deprecation error messages as warnings instead of errors

- src/Boot/DrupalBoot8.php
Thanks for the report. 
The ultimate error isn't easy to improve as Symfony Console is throwing the Exception about command not found and we'd have to override a lot to take control and report back the SQL error.
This PR enhances the debug log message to show the actual connection error.
`drush status` tells you Bootstrap Successful when all is OK and tells you nothing when it isn't. I think we should say Unsuccessful in that case. Might need a major version to change this unfortunately.
> Fix #4671. Show DB connection error details during bootstrap.

- src/Config/Environment.php
Hopefully this fixes both issues linked in the title, and removes a bit of custom code. See https://github.com/symfony/console/blob/5.x/Terminal.php#L25-L37
> Fix #4043,#3843 - Use Symfony Console to determine terminal width.

- src/Drupal/Commands/sql/SanitizeCommands.php
According to the `SanitizePluginInterface`, I think the help text on the `sql:sanitize` command should reference the `sql-sanitize-confirms` event and not `sql-sanitize-message`.
https://github.com/drush-ops/drush/blob/69ccd328836dde979dcbbeea8ca40ab0b336515f/src/Drupal/Commands/sql/SanitizePluginInterface.php#L24
> Update sql:sanitize help text to use sql-sanitize-confirms event

- src/Drupal/Commands/config/ConfigCommands.php
If you use the config_ignore module, and inadvertently have ignored config in your sync directory, `drush config-import --preview=diff' will fail with a nondescript type error when the source can't be found. This outputs a more helpful message.
> Fix error from diff preview against ignored config.

- lib/Drush/Boot/DrupalBoot.php
`getenv` will work in some environments, but not in all environments.
> Check for PRESSFLOW_SETTINGS the same way that Pressflow does.

- composer.json
- docs/commands.md
- docs/generators.md
- src/Application.php
- src/Commands/generate/GenerateCommands.php
- src/Runtime/Runtime.php
- tests/fixtures/lib/Drush/Commands/CustomDrushCommands.php
- tests/fixtures/lib/Drush/Generators/CustomGenerator.php
- tests/integration/CustomLibraryCommandsAndGeneratorsTest.php
- tests/integration/CustomLibraryCommandsTest.php
- tests/unish/Controllers/RuntimeController.php
True, there is a way to discover such commands by adding their paths in Drush configuration. But I want to be able to have such commands available automatically, when I `composer require` a 3rd party library Drush commands provider.
This PR uses the Robo `RelativeNamespaceDiscovery` to grab the Drush commands living in 3rd party libraries, loadable via PSR4. Such a class should comply with the following requirements:
* The commands class namespace ends with `*\Drush\Commands`, e.g. `My\Custom\Library\Drush\Commands`.
* The class and file name ends with `*DrushCommands`, e.g. `FooDrushCommands`.
> Auto-discover non-Drupal commands

- src/Drupal/Commands/pm/PmCommands.php
- tests/functional/PmEnDisUnListInfoTest.php
We have a need to get information about modules in a Drupal site. We're using a remote call, and the target might be running various versions of Drupal + Drush. We'd like to know which project a module is associated with, and since pm:info no longer exists in current versions of Drush, and whereas the project information is readily available in the extension information, this seemed like a low-impact solution that is generally useful.
Note that the default fields do not change in this PR, so the default output does not change either (you only get `project` if you request it via `--fields`).
> Add "project" to pm:list

- commands/core/views.d8.drush.inc
- commands/pm/pm.drush.inc
- tests/pmEnDisUnListInfoTest.php
This is a backport of #4694 for Drush 8.
Also adds 'display_name' and 'path' to the `pm:list` output for forward compatibility. The `name` field remains as-is in Drush 8 for compatibility, so the `name` field is different between Drush 8 (where it is the display name) and Drush 9+ (where it is the machine name). In json output mode, the key is the machine name in both Drush 8 and Drush 9+, though.
Also fixes a typo in the views command definition.
> Add "project" to pm:list (Drush 8 backport)

- examples/example.drush.yml
- src/Commands/core/XhprofCommands.php
- tests/unit/XhProfTest.php
Defaults for `xh` config is missing but `\Drush\Commands\core\XhprofCommands::xhprofFlags()` expects array as argument
It prevents to fail command as #4704
> Provide global defaults for profiler

- docs/bootstrap.md
- docs/site-alias-manager.md
- docs/site-aliases.md
- docs/usage.md
- docs/using-drush-configuration.md
- examples/example.drush.yml
- examples/example.site.yml
- mkdocs_base.yml
- src/Commands/OptionsCommands.php
- src/Commands/core/DocsCommands.php
- src/Commands/core/RsyncCommands.php
- src/Commands/core/SiteCommands.php
- src/Commands/sql/SqlCommands.php
Markdown is more readable with hyperlinks, formatting, etc. The old pages are left behind in a minimal state with a link to the web. If we get rid of `drush init` in drush 11, we can probably get rid of these 2 example files.
> Move example.drush.yml and example.site.yml content to a markdown

- examples/example.drush.yml
This broke acli https://github.com/acquia/cli/issues/508
> Re-add global paths in example.drush.yml

- src/Commands/sql/SqlSyncCommands.php
Was omitted accidentally in https://github.com/drush-ops/drush/issues/3512
> Add --extra-dump default value in sql:sync

- src/Drupal/Commands/pm/PmCommands.php
- src/Drupal/Commands/pm/drush.services.yml
- sut/modules/unish/drush_empty_module/drush_empty_module.install
- tests/functional/PmEnDisUnListInfoTest.php
This resolves #4190 and supersedes the #4337 PR to include functional tests as well as read all requirement errors.
> Run hook_requirements() on pm:enable

- lib/Drush/UpdateService/Project.php
I'm sure there are more elegant ways of fixing the problem, but this seems to get the pm: commands working again in PHP 8.0
> Workaround for array vs SimpleXMLElement in PHP 8 (#4762)

- README.md
On https://github.com/drush-ops/drush/tree/8.x
the readme link for "Installing (and Upgrading)" goes to https://docs.drush.org/en/master/install/ which does not work as intended.
Link should go to http://docs.drush.org/en/8.x/install/
> Fix install link for drush 8.

- src/Commands/pm/SecurityUpdateCommands.php
- tests/integration/SecurityUpdatesTest.php
We use `drush sec` and `drush sec-php` to check for vulnerabilities on our websites automatically, but we don't want to be notified for vulnerabilities in development dependencies because these are never installed on the server.
> New no-dev option for security commands

- src/Drupal/Commands/config/ConfigCommands.php
Relates issue #4769. 
I've added a new usage, very useful for CI checks, when you want to validate there are no differences between the database and the exported configuration
> Improve documentation for config status over stdout

- src/Drupal/Commands/core/WatchdogCommands.php
- src/TestTraits/CliTestTrait.php
- tests/functional/WatchdogTailTest.php
- tests/unish/CommandUnishTestCase.php
WIP, feedback welcome.
Only tested with `composer functional -- --filter testWatchdogTail`.
> Add a watchdog tail command

- src/Drupal/Commands/core/MigrateRunnerCommands.php
- src/Drupal/Migrate/MigrateExecutable.php
- tests/functional/MigrateRunnerTest.php
Fixes #4750 
Original PR: #4751
> Fix handling of missing source rows in migrate:import

- src/Preflight/ArgsPreprocessor.php
An empty arg such as `/drush cset system.site name ""` was giving a notice.
> Avoid notice for empty arg.

- src/Drupal/Commands/core/RoleCommands.php
The `role:perm:add --help` text has an example of listing permissions with `pm:info`. This doesn't work anymore and should probably be removed or updated. This PR just removes it.
> Remove pm:info usage example from role:perm:add annotation

- src/Drupal/Commands/core/MigrateRunnerCommands.php
Seems to come from migrate:status. Adjusted to describe the actual use.
> Improve documentation on migrate:fields-source return value

- docs/migrate.md
migrate_tools runs migrations, independently of where they were originally set, i.e. using migrate configuration entities is not a requisite to use migrate_tools.
> Remove a non-relevant sentence from migrate documentation

- src/Drupal/Commands/core/DeployHookCommands.php
- src/Drupal/Commands/core/drush.services.yml
- tests/functional/DeployHookTest.php
The original deploy:hook implementation passed the $sandbox variable to the deploy hooks to have the same signature as the post_update hooks. But we faked the batch process. However after using this for a while we found that it is necessary to do the batching in order to reduce the memory consumption that is unavoidable due to lots of static caches not being able to be cleared.
> Update deploy:hook command to use batch system

- src/Commands/core/UpdateDBCommands.php
drush updb -y --quiet did not run update hooks
closes #4805
> Fix running drush update:database with quiet option

- src/Drupal/Commands/core/MigrateRunnerCommands.php
**Describe the bug**
`migrate:stop`, `migrate:messages` and `migrate:fields-source` are not handling the case when an invalid migrate name is passed.
**To Reproduce**
Try `vendor/bin/drush migrate:stop unexisting_migration`
Change it for `migrate:messages` and `migrate:fields-source` to get similar results.
**Expected behavior**
An error message is presented.
**Actual behavior**
An unhandled error is reached, triggering a php fatal error.
**Workaround**
No.
| Q               | A
| --------------- | ---
| Drush version?  | 10.x e436955b5556113dda0af8a3c4225f0b209ed329
| Drupal version? | 9.x
| PHP version     | 7.3
| OS?             | Linux
**Additional information**
Add any other context about the problem here.
Here the full output I get without the extra change on this pull request.
$ …
> Validate migration IDs

- composer.json
- composer.lock
- src/Drush.php
- src/Runtime/DependencyInjection.php
Going to take a swing at #4812. First, though, let's run the tests with latest dependencies and no other changes to see if maybe #4813 is related to the new Annotated Command library release.
> Fixes #4812: Support Robo 3 while maintaining compatibility with Robo 2 and Robo 1.

- src/Drupal/Commands/config/ConfigCommands.php
Escape the ampersand in the documentation text for config:status.
drush-ops#4827
> Escape ampersand in doc text for config:status

- src/Commands/core/PhpCommands.php
The `php:eval` examples in the `@usage` section were still geared to Drupal 7. 
This pull request updates them to be successful with Drupal 9.2.5
I do get a warning about the format description option not being provided to `HelpCLIFormatter.php` but I believe that is just a relic of how I am set up locally.
> Updating to usable php help examples.

- src/Drupal/Commands/core/MigrateRunnerCommands.php
- tests/functional/MigrateRunnerTest.php
> The system_migrate_prepare_row() hook implementation not picked-up

- docs/install.md
I propose we EOL Drush 8 [in concert with Drupal 8](https://www.drupal.org/psa-2021-2021-06-29), which is Nov 2, 2021. ﻿We might still accept bug fixes after that date, but the diligence level goes down. 
I also propose an EOL for Drush 10 at same time, and asking folks to upgrade to a nearly identical Drush 11.
This gets us to just 1 supported version of Drush :1st_place_medal:
> Add EOL dates for Drush 8 and Drush 10

- src/internal-forks/Config/Yaml/Inline.php
One more fix for 10.x after  https://github.com/drush-ops/drush/pull/4840
It also needs https://github.com/consolidation/site-alias/pull/44
PS: 8.x branch is different https://github.com/drush-ops/drush/pull/4839
> Fix PHP 8.1 - allow empty yaml

- .circleci/config.yml
This will move us to PHP 8.1 as soon as it is released, and so on. I think that’s the best option given what I see at https://github.com/wodby/php#docker-images /cc @andypost
> Always use latest PHP release in CI for tip test

- commands/core/config.drush.inc
- includes/batch.inc
- includes/command.inc
The only notice I get using 8.4.8 with PHP 8.1rc2
```
$ drush st
PHP Deprecated:  Return type of DrushBatchContext::offsetSet($name, $value) should either be compatible with ArrayObject::offsetSet(mixed $key, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/drush/includes/batch.inc on line 39
Deprecated: Return type of DrushBatchContext::offsetSet($name, $value) should either be compatible with ArrayObject::offsetSet(mixed $key, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/bin/drush/includes/batch.inc on line 39
Drupal version         :  9.3.0-dev             
...
Drush version          :  8.4.8  
```
> Fix PHP 8.1 compatibility for drush 8.x

- src/Drupal/Commands/core/LanguageCommands.php
This is a minor fix to the help text for the skip-translations option of the language:add command that @enid-h-williams found while helping with copy editing content for Drupalize.Me.
> Copy edit help text for language:add

- CONTRIBUTING.md
You mentioned the `composer cs` script in https://github.com/drush-ops/drush/pull/4853, but I don't see it documented anywhere. Now it's documented in CONTRIBUTING.md.
> Mention PHP_CodeSniffer in CONTRIBUTING.md

- composer.json
> psysh 0.11 does not work with Drush 10

- src/Application.php
Otherwise we run into warnings when `drush` is run with no commands:
```shell
$ drush
[warning] Undefined array key 1 Application.php:199
(...)
```
Closes: https://github.com/drush-ops/drush/issues/4887
> Check for runtime.argv array size before use (#4887)

- src/Drupal/Commands/core/AskBundleTrait.php
- src/Drupal/Commands/core/FieldDefinitionRowsOfFieldsTrait.php
- src/Drupal/Commands/core/FieldInfoCommands.php
- src/Drupal/Commands/core/ValidateEntityTypeTrait.php
- src/Drupal/Commands/core/drush.services.yml
- tests/functional/FieldCreateTest.php
- tests/functional/FieldTest.php
This PR adds a command to show information about fields, similar to the [field-info command that was present in Drush 8](https://drushcommands.com/drush-8x/field/field-info/). It has already been used in multiple projects as part of the [wmscaffold module](https://github.com/wieni/wmscaffold) and is in my opinion stable enough to be considered to be merged in Drush.
- `AskBundleTrait` and `ValidateEntityTypeTrait` are also included in https://github.com/drush-ops/drush/pull/4926, https://github.com/drush-ops/drush/pull/4929 and https://github.com/drush-ops/drush/pull/4930. 
- `FieldDefinitionRowsOfFieldsTrait` is also included in https://github.com/drush-ops/drush/pull/4930.
- `./vendor/bin/drush fi` => _Not enough arguments (missing: "entityType")._
- `./vendor/bin/drush fi node` => Asks …
> Add field:info command

- src/Drupal/Commands/core/EntityTypeBundleAskTrait.php
- src/Drupal/Commands/core/EntityTypeBundleValidationTrait.php
- src/Drupal/Commands/core/FieldCreateCommands.php
- src/Drupal/Commands/core/FieldDeleteCommands.php
- src/Drupal/Commands/core/FieldInfoCommands.php
- src/Drupal/Commands/core/drush.services.yml
- tests/functional/FieldCreateTest.php
This PR adds a command to delete fields, similar to the [field-delete command that was present in Drush 8](https://drushcommands.com/drush-8x/field/field-delete/). It has already been used in multiple projects as part of the [wmscaffold module](https://github.com/wieni/wmscaffold) and is in my opinion stable enough to be considered to be merged in Drush.
- `AskBundleTrait` and `ValidateEntityTypeTrait` are also included in https://github.com/drush-ops/drush/pull/4928, https://github.com/drush-ops/drush/pull/4929 and https://github.com/drush-ops/drush/pull/4930. 
- `./vendor/bin/drush fd` => _Not enough arguments (missing: "entityType")._
- `./vendor/bin/drush fd node` => Asks for bundle
- `./vendor/bin/drush fd node --no-interaction` => _The bundle argument is required._
- …
> Add field:delete command

- src/Drupal/Commands/core/BaseFieldInfoCommands.php
- src/Drupal/Commands/core/FieldBaseInfoCommands.php
- src/Drupal/Commands/core/FieldInfoCommands.php
- src/Drupal/Commands/core/drush.services.yml
- tests/functional/FieldTest.php
This PR adds a command to show information about base fields, similar to https://github.com/drush-ops/drush/pull/4928. It has already been used in multiple projects as part of the [wmscaffold module](https://github.com/wieni/wmscaffold) and is in my opinion stable enough to be considered to be merged in Drush.
- `AskBundleTrait` and `ValidateEntityTypeTrait` are also included in https://github.com/drush-ops/drush/pull/4926, https://github.com/drush-ops/drush/pull/4928 and https://github.com/drush-ops/drush/pull/4929. 
- `FieldDefinitionRowsOfFieldsTrait` is also included in https://github.com/drush-ops/drush/pull/4928.
- `./vendor/bin/drush bfi` => _Not enough arguments (missing: "entityType")._
- `./vendor/bin/drush bfi node` => Lists the default columns
- `./vendor/bin/drush bfi node …
> Add field:base-info command

- src/Drupal/Commands/core/BaseFieldOverrideCreateCommands.php
- src/Drupal/Commands/core/FieldBaseOverrideCreateCommands.php
- src/Drupal/Commands/core/drush.services.yml
- tests/functional/FieldTest.php
This PR adds a command to create a [base field override](https://www.drupal.org/project/base_field_override_ui). It has already been used in multiple projects as part of the [wmscaffold module](https://github.com/wieni/wmscaffold) and is in my opinion stable enough to be considered to be merged in Drush.
- `AskBundleTrait` and `ValidateEntityTypeTrait` are also included in https://github.com/drush-ops/drush/pull/4926, https://github.com/drush-ops/drush/pull/4928 and https://github.com/drush-ops/drush/pull/4930. 
- `./vendor/bin/drush bfoc` => _Not enough arguments (missing: "entityType")._
- `./vendor/bin/drush bfoc node` => Asks for bundle
- `./vendor/bin/drush bfoc node --no-interaction` => _The bundle argument is required._
- `./vendor/bin/drush bfoc node article` => Asks for field …
> Add field:base-override-create command

- src/Drupal/Commands/field/FieldCreateCommands.php
Since the Cancel option is removed from choice lists (#4907), the numerical indexes changed. Commands that use an indexed array for options and that have a default value will have to update that default value. I haven't found another occurrence of this issue in Drush core.
> Fix default value of the field:create cardinality option

- src/Drupal/Commands/field/FieldCreateCommands.php
- src/Style/DrushStyle.php
Symfony doesn't provide a simple way to make a question required, if you want to do so you have to create a validator callback. Having to write this for multiple commands causes a lot of boilerplate, which is why I propose adding this method to DrushStyle.
So far there's only 1 use case in Drush core, but I have more use cases in contrib projects.
> Add askRequired helper to DrushStyle

- src/Drupal/DrupalKernelTrait.php
This notice appears for me when uninstalling a module through a `drush cim`, using PHP 8.1.
```
[error]  Message: /Deprecated function/: file_exists(): Passing null to parameter #1
($filename) of type string is deprecated in
/Drush\Drupal\DrupalKernel->addDrushServiceProvider()/ (line /209/ of
//Users/dieterholvoet/Projects/sites/whathappens/vendor/drush/drush/src/Drupal/DrupalKernelTrait.php/).
Drush\Drupal\DrupalKernel->addDrushServiceProvider('_drush.minimal', NULL)
(Line: 132)
Drush\Drupal\DrupalKernel->addModuleDrushServiceProvider('minimal',
'core/profiles/minimal/minimal.info.yml') (Line: 121)
Drush\Drupal\DrupalKernel->discoverServiceProviders() (Line: 1305)
Drupal\Core\DrupalKernel->initializeServiceProviders() (Line: 1211)
Drupal\Core\DrupalKernel->compileContainer() (Line: 900) …
```
> Fix PHP 8.1 deprecation notice

- box.json.dist
- composer.json
- docs and examples not useful out of phar
- apply GZ compression, zlib is PHP requirement
- clean-up extra files from vendor
Fixes #4856
> Minimize .phar size

- src/Commands/DrushCommands.php
- src/Log/DrushLoggerManager.php
- src/Log/Logger.php
- src/Runtime/DependencyInjection.php
- src/Runtime/Runtime.php
- sut/drush/Commands/SimpleSutCommands.php
- tests/integration/CustomLoggerTest.php
Refs #4422 and implements the suggestion at https://github.com/consolidation/log/issues/20#issuecomment-1008483330. DrushLoggerManager is a slightly customized version of the Consolidation/Log/LoggerManager.
The changes in Runtime.php illustrate my guess as to when and how a site would swap a custom Logger for Drush's. I think that we could refactor our front controller (i.e. [$runtime->run()](https://github.com/drush-ops/drush/blob/77cb2ef52fcc58c6c9ce248c3655a5b4c9f8c06a/drush.php#L72)) such that a site could replace that controller with one that swaps in own Logger. Is that a promising way to go?
> Enable custom Logger(s).

- src/Sql/SqlBase.php
`drush core:status` worked in Drush 10 with a non-core db driver, but on Drush 11 it fails with
`TypeError: Drush\Sql\SqlBase::getInstance(): Return value must be of type ?Drush\Sql\SqlBase, none returned in Drush\Sql\SqlBase::getInstance() (line 114 of /home/runner/work/drudbal/drudbal/vendor/drush/drush/src/Sql/SqlBase.php).`
This seems due to introduced return typehinting in the `getInstance()` method. It is set to `?self` but if the driver class is missing there is no return stament called hence the TypeError.
> drush core:status no longer works in Drush 11 with non-core db drivers

- composer.json
- composer.lock
Necessary for drush to work on Drupal 10.0.x
```
$ composer require drush/drush 11.x-dev
Your requirements could not be resolved to an installable set of packages.
Problem 1
- grasmash/yaml-expander[1.1.1, ..., 1.2.0] require symfony/yaml ^2.8.11|^3 -> found symfony/yaml[v2.8.11, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev] but the package is fixed to v5.4.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
- grasmash/yaml-expander[1.3.0, ..., 1.x-dev] require symfony/yaml ^2.8.11|^3|^4 -> found symfony/yaml[v2.8.11, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev] but the package is fixed to v5.4.2 (lock file version) by a partial update and that version does not match. Make …
```
> Remove grasmash/yaml-expander as it is not used

- src/Sql/SqlBase.php
> drush core:status (still) no longer works in Drush 11 with non-core db drivers

- docs/install.md
Since Drupal 8 is EOL and Drupal 8.0 through 8.3 are now very very old, there seems to be little reason to make fine distinctions between Symfony 2 and Symfony 3 in the support matrix. Unless we are concerned about frustrating users trying to reconfigure Drupal 8.2 installations to work with unsupported Drush versions, we might as well clean up the table and make it a bit easier to read.
> Simplify compatiblity matrix now that Drupal 8 is EOL.

- src/Application.php
- tests/fixtures/drush-extensions/DrushExtensionsCommands.php
- tests/fixtures/drush-extensions/drush.yml
- tests/integration/CommandsFromConfigurationTest.php
- tests/unish/UnishTestCase.php
discoverCommandsFromConfiguration function was returning keys from $commandList instead of values. This caused that the returned values were the path to the command file instead of the class and therefore the classes (and commands) are not loaded.
The fix included in this PR makes the commands to load again.
> Return values instead of keys in discoverCommandsFromConfiguration.

- src/Commands/pm/SecurityUpdateCommands.php
I did some maintenance work on  drupal-composer/drupal-security-advisories and published security advisories for Drupal 9 on 9.x. The same advisories are published on 8.x-v2 for a while, this should not break older Drush releases.
> Update endpoint in SecurityUpdateCommands

- src/Drupal/Commands/core/DrupalCommands.php
Currently the example causes the following error.
> The user-entered string 'user/1' must begin with a '/', '?', or '#'.
> Fix usage example in core:route command

- box.json.dist
Don't blacklist internal/symfony as its used by the yaml dumper
https://github.com/drush-ops/drush/issues/5047
> Don't blacklist internal/symfony

- src/TestTraits/DrushTestTrait.php
Issue #5066 - PHP 8.1 null vs. \strlen()
> Issue #5066 - PHP 8.1 null vs. \strlen()

- src/Drupal/Commands/core/UserCommands.php
With PHP 8.1 I'm running
```
drush user:role:add moderator john
```
and I'm getting:
> explode(): Passing null to parameter #2 ($string) of type string is deprecated in /Drush\Utils\StringUtils::csvToArray()
The error pops up for both, lack of `--uid` and lack of `--mail`
> PHP 8.1 deprecation messages when the user has no mail or uid

- composer.json
- composer.lock
See https://www.drupal.org/node/3266017. Various consolidation components need psr/log v2 or v3 compat before drush's `test_81_drupal10_highest` tests will pass.
> Remove psr/log as direct dependency

- src/Commands/core/StatusCommands.php
Helps with https://github.com/consolidation/site-process/issues/56
> Canonicalize all paths in status output.

- docs/using-drush-configuration.md
This should now work and the link can probably be removed from the docs.
> Remove link referencing closed PR regarding site-specific config.

- src/Drupal/Commands/core/EntityCommands.php
Let's assume there are only 5 entities, but chunk size is set as 250. The progress bar shows "5" => "0%" for one second and immediately switch to "250" => "100%". While the progress should only rise by the actual number of entity IDs in the current `$chunk`.
> Fix entity command batch progress bar

- docs/using-drush-configuration.md
Setting `drush.backup-dir` as outlined in the docs was not working for me. `FsUtils::getBackupDirParent()` seems to be looking for the config at `drush.paths.backup-dir`.
https://github.com/drush-ops/drush/blob/287400c51a2e3a83cb95440826ce12d2d95956f6/src/Utils/FsUtils.php#L63
This PR changes the docs to reflect that, although maybe `FsUtils` should be updated instead?
> Move `backup-dir` under `drush.paths` in config docs.

- docs/install.md
Drupal 7's End-of-Life was extended to November 1, 2023: https://www.drupal.org/psa-2022-02-23
@greg-1-anderson:
> Yes, the documentation is out of date. Drush 8 will continue to be supported for the lifetime of Drupal 7.
From https://github.com/drush-ops/drush/issues/5092#issuecomment-1065959827.
> Update Drush 8 EOL date to November 2023

- src/Drupal/Commands/core/RoleCommands.php
> Preserve ability to not pass a role label (for now).

- src/Commands/core/UpdateDBCommands.php
Core is likely to add support for post updates in themes. See https://www.drupal.org/project/drupal/issues/3259188
This PR changes drush to support this in a BC compatible way.
I think this should go back to 10.x too depending on which branches https://www.drupal.org/project/drupal/issues/3259188 ends up in.
> Run theme post updates when supported by core

- src/Psysh/DrushHelpCommand.php
PHP 8.2 deprecates string interpolation patterns that place the dollar sign outside the curly braces. This fixes such patterns by replacing them with proper curly braced patterns.
Fix: `Drush\Psysh\DrushHelpCommand::execute()`
Reference:
- [PHP.Watch: `${var}` string interpolation deprecated](https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated)
- [wiki.php.net RFC](https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation)
> [PHP 8.2] Fix deprecated `${var}` string interpolation patterns

- src/Drupal/Commands/field/FieldDeleteCommands.php
> The field:delete command deletes fields from all bundles instead of only the requested bundles.

- src/Attributes/Bootstrap.php
When using PHPStan, there is an error with the following code:
Code:
```
#[CLI\Bootstrap(level: DrupalBootLevels::NONE)]
```
Error:
```
Parameter $level of attribute class Drush\Attributes\Bootstrap constructor expects string, int given. 
```
All constants are integers. When passing a stringified zero (`'0`) the attribute fails. So it's documented as a string but actually wants an integer.
> Bootstrap levels are `int` in DrupalBootLevels

- src/Drupal/Commands/core/DrupalCommands.php
`drush route --path` is one of may favorite Drush commands. However, it feels a bit boring to manually extract path from URL.
Add `url` option. So that the URL copied from the browser address bar can be pasted directly to the command line.
Example:
```
drush route --url=https://example.com/node/1
```
> Add url option to the core:route command
