- commands/core/variable.drush.inc
- tests/variableTest.php
> #499: Maintain Drush 5 compatible output from vget

- commands/make/make.project.inc
- commands/pm/package_handler/git_drupalorg.inc
- commands/pm/pm.drush.inc
- tests/makeTest.php
> Fix datestamp to time of last commit.

- commands/core/config.drush.inc
> Adds an option to view overridden config.

- drush.complete.sh
- includes/sitealias.inc
- tests/siteSetUnitTest.php
Ported #64 from the 6.x branch to master.
> Made site alias envvar file multi user aware.

- includes/sitealias.inc
> Issue #1263: Fix fatal error: Call to a member function db_spec() on boolean

- drush.php
- lib/Drush/Boot/BaseBoot.php
- lib/Drush/Boot/Boot.php
- lib/Drush/Boot/DrupalBoot8.php
Also refactored drupal8_bootstrap().
> Insure that kernel->terminate is called at the end of commands.

- commands/make/make.drush.inc
This is a useful command for converting from the legacy makefile format to YAML. 
I have a feeling I may not be using best practices by manually adding a `require` statement here. Open to feedback!
> Adding command to convert legacy makefiles to yaml.

- lib/Drush/UpdateService/StatusInfoDrush.php
> Avoid overwrite of calculated update data with release info. Fixes #1157

- tests/coreTest.php
Fixes the regression in testing from #382.
> Resume testing for drush dd with a better theme for testing.

- lib/Drush/UpdateService/Project.php
ref: https://github.com/drush-ops/drush/issues/1295
> Allow major versions of '0'.

- drush.php
> Use the right boostrap object

- includes/environment.inc
> Use explicit 'env' for remote command execution

- commands/sql/sql.drush.inc
- includes/drush.inc
> find SQL class in Drupal drivers

- commands/make/generate.contents.make.inc
- commands/make/make.drush.inc
- commands/make/make.utilities.inc
This should fix #1268. Let's see what TravisCI thinks.
> Fix for issue #1268

- commands/core/core.drush.inc
- tests/Unish/CommandUnishTestCase.php
- tests/outputFormatTest.php
Per #1339.  Seems like a good idea.
> #1339: Add path to Drush script to 'drush status' command.

- commands/user/user.drush.inc
- lib/Drush/User/User6.php
- lib/Drush/User/User7.php
- lib/Drush/User/User8.php
Use UserVersion->getUid() instead.
Fixes  #1354
> Don't access uid directly, as it differs between drupal versions.

- examples/example.aliases.drushrc.php
- examples/example.drushrc.php
- examples/policy.drush.inc
- examples/sandwich.drush.inc
- examples/xkcd.drush.inc
- lib/Drush/Boot/DrupalBoot.php
See https://github.com/drupal-composer/drupal-project/issues/20
> Also search for configuration in a 'drush' directory above the webroot.

- lib/Drush/Sql/Sqlsqlsrv.php
See https://github.com/drush-ops/drush/issues/1421 for details.
> Allow Windows Authentification mode (no login).

- commands/pm/download.pm.inc
- commands/pm/pm.drush.inc
- commands/pm/updatestatus.pm.inc
- lib/Drush/UpdateService/StatusInfoDrush.php
> Honor 'project status url' and --source option. Fixes #1321

- commands/pm/updatecode.pm.inc
- drush.api.php
- examples/pm_update.drush.inc
Fix invocation of the hook, and adds an example implementation, useful for #596
> Add an example command that restores sqlsrv driver after pm-update

- drush.complete.sh
I read this article (https://www.lullabot.com/articles/switching-drush-versions) and I see that no provide autocomplete for drush8
> Support autocomplete for drush8

- commands/core/drupal/update.inc
- Core change: https://www.drupal.org/node/2535082
> Update hooks are run prior to automatic entity definition updates.

- commands/make/generate.make.inc
Let's see how TravisCI likes this.
> Fixes #1397: Fix dev snapshot version numbers when generating makefile.

- commands/core/config.drush.inc
Or maybe this instead #1571 for #1570
> More informative message with config-import error

- lib/Drush/Sql/Sqlpgsql.php
As mentioned in the issue, I'm not sure if this has any repercussions, but it does fix a bug on my system.
> Issue #1376: Fix sql-drop on PostgreSQL

- commands/core/core.drush.inc
- commands/core/drupal/update.inc
- Corresponding Drupal core issue: https://www.drupal.org/node/2542748
This can probably be merged prior to the core issue.
> Only apply automatic entity updates if option is set.

- tests/README.md
Because why not? :) Works on Github.com and in PhpStorm.
> Hyperlink reference to phpunit.xml.dist in tests/README.md.

- includes/sitealias.inc
Follow-up for https://github.com/drupal-composer/drupal-project/pull/35
> Search for site-aliases outside the web root

- lib/Drush/Sql/Sqlpgsql.php
Fixes #1129 
Note that there is http://www.postgresql.org/message-id/4EEB5BCD.2070007@archonet.com which apparently was fixed in version 9.2, so you need that at least for this to work. (At least I think that's true, I have 9.4.5 locally.)
> Support passwords with : and \ in PostgreSQL

- lib/Drush/Sql/Sqlmysql.php
This pull request fixes issue #1702.
I think it should be manually tested before merging.
> Use wildcard in host name in GRANT ALL PRIVILEGES

- includes/backend.inc
This should do the trick; just lettiing Travis run all the tests.
> #1711: Fix backend simulate.

- includes/output.inc
See https://www.drupal.org/node/2575703#comment-10516850
> Fix FormattableMarkup Invalid placeholder error

- includes/drupal.inc
- lib/Drush/Boot/BaseBoot.php
- lib/Drush/Boot/Boot.php
- lib/Drush/Boot/DrupalBoot.php
- lib/Drush/Boot/DrupalBoot6.php
- lib/Drush/Boot/DrupalBoot7.php
- lib/Drush/Boot/DrupalBoot8.php
Fixes https://github.com/drush-ops/drush/issues/1724 for master.
> Issue #1724: Move logic for version information into Boot classes.

- commands/core/drupal/environment.inc
> Don't discard hidden themes if configured as default or admin

- composer.json
- composer.lock
I tested and seems to have no issues.
> Update psy/psysh dependency to 0.6.0

- commands/core/cli.drush.inc
- lib/Drush/Psysh/Caster.php
just a refactor to move the caster callbacks into a class with static methods.
> Move caster callbacks into a Caster class

- commands/pm/pm.drush.inc
- commands/pm/projectinfo.pm.inc
- tests/pmEnDisUnListInfoTest.php
> Bring pm-projectinfo in drush

- commands/pm/pm.drush.inc
Fixes #881
Also fix a bug when asked for several projects with coincident release numbers.
> Adapt pm-releases to support more fields

- commands/make/make.drush.inc
- commands/make/make.utilities.inc
- docs/make.md
Pretty simple implementation of #1151.
> Fixes #1151: Add option to include makefiles on the fly.

- commands/pm/package_handler/wget.inc
> Fixes #1915. Strict comparison ensures hashes are truly the same.

- includes/bootstrap.inc
- includes/environment.inc
- lib/Drush/Boot/DrupalBoot.php
Continuation of #1755.  Removed conditionals. Will merge once tests pass; will add more debug logging levels in a separate PR.
> Rmuit bootstrap logging

- commands/make/make.drush.inc
Ran into the issue discussed in #1759 while using drush 7. The same fix works without any changes, so have just cherrypicked the same commit over.
> Backport fix for #1759 to Drush 7

- includes/environment.inc
- tests/generateMakeTest.php
> Fix make-generate test.

- commands/make/generate.contents.make.inc
- tests/lockMakeTest.php
- tests/makefiles/lock-default.make.yml
- tests/makefiles/lock-git.make.yml
- tests/makefiles/lockfiles/default.lock.yml
- tests/makefiles/lockfiles/git.lock.yml
Here's a pretty straight-forward solution to #2000.
> Fixes #2000: Resolve git branches and revisions in make-lock.

- .travis.yml
- tests/commandTest.php
- tests/pmDownloadTest.php
- tests/pmEnDisUnListInfoTest.php
Let's find out how many of the unit tests actually pass on Drupal 6.  Just running one test group to start out.
> Try testing just one testing group with Drupal 6.

- composer.json
- composer.lock
- docs/install.md
- drush.info
- includes/preflight.inc
Merge into master branch after 8.x branch created.
> Changes to make for Drush 9. 

- drush.complete.sh
Change **which** test to command test for better reliability. Pull request per https://github.com/drush-ops/drush/issues/521#issuecomment-203462556
> Replacing which with command test for better reliablity.

- commands/core/drupal/batch.inc
> Use Drupal 8's batch.storage service when available in batch.inc

- commands/make/generate.contents.make.inc
> Allows custom locations to be included in make-lock files.

- lib/Drush/Sql/Sqlmysql.php
> Add support for SSL MySQL connections

- .travis.yml
- lib/Drush/UpdateService/Project.php
- lib/Drush/UpdateService/ReleaseInfo.php
- tests/coreTest.php
- tests/pmDownloadTest.php
- tests/pmUpdateCodeTest.php
Backport of #2146 for Drush-7.
> Fix 6 backport

- lib/Drush/Boot/DrupalBoot8.php
- lib/Drush/Command/ServiceCommandlist.php
- lib/Drush/Drupal/DrupalKernel.php
- lib/Drush/Drupal/DrushServiceModfier.php
- lib/Drush/Drupal/FindCommandsCompilerPass.php
- tests/resources/modules/d8/woot/src/Command/GreetCommand.php
- tests/resources/modules/d8/woot/woot.services.yml
The main question here is whether creating our own subclass of DrupalKernel is a better tradeoff than using service parameters.  I think it probably is.
> Tagged services

- commands/make/make.download.inc
- commands/make/make.project.inc
- docs/make.md
> Fixes #2189: Support 'no-core' tarballs for profile downloads.

- lib/Drush/Boot/DrupalBoot8.php
https://github.com/drush-ops/drush/issues/2258
> Fixes #2258 : Disable automated cron on drush requests

- tests/makeTest.php
The SVN repo doesn't appear to exist anymore.
> Skip SVN tests for now.

- lib/Drush/UpdateService/Project.php
- tests/pmDownloadTest.php
Expected to fail. Fix is #2274
> Test project versions are checked strictly (no numeric equivalence).

- includes/startup.inc
Just some better hygiene here.
> Use DIRECTORY_SEPARATOR in startup.inc.

- commands/core/site_install.drush.inc
- lib/Drush/Sql/SqlBase.php
- lib/Drush/Sql/Sqlmysql.php
- lib/Drush/Sql/Sqlsqlite.php
- tests/makefiles/qd-devel.make
Also fixes missing error handling
> Fix SQL hostname for localhost #2017

- includes/preflight.inc
> Issue #2320: Fixing typo in includes/preflight.inc.

- commands/sql/sqlsync.drush.inc
- includes/environment.inc
- includes/filesystem.inc
- includes/sitealias.inc
- lib/Drush/Sql/SqlBase.php
> Canonicalize 'root' in site alias records.

- docs/install.md
> Update install.md - Fixed upcoming release path

- commands/make/make.download.inc
While working on #2249 I found a function that's not used anywhere, fancy remove it?
> Remove unused function _make_download_file_move()

- includes/output.inc
> Convert legacy translation placeholders to valid D8 placeholders

- includes/annotationcommand_adapter.inc
- includes/preflight.inc
- lib/Drush/Commands/core/StatusCommands.php
- lib/Drush/Drupal/DrushServiceModfier.php
- tests/annotatedCommandTest.php
- tests/resources/global-includes/Commands/FoobarCommands.php
- tests/resources/modules/d6/woot/Commands/WootCommands.php
- tests/resources/modules/d7/woot/Commands/WootCommands.php
- tests/resources/modules/d8/woot/src/Commands/AnnotatedGreetCommand.php
- tests/resources/modules/d8/woot/src/Commands/GreetCommand.php
- tests/resources/modules/d8/woot/src/Commands/WootCommands.php
- tests/resources/modules/d8/woot/woot.services.yml
> Drush 8.x version of global and site annotated commands

- commands/core/core.drush.inc
- includes/annotationcommand_adapter.inc
- lib/Drush/Commands/core/CoreCommands.php
- lib/Drush/Commands/core/StatusCommands.php
- tests/shellAliasTest.php
Also ports core-global-options topic.
> Handle @topic and @topics annotations in adapter.

- commands/sql/sql.drush.inc
- lib/Drush/Commands/core/SanitizeCommands.php
- tests/resources/user_fields-D8.php
- tests/sqlSyncTest.php
> Adding sanitation of user Fields for Drupal 8. (#2457)

- composer.json
- composer.lock
I'll explain this if the tests pass (as they should).
> Use output-formatters:~3

- lib/Drush/Boot/DrupalBoot.php
> change $_SERVER['REQUEST_METHOD'] default to 'GET'

- commands/core/drupal/update.inc
This is a backport of bc8bb69e9e44b958e8e22cb175e7523ad113a281
> Fixes #2617: Perform cache rebuild during updb in same process

- composer.json
- composer.lock
- src/Command/DrushInputAdapter.php
update of pull request https://github.com/drush-ops/drush/pull/2477
see https://www.drupal.org/node/2712647#comment-11981323
> Update symfony to 3.2

- src/Commands/config/ConfigCommands.php
- src/Commands/config/ConfigExportCommands.php
- src/Commands/sql/SqlSyncCommands.php
- src/Log/Logger.php
- src/Sql/SqlBase.php
- tests/configPullTest.php
A few unrelated fixes. The commits deal with each fix discretely.
> Error logging and rsync fixes

- includes/drush.inc
- src/Commands/DrushCommands.php
- src/Commands/config/ConfigCommands.php
- src/Commands/config/ConfigExportCommands.php
- src/Commands/config/ConfigImportCommands.php
- src/Commands/core/CacheCommands.php
- src/Commands/core/EditCommands.php
- src/Commands/core/ImageCommands.php
- src/Commands/core/InitCommands.php
- src/Commands/core/RsyncCommands.php
- src/Commands/core/SiteInstallCommands.php
- src/Commands/core/TopicCommands.php
- src/Commands/core/UpdateDBCommands.php
- src/Commands/core/UserCommands.php
- src/Commands/core/WatchdogCommands.php
- src/Commands/pm/PmCommands.php
- src/Commands/sql/SanitizeCommands.php
- src/Commands/sql/SqlCommands.php
- src/Commands/sql/SqlSyncCommands.php
- src/Style/DrushStyle.php
- tests/configPullTest.php
Its a little awkward to handle the 'cancel' choice ourselves but I see no way to provide that otherwise.
> Fix #2680 Use Symfony questionHelper

- tests/resources/codebase/composer-highest.json
https://github.com/drupal-composer/drupal-core/commit/4d72d770023aa8cb3be09df97ca8f30a782764d8
https://www.drupal.org/node/2712647?page=1#comment-12065971
https://github.com/drush-ops/drush/pull/2724
> Remove reference to webflo/drupal-core-8.4.x

- src/Sql/SqlSqlite.php
Discovered the syntax error via https://travis-ci.org/drupal-composer/drupal-project/jobs/228240373
> Fix PHP syntax error in SqlSqlite

- src/Sql/SqlSqlite.php
The SqlSqlite backend throws a few notices.
> Fix notices in SqlSqlite class

- src/Commands/core/SiteInstallCommands.php
- Handle exception from drupal_get_profile when container ist not initialized and db connection not defined yet.
- Reimplement distribution detection (reverts 7b609a4)
---
I did some debugging for https://github.com/drupal-composer/drupal-project/pull/270 and found the root cause in commit 7b609a4.
> Fix site-install command

- src/Commands/core/DocsCommands.php
- src/Commands/core/SiteInstallCommands.php
- src/Commands/help/HelpCLIFormatter.php
- src/Commands/help/HelpCommands.php
- src/Commands/help/ListCommands.php
Looks good. One last problem is that the list command is not wrapping correctly in the table containing command list. Use a narrow window and see command description wrap like it used to.
> Use tableFormatter in help and cli commands.

- docs/make.md
Implemented in https://www.drupal.org/node/840540 (3 years ago)
> Documented local paths for patches in makefile

- includes/preflight.inc
Was introduced with removal of Launcher.
> Remove redispatch infinite loop 

- commands/core/cache.drush.inc
Pull request to fix issue #2725
> Workaround segmentation fault when clearing caches.

- .travis.yml
- lib/Drush/Command/DrushInputAdapter.php
- tests/Unish/UnishTestCase.php
- tests/archiveDumpTest.php
- tests/bootstrap.inc
- tests/makeTest.php
#2724 was never backported to the Drush 8.x branch.
> Backport #2724 / f476dd51 (Sans Symfony 3) to Drush 8.x.

- src/Commands/generate/Helper/InputPreprocessor.php
Moving from magical numeric indexes to Question setters should make the code more readable.
> Make input preprocessor work with Question objects

- composer.json
- src/Commands/generate/Helper/InputHandler.php
This should work equally for module and theme generators.
> Set extension name automatically when possible

- src/Drupal/Commands/core/CliCommands.php
Master port of https://github.com/drush-ops/drush/pull/2822
> Disable the psysh version check

- commands/user/user.drush.inc
> Issue #2832: Fix passing incorrect type to dt/t causing error in PHP 7.1

- includes/drush.inc
> 8.x version of #2836: create_function is deprecated in php 7.2

- includes/drush.inc
Might as well use an anonymous function instead.
> Fixes #2831: create_function is deprecated in php 7.2

- includes/startup.inc
> Workaround for #2065: Additional use_pcntl_exec check

- commands/sql/sql.drush.inc
See https://github.com/drush-ops/drush/issues/34#issuecomment-326548684
> Ensure "sql-cli" command sets an error on non-zero child process exit status

- composer.lock
> Revert "Update Psysh to version 0.8.11"

- composer.lock
Testing again with new PR and `composer update` run. See https://github.com/drush-ops/drush/pull/2913 and https://github.com/drush-ops/drush/pull/2935
> Update psysh to 0.8.11

- src/Boot/DrupalBoot.php
- src/Command/GlobalOptionsEventListener.php
- src/Commands/core/CacheCommands.php
- src/Preflight/LegacyPreflight.php
Started down this road, but decided it wasn't worth the time.  Might merge this if the tests all pass tho.
> Symfony dispatch remove some preflight

- src/Preflight/PreflightArgs.php
Convert to 'hel…p' command if found.
> Identify --help and -h during args preprocessing

- src/Commands/DrushCommands.php
> Make DrushCommands::printFile protected.

- src/Config/ConfigLocator.php
- src/Preflight/Preflight.php
- src/SiteAlias/SiteAliasManager.php
Move responsibility of site alias path building to the configlocator and only add environment if the config is --local.
> Move responsibility of site alias path building to the configlocator

- isolation/tests/ArgsPreprocessorTest.php
- src/Config/ConfigLocator.php
- src/Preflight/Preflight.php
- src/Preflight/PreflightArgs.php
Treat all path config as list of paths instead of a string path.
> Config path merging and list of arrays

- commands/core/config.drush.inc
@weitzman Thanks for the original fix. I hope you will accept this back-port to 8.x.
> Backport to 8.x #2604 Allow delete of single value in a config object

- includes/drush.inc
> #3039 : Fixed numeric notice in PHP 7.x.

- drush.php
- src/Application.php
- src/Preflight/ArgsRemapper.php
- src/Preflight/Preflight.php
- src/Runtime/DependencyInjection.php
- src/Runtime/RedispatchHook.php
- src/Runtime/Runtime.php
- src/Runtime/TildeExpansionHook.php
Just a refactoring for better separability of responsibilities.
> Drush runtime

- src/Commands/sql/SqlSyncCommands.php
- tests/sqlSyncTest.php
… when importing the sql database in sql:sync.
> Fixes #3046: Use correct target alias record 

- src/Commands/core/SiteInstallCommands.php
> Fix option name in site-install exception

- src/Drupal/DrupalKernel.php
- tests/resources/modules/d8/woot/composer.json
Still needs to check the Drush version in a meaningful way.
> Check to see if Drush extensions are compatible with the current version.

- includes/batch.inc
- src/Commands/core/UpdateDBCommands.php
- src/Drupal/Commands/core/BatchCommands.php
- tests/UpdateDBTest.php
- tests/resources/modules/d8/woot/woot.install
- tests/resources/modules/d8/woot/woot.post_update.php
> updatedb: return exit code 1 on failure

- docs/hooks.md
I'm just fixing these as I find them - let me know if you'd prefer a PR with multiple changes.
> update hooks documentation

- includes/drush.inc
- includes/filesystem.inc
- tests/archiveDumpTest.php
> Issue #3199: Add ignored-directories option to 8.x

- composer.json
- src/Commands/generate/Generators/Drush/DrushAliasFile.php
- src/Commands/generate/Generators/Drush/DrushCommandFile.php
- src/Commands/generate/Generators/Migrate/MigrationGenerator.php
- src/Commands/generate/Helper/InputHandler.php
- tests/resources/modules/d8/woot/src/Generators/ExampleGenerator.php
This might require manual testing.
> Remove deprecated code from Drush generators

- src/Drupal/Commands/core/UserCommands.php
> fix password array key

- src/Commands/generate/Generators/Drush/default-methods.twig
> replace dashes with colons in dcf default method annotations

- src/Preflight/Preflight.php
- src/SiteAlias/SiteAliasFileLoader.php
- src/SiteAlias/SiteAliasManager.php
- tests/AnnotatedCommandTest.php
> Replace substitutions in alias files with configuration values.

- tests/CommandUnishTestCase.php
> Remove undefined constant from CommandUnishTestCase

- unish.sut.php
> Use absolute path to test codebase in unish_setup_sut()

- src/Config/Environment.php
- src/Preflight/RedispatchToSiteLocal.php
- src/SiteAlias/AliasRecord.php
- src/Utils/FsUtils.php
This is a partial resolution to #3110.
> #3110: Prevent infinite loops in RedispatchToSiteLocal.

- includes/filesystem.inc
> The path in drush_tempdir() need to be properly joined 

- src/Drupal/Commands/config/ConfigCommands.php
- src/Drupal/Commands/config/ConfigExportCommands.php
- src/Drupal/Commands/config/ConfigImportCommands.php
> Fix #2563. Add diff preview to config-export

- src/Boot/DrupalBoot.php
> Add ending semicolon to SQL query

- src/Commands/core/UpdateDBCommands.php
- tests/UpdateDBTest.php
> Improve logging for the UpdateDB commands

- composer.json
- includes/output.inc
This should resolve #3226.
See pear/Console_Table#14 for details.
> Update pear/console_table package

- src/Commands/core/SiteInstallCommands.php
> Make SiteInstallCommands::getSitesSubdirFromUri find dir from sites.php (#3334)

- commands/sql/sql.drush.inc
> Backport #3341 to 8.x

- src/Boot/BootstrapManager.php
- src/Boot/DrupalBoot8.php
- src/Boot/Kernels.php
- src/Commands/core/SiteInstallCommands.php
- src/Drupal/InstallerKernel.php
Also uses non-deprecated method for getting install profile.
> Use Drupal’s InstallerKernel in site:install

- src/Drupal/Commands/config/ConfigImportCommands.php
> Fix config split when using config import

- src/Boot/BootstrapManager.php
- src/Commands/sql/SqlCommands.php
Less bootstrapping for sql commands.
> Support a new @max annotation in sql commands (fix #3389)

- src/Boot/BootstrapManager.php
> Fix '@bootstrap max'

- includes/preflight.inc
Alternate implementation of #3426
> Prevent 'drush @local uli' and related commands from executing twice.

- src/Preflight/Preflight.php
- src/Preflight/PreflightSiteLocator.php
- src/SiteAlias/SiteAliasFileLoader.php
- src/SiteAlias/SiteAliasManager.php
One step down the road to factor site alias classes into a separate project.
> Factor preflight class references out of site alias manager

- .travis.yml
Try again with base set correctly so that tests will (hopefully) run on Travis.
Otherwise the same as #3437.
> Add tests for Drupal 8.5.

- src/Application.php
Fix missing return from this [commit](https://github.com/drush-ops/drush/commit/500ec257857ed04cf6c76569d6593df7bcdf7571)
> fix: add missing return

- src/Commands/generate/Helper/InputHandler.php
> Remove outdated connection between name and machine name

- includes/batch.inc
> Call batch finished with call_user_func_array() to use static method call.

- commands/core/drupal/batch.inc
> Call batch finished with call_user_func_array() to use static method call

- src/Commands/LegacyCommands.php
> Remove the double 'the'

- tests/resources/codebase/composer-highest.json
- tests/resources/codebase/composer.json
Use a form that is less confusing to Composer.
> Change the 'require' for drush/drush in the sut 

- tests/UserTest.php
Content entity generator has got "translatable" option.
https://github.com/Chi-teck/drupal-code-generator/pull/10
> Update user cancel test to match upstream DCG changes

- src/SiteAlias/AliasRecord.php
https://github.com/drush-ops/drush/issues/3569
> #3569, Drush 9 aliases path is wrong when using symlink

- src/Commands/core/SiteInstallCommands.php
Fallback to default site directory in SubdirFromUri check
> Fix si breaking with uri and default directory

- src/Commands/core/UpdateDBCommands.php
This is the PR for 9.x/master
Unlike 8.x, post updates are unfortunately not re-using the code from core, so we have to duplicate it there.
Fixes #3604
> Set maintenance mode to update when running updates

- src/Drupal/Commands/core/CliCommands.php
- src/Psysh/DrushCommand.php
Fixes for https://github.com/drush-ops/drush/issues/3595
> Fixes #3595: Remove non-default options in REPL commands, Fix help command grouping

- src/Commands/core/UpdateDBCommands.php
Both exception branches have same 2 lines.
> Fix 3376. When an update fails, updatedb is still exiting with 0.

- tests/UpdateDBTest.php
- tests/resources/modules/d8/woot/woot.install
> Test coverage for Updatedb exits with 0 if TypeError occurs

- docs/cron.md
cd to the docroot shall be made prior to calling env / drush
> Update cron.md - invert env / docroot order

- docs/index.md
API Documentation's one was broken
> Fix and secure URL-s in docs' index

- src/Drupal/Commands/config/ConfigExportCommands.php
> Fix config:export not deleting collections

- src/Commands/help/ListCommands.php
- sut/drush/Commands/SimpleSutCommands.php
- sut/drush/Commands/custom/example-site-wide-command/NestedSutCommands.php
- sut/drush/Commands/custom/example-site-wide-command/src/NestedSrcSutCommands.php
Also mark SUT commands as hidden.
> Use new native isHidden() method in Help. 

- src/Commands/core/CacheCommands.php
Also, cache types may now accept arguments.
> Add way to clear cache bin(s) by name via 'drush cc bin [name]'

- src/Drupal/Commands/core/LocaleCommands.php
> Fixed notice Undefined variable: translationOptions

- src/Drupal/Commands/core/CliCommands.php
This adds https://github.com/drush-ops/drush/pull/3656 to master.
ping @greg-1-anderson
> Fixes #3656 in master: Adding cwd option to core-cli

- src/Config/Environment.php
- sut/autoload.php
See  - https://github.com/drush-ops/drush/issues/3741.
> Fix #3741 Handle global Drush9 edge case

- src/Config/Environment.php
Should have gone the other way, but here it is.
> Forward-port #3764 to master

- .circleci/config.yml
- .circleci/patch.sh
- tests/functional/UpdateDBTest.php
> Restore skipped test testUpdateModuleWithServiceDependency()

- .circleci/config.yml
- .circleci/patch.sh
> Apply patches that are compatible with the installed version of core

- includes/sitealias.inc
> Restore 91da7528, inadvertantly reverted.

- includes/filesystem.inc
- src/Commands/sql/SqlCommands.php
- src/Drupal/Commands/config/ConfigCommands.php
- src/Drupal/Commands/config/ConfigImportCommands.php
- src/Exec/ExecTrait.php
Use it in sql:* and config:export
> Fix ##1371. Move drush_program_exists() to ExecTrait

- src/Commands/sql/SqlCommands.php
- src/Sql/SqlBase.php
- src/Sql/SqlSqlite.php
Also use an exception in sqlite driver.
> Cleanup dump command slightly.

- .scenarios.lock/php5/composer.json
- .scenarios.lock/php5/composer.lock
- composer.json
- composer.lock
- src/Drush.php
- src/Runtime/DependencyInjection.php
- src/Runtime/RedispatchHook.php
- src/SiteAlias/ProcessManager.php
- tests/unish/UnishTestCase.php
c.f. https://github.com/consolidation/site-process/pull/21
> Use process manager

- src/Boot/BootstrapManager.php
- src/Runtime/RedispatchHook.php
- src/SiteAlias/ProcessManager.php
Making some more improvements related to config and process manager dependency injection et. al.
> Config and process

- src/Commands/pm/SecurityUpdateCommands.php
See https://github.com/drupal-composer/drupal-security-advisories/pull/11.
> Use updated security advisories feed. 

- src/Commands/core/UpdateDBCommands.php
> Propagate option negations to updatedb:status

- src/Commands/core/PhpCommands.php
- src/Drupal/Commands/config/ConfigCommands.php
- src/Drupal/Commands/core/StateCommands.php
> Update 3 commands to use new StdinAwareInterface.

- commands/make/make.download.inc
- commands/pm/package_handler/git_drupalorg.inc
- docs/make.md
- examples/example.make
- examples/example.make.yml
- tests/makeTest.php
- tests/makefiles/git.make
This PR is a combination of:
- #3902
- #3901 
- #3899
> Drupalorg updates

- .scenarios.lock/php5/composer.json
- .scenarios.lock/php5/composer.lock
- composer.json
- composer.lock
- src/Runtime/DependencyInjection.php
- src/SiteAlias/ProcessManager.php
More work will be required to allow configuration to provide overrides for site alias properties.
> Allow configuration to provide default values for site alias properties.

- docs/dependency-injection.md
Fixes documentation also on master as discussed in #3950
> Fix documentation example for DependencyInjection.

- commands/core/core.drush.inc
- commands/core/docs.drush.inc
Some that had too many ':'s should ha…ve been using '-'s instead.
> Fix backported command aliases

- .circleci/config.yml
- tests/functional/LanguageAddTest.php
- tests/functional/PmEnLocaleImportTest.php
failure at https://circleci.com/gh/drush-ops/drush/7039
> Fix failing test on highest.

- src/TestTraits/CliTestTrait.php
- tests/README.md
Initial user for this is https://www.drupal.org/project/devel/issues/3043002
> Auto set user agent for contrib modules using DrushTT.

- src/Commands/core/LoginCommands.php
- tests/functional/UserTest.php
See #4020 for more information.
> #4020 Added extra options for the drush user:login command

- .circleci/config.yml
- .scenarios.lock/php5/composer.json
- .scenarios.lock/php5/composer.lock
- .travis.yml
- composer.json
- composer.lock
- docker-compose.yml
- tests/phpunit.xml.dist
Helps with running BrowserTestBase as used by Drush Test Trait cases.
> Add webflo/drupal-core-require-dev

- .travis.yml
- commands/make/make.download.inc
- commands/make/make.drush.inc
- commands/pm/package_handler/git_drupalorg.inc
- commands/pm/pm.drush.inc
- docs/make.md
- examples/example.make
- examples/example.make.yml
- tests/coreTest.php
- tests/makeConvertTest.php
- tests/makeTest.php
- tests/makefiles/composer.json
- tests/makefiles/composer.lock
- tests/makefiles/lock-git.make.yml
- tests/makefiles/lockfiles/git.lock.yml
- tests/sqlSyncTest.php
Revert 'drush make' improvements and add mysql service to Travis build.
> Fix 8.x build

- drush.info
- src/Commands/core/StatusCommands.php
- src/Commands/sql/SqlSyncCommands.php
- src/Drupal/DrupalKernelTrait.php
- tests/functional/ConfigTest.php
- tests/functional/UpdateDBTest.php
- tests/functional/resources/modules/d8/woot/composer.json
Also warn when a commandfile doesn’t meet API constraint (was a debug log)
> Up version to 10 and improve unsatisfied constraint warning

- composer.json
- composer.lock
symfony/event_dispatcher version requirements
> fixes #4152

- .circleci/config.yml
- .travis.yml
- docs/install.md
- tests/README.md
- tests/functional/SiteSetTest.php
- tests/unish/UnishTestCase.php
After this PR, we are only using Travis for publishing api docs via sami.
This gets us testing unit+integration on Highest for free.
> Run integration and unit tests at Circle

- src/Drupal/Commands/config/ConfigExportCommands.php
- src/Drupal/Commands/config/ConfigImportCommands.php
- src/Drupal/Commands/config/drush.services.yml
Once this lands in core we could use the new services in drush too.
https://www.drupal.org/project/drupal/issues/3047812
> Change import and export commands to use the new core API

- composer.json
- composer.lock
- examples/example.site.yml
Followup for https://github.com/consolidation/site-process/pull/47
> Added env-vars key to example.site.yml

- src/Drupal/Commands/config/ConfigCommands.php
- src/Drupal/Commands/config/drush.services.yml
> #4194: drush config:status does not respect excluded modules

- src/Commands/core/LoginCommands.php
> Issue-4208: Fix User:login command incorrect url handling

- src/Drupal/Commands/core/QueueCommands.php
> Add --items-limit option to queue:run command

- includes/drush.inc
- src/Commands/config/ConfigImportCommands.php
- src/Drupal/Commands/config/ConfigImportCommands.php
- src/Drupal/Commands/core/EntityCommands.php
- tests/functional/ConfigTest.php
> Use the UpdateKernel for config:import.

- src/Commands/core/SiteInstallCommands.php
> Fix #4243. site-install doesn't use db connection in settings.php

- includes/drush.inc
- src/Commands/core/CoreCommands.php
- src/Commands/sql/SqlSyncCommands.php
- tests/functional/SqlSyncTest.php
A more minimalist implementation of #4245
> Stop sending —backend during sql:sync calls

- composer.json
- composer.lock
> Allow symfony/var-dumper 5.

- src/Drupal/Commands/sql/SanitizeUserFieldsCommands.php
- src/Drupal/Commands/sql/drush.services.yml
> Use entity_field.manager in user field sanitize plugin. Drupal 9 compat.

- lib/Drush/Sql/Sqlmysql.php
Drush 8 version of fix for #4259 that has been tested
> drush site-install fails with MySQL 8 #4259

- .circleci/config.yml
per https://www.drupal.org/node/3106075
> Bump Unish's Drupal 9 testing to PHP 7.3 

- docs/shellscripts.md
...remove it from the **arument** list and bootstrap...
> Small typo in shellscripts.md

- src/Utils/FsUtils.php
> Fix #4319. Missing application/gzip mime type

- docs/install.md
> Add release and EOL dates to Drush versions table

- src/TestTraits/OutputUtilsTrait.php
> Do not throw an exception when valid JSON data evaluates to empty PHP data

- src/Sql/SqlMysql.php
Fixes #4318
Tested with Mysql 5.6, Mysql 8.0 and MariaDB 10.1.
> Fix SQL user creation with MariaDB

- src/Drupal/Commands/config/ConfigCommands.php
- tests/functional/ConfigTest.php
> Output correct data for machine readable formats in config:status

- src/Drupal/Commands/core/DeployHookCommands.php
- src/Drupal/Commands/core/drush.services.yml
- tests/functional/DeployHookTest.php
- tests/functional/resources/modules/d8/woot/woot.deploy.php
> Add deploy:hook command for hook_deploy_NAME "update hooks"

- src/Drupal/Commands/core/WatchdogCommands.php
Fixes #3523 (in a more generic way).
> Document how to rerun watchdog:show every 2 seconds.

- includes/dbtng.inc
> MySQL 8 support for drush8

- src/Drupal/Commands/pm/ThemeCommands.php
> Don't check return value on theme uninstall

- docs/commands.md
As discussed in Slack, including src in command path will break discovery and cause other(unclear) problems. :)
> Note problems with having src in command path

- examples/example.site.yml
Only adds a snippet of code to an example file.
> #4382: Documenting rsync exclude-paths in site aliases

- .travis.yml
Note that we are still testing against all versions of php using the same lock file.
> Update the version of PHP used in tests.

- examples/example.drushrc.php
- includes/sitealias.inc
#4432
added option 'alias-search-depth'(Default: TRUE) in drushrc.php
> Drush8 alias files search depth

- composer.json
- composer.lock
> Declare the minimum supported version of Robo

- CONTRIBUTING.md
- docs/contribute/CONTRIBUTING.md
- docs/contribute/README.md
- mkdocs_base.yml
- tests/README.md
Expose CONTRUBUTION and Unish doc files
> Add Contribute top level menu to web site

- src/Commands/core/UpdateDBCommands.php
- src/Drupal/Commands/core/DrupalCommands.php
- src/Drupal/DrupalUtil.php
> Error message from requirements check on updatedb

- src/Drupal/Commands/core/UserCommands.php
> Better example in user:role:add

- appveyor.yml
- composer.json
- composer.lock
- src/Commands/DrushCommands.php
- src/Commands/pm/SecurityUpdateCommands.php
Now honors any HTTP_PROXY env variable
> Fix #4134,#4438. Use Guzzle to fetch json in security commands

- .gitattributes
- .github/workflows/main.yml
- .gitignore
- .scenarios.lock/php5/composer.json
- composer.json
- doctum-config.php
Replace Sami by [Doctum](https://github.com/code-lts/doctum)
> Replace abandoned Sami by Doctum

- composer.json
Fixes: https://github.com/drush-ops/drush/pull/4539
> Fix #4539, add php bin before .phar

- .github/workflows/main.yml
- composer.json
> Fix #4539, use  --ignore-parse-errors

- composer.json
> Remove composer branch-alias

- .circleci/config.yml
- .github/workflows/main.yml
- composer.lock
Updates composer-patches as well
> Use composer2 in CI

- .circleci/config.yml
Also start testing tip of Drupal 9.2
> Remove PHP 7.2 testing variant and update 2 others to Drupal 9.1.

- src/Sql/SqlMysql.php
Patch tested with MySql 8.  Also rough fake testing for MariaDB by hard-coding in a version string.
> Mysql 8.4616

- docs/output-formats-filters.md
Minor readability improvement.
> Use italics in doc page

- src/Boot/DrupalBoot8.php
This fixes the most recent error described on https://www.drupal.org/project/drupal/issues/2985199 (see comment 70)
> Fix container rebuilds on deployment identifier change

- .circleci/config.yml
- .scenarios.lock/install
- .scenarios.lock/php5/composer.json
- .scenarios.lock/php5/composer.lock
- .travis.yml
- composer.json
- composer.lock
- src/Drupal/Commands/pm/PmCommands.php
- tests/functional/PmEnDisUnListInfoTest.php
- tests/functional/RsyncTest.php
- tests/functional/SqlSyncTest.php
The main problem with a Drush 9 backport is ensuring that the tests still run
> Add "project" to pm:list (Drush 9 backport)

- composer.json
- composer.lock
- src/Commands/core/XhprofCommands.php
- removes useless dependency
- it will not fail if extra source for xhprof will be missing
- allows to override directory where to save the profile dump
> Allow to override the path to save profile dump 

- src/Commands/generate/Generators/Migrate/MigrationGenerator.php
- src/Commands/generate/Generators/Migrate/migration.yml.twig
> Update migrate generator for new MigrateRunnerCommands

- src/SiteAlias/ProcessManager.php
- src/TestTraits/CliTestTrait.php
> Fix #4402 by removing deprecated use of Process::inheritEnvironmentVariables

- includes/batch.inc
> No timeout for batch processing as we already re-spawn on low memory.

- src/Commands/pm/SecurityUpdateCommands.php
Per https://github.com/drush-ops/drush/pull/4657#issuecomment-822232915
> Zip extension no longer required in securityUpdateCommands

- src/Drupal/Commands/core/MigrateRunnerCommands.php
- src/Drupal/Migrate/MigrateExecutable.php
- tests/functional/WatchdogTailTest.php
- tests/integration/CustomLibraryCommandsAndGeneratorsTest.php
> Fix warnings on migrate rollback

- src/Drupal/Commands/core/MigrateRunnerCommands.php
- tests/functional/MigrateRunnerTest.php
> Reduce the default number of fields on migrate:status

- commands/core/locale.d8.drush.inc
This fixes the incorrectly set drush-9 style locale aliases.
> Fix locale aliases (drush-ops#4791)

- src/Drupal/Commands/core/DeployHookCommands.php
- tests/functional/DeployHookTest.php
PR for #4738
I am open to name it differently, have it ask for confirmation, expand the documentation etc...
> Add drush deploy:hook-skip (#4738)

- src/Commands/pm/SecurityUpdateCommands.php
> fix: --format=json not being respected by pm:security

- includes/batch.inc
Related to https://github.com/drush-ops/drush/pull/4839
> Fix PHP 8.1 compatibility for batch.inc

- src/Runtime/DependencyInjection.php
Keep only the newer part of https://github.com/drush-ops/drush/commit/3d91cf932991a4f19f3e845792134b69673164b7
> Only support league/container v3

- includes/batch.inc
Fix for https://github.com/drush-ops/drush/issues/3773
> I-3773: Fixed drush_backend_batch_process() not clearing batch_get()

- composer.json
- src/Psysh/Shell.php
> Make Drush compatible with newer versions of psysh

- .gitignore
- src/Commands/core/MkCommands.php
- Depends on https://github.com/consolidation/annotated-command/pull/247
> Add generators section to docs site.

- src/Drupal/Commands/core/drush.services.yml
- src/Drupal/Commands/field/EntityTypeBundleAskTrait.php
- src/Drupal/Commands/field/EntityTypeBundleValidationTrait.php
- src/Drupal/Commands/field/FieldBaseInfoCommands.php
- src/Drupal/Commands/field/FieldBaseOverrideCreateCommands.php
- src/Drupal/Commands/field/FieldCreateCommands.php
- src/Drupal/Commands/field/FieldDefinitionRowsOfFieldsTrait.php
- src/Drupal/Commands/field/FieldDeleteCommands.php
- src/Drupal/Commands/field/FieldInfoCommands.php
- src/Drupal/Commands/field/drush.services.yml
- src/Drupal/DrupalKernelTrait.php
> Move field commands into own namespace.

- .github/workflows/main.yml
- docs/commands.md
- docs/overrides/main.html
- mkdocs_base.yml
- Slightly more terse docs for Attributes
- Add last-updated date and authors to bottom of all docs pages.
> More terse Attributes example and Add last-updated date and authors to bottom of all docs pages.

- .circleci/config.yml
- commands/pm/pm.drush.inc
- tests/archiveDumpTest.php
- tests/coreTest.php
> Test on Drupal 9.3, stop testing on Drupal 8 (EOL)

- box.json.dist
by default box packaging only *.php files
Ref https://gist.github.com/andypost/1fa0be5c9231bab3e8e124c77598e171
> Add missing .php8 file

- src/Drupal/Commands/core/EntityCommands.php
- src/Drupal/Commands/core/MigrateRunnerCommands.php
- src/Drupal/Commands/core/drush.services.yml
- src/Drupal/Migrate/MigrateExecutable.php
- src/Drupal/Migrate/MigrateIdMapFilter.php
- src/Drupal/Migrate/MigrateMissingSourceRowsEvent.php
- src/Drupal/Migrate/MigratePrepareRowEvent.php
- src/Drupal/Migrate/MigrateUtils.php
Includes tightening typing and some cosmetic changes
> Inject migration plugin manager

- src/Drush.php
- src/Exec/ExecTrait.php
- src/Log/DrushLog.php
- src/Log/Logger.php
- src/Style/DrushStyle.php
- src/TestTraits/CliTestTrait.php
- src/TestTraits/DrushTestTrait.php
- src/TestTraits/OutputUtilsTrait.php
- More rector - quality set.
- A bit more Rector in /src
> More Rector in /src

- src/Commands/core/SiteInstallCommands.php
> Fixed sites.php file included without $sites variable defined.

- appveyor.yml
- src/Drupal/Commands/core/CliCommands.php
- src/Exec/ExecTrait.php
- src/Utils/FsUtils.php
> Fix CLI history path and startBrowser().

- src/Commands/DrushCommands.php
- src/Log/Logger.php
- src/Log/SuccessInterface.php
Implements https://github.com/consolidation/log/issues/20
> Add SuccessInterface to DrushLogger.

- src/Drupal/Commands/config/ConfigImportCommands.php
label argument was removed in #4848
> Remove reference to label argument

- src/Commands/LegacyCommands.php
Fixes https://www.drupal.org/project/devel_entity_updates/issues/3259523
> Dont define entity-updates

- src/Drupal/FindCommandsCompilerPass.php
> Ignore services on invalid reference

- src/Commands/core/EditCommands.php
> Fix core:status warning

- src/Drupal/Commands/pm/PmCommands.php
- tests/unit/ArgsRemapperTest.php
> Add pm:uninstall alias un

- composer.json
- composer.lock
- src/Commands/core/ArchiveDumpCommands.php
- src/Commands/core/ArchiveRestoreCommands.php
- src/Drupal/Commands/field/FieldDeleteCommands.php
- tests/functional/ArchiveTest.php
Resolves feedback in comments and merges the most recent 11.x updates into branch.
> Jabxjab archive dump command updates

- docs/install.md
> Revert "Link compatibility to new docs"
